import { EQUIPMENTS } from '../equipments'
import { INGREDIENTS } from '../ingredients'

export const GRILL = [
  {
    metaSeo: {
      title: 'Шашлык из свинины на кефире',
      description:
        'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
      keywords: ['шашлык', 'свинина', 'кефир', 'маринад', 'лук', 'зелень', 'базилик', 'укроп', 'петрушка'],
      'og:title': 'Шашлык из свинины на кефире',
      'og:description':
        'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-svininy-na-kefire',
      'og:image': '/static/recipes/grill/shashlyk-iz-svininy-na-kefire.jpeg',
      twitterTitle: 'Шашлык из свинины на кефире',
      twitterDescription:
        'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-svininy-na-kefire.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-svininy-na-kefire',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-svininy-na-kefire',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'шашлык',
      'маринад для шашлыка',
      'рецепт шашлыка',
      'как приготовить шашлык',
      'шашлык из свинины',
      'маринад для шашлыка из свинины',
      'шашлык на мангале',
      'как мариновать шашлык',
      'как замариновать шашлык',
      'сочный шашлык',
      'вкусный шашлык',
      'лучший шашлык',
      'рецепт шашлыка из свинины',
      'шашлык из курицы',
      'маринад для шашлыка с уксусом',
      'маринад для шашлыка с луком',
      'маринад для шашлыка с кефиром',
      'маринад для шашлыка с минералкой',
      'шашлык в духовке',
      'шашлык на решетке',
      'шашлык на углях',
      'шашлык дома',
      'шашлык из баранины',
      'шашлык из говядины',
      'шашлык из индейки',
      'шашлык из рыбы',
      'овощной шашлык',
      'маринад для куриного шашлыка',
      'специи для шашлыка',
      'лук для шашлыка',
      'какой маринад для шашлыка',
      'как жарить шашлык на мангале',
      'сколько жарить шашлык',
      'чем поливать шашлык при жарке',
      'как понять что шашлык готов',
      'какое мясо лучше для шашлыка',
      'в каком маринаде лучше шашлык',
      'сколько шашлыка на человека',
      'сколько нужно мяса на шашлык',
      '1 кг шашлыка сколько порций',
      'цена шашлыка',
      'шашлык на майские праздники',
      'шашлык на выходные',
      'шашлык на даче',
      'шашлык на природе',
      'шашлык летом',
      'шашлык на Новый год',
      'домашний шашлык из свинины',
      'шашлык без мангала',
      'шашлык в банке',
      'шашлык в духовке в банке',
      'шашлык из курицы в духовке',
      'шашлык из свинины с луком',
    ],
    categories: [{ name: 'grill' }],
    key: 'shashlyk-iz-svininy-na-kefire',
    name: 'shashlyk-iz-svininy-na-kefire',
    img: '/static/recipes/grill/shashlyk-iz-svininy-na-kefire.jpeg',
    title: 'Шашлык из свинины на кефире',
    description:
      'Мечтаете о по-настоящему нежном и сочном шашлыке из свинины? Попробуйте приготовить мясо в маринаде из кефира — это простой и эффективный способ добиться потрясающего результата. Особенно хорошо подходит свиная шея: она жирная, мягкая и быстро пропитывается ароматами специй. Главный секрет мягкости — в кефире. Этот кисломолочный продукт, независимо от жирности, содержит бактерии, которые при длительном мариновании разрушают жесткие волокна, делая мясо необычайно нежным. Чтобы усилить вкус, рекомендуем добавить в маринад свежую зелень — базилик, укроп и петрушку. Они придают шашлыку легкий травяной аромат и подчеркивают вкус мяса. Не забудьте про лук — он не только усиливает аромат, но и дополнительно смягчает свинину. Достаточно оставить мясо в маринаде на 4–6 часов, а лучше — на ночь, и результат вас приятно удивит. Приготовьте шашлык из свинины на кефире по нашему проверенному рецепту и наслаждайтесь идеальным вкусом с дымком! Такой маринад сделает ваш пикник незабываемым.',
    calories: 1999.06,
    preparation: 240,
    time: 40,
    level: 1,
    rating: 5,
    portions: 4,
    used: [74.36, 179.36, 20.2],
    ingredients: [
      {
        ...INGREDIENTS.onion,
        count: 8,
      },
      {
        ...INGREDIENTS.salt,
        count: 5,
      },
      {
        ...INGREDIENTS.groundBlackPepper,
        count: 5,
      },
      {
        ...INGREDIENTS.dill,
        count: 0.5,
      },
      {
        ...INGREDIENTS.basil,
        count: 1,
      },
      {
        ...INGREDIENTS.parsley,
        count: 0.5,
      },
      {
        ...INGREDIENTS.porkNeck,
        count: 2,
      },
      {
        ...INGREDIENTS.kefir32,
        count: 600,
      },
      {
        ...INGREDIENTS.oliveOil,
        count: 4,
      },
    ],
    equipments: [
      EQUIPMENTS.bowl,
      EQUIPMENTS.knife,
      EQUIPMENTS.cutBoard,
      EQUIPMENTS.blender,
      EQUIPMENTS.spoon,
      EQUIPMENTS.grill,
      EQUIPMENTS.tongs,
      EQUIPMENTS.lid,
      EQUIPMENTS.paperTowel,
      EQUIPMENTS.skewers,
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Подготовьте ингредиенты: хорошо промойте мясо и обсушите бумажным полотенцем. Удалите лишний жир и плёнки, чтобы шашлык получился мягким и не имел лишней жирности.',
        ingredients: [{ ...INGREDIENTS.porkNeck }],
      },
      {
        img: null,
        video: null,
        description:
          'Нарежьте свиную шею острым ножом на равные по размеру куски — так мясо прожарится равномерно и не пересохнет. Оптимально — кубики размером около 4–5 см.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Промойте зелень — укроп, базилик и петрушку — в холодной воде, затем обсушите. Разберите зелень руками и выложите в чашу блендера вместе с черешками.',
        ingredients: [{ ...INGREDIENTS.dill }, { ...INGREDIENTS.basil }, { ...INGREDIENTS.parsley }],
      },
      {
        img: null,
        video: null,
        description:
          'Добавьте к зелени оливковое или рафинированное растительное масло. Измельчите до состояния пасты — она придаст маринаду яркий аромат и насыщенный вкус.',
        ingredients: [{ ...INGREDIENTS.refinedVegetableOil }, { ...INGREDIENTS.oliveOil }],
      },
      {
        img: null,
        video: null,
        description:
          'В глубокой миске соедините куски мяса, кефир, луковые кольца, зелёную пасту, соль и перец. Всё хорошо перемешайте руками, чтобы маринад равномерно покрывал мясо.',
        ingredients: [
          { ...INGREDIENTS.kefir32 },
          { ...INGREDIENTS.onion },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Накройте миску крышкой или пищевой пленкой и оставьте мясо мариноваться минимум на 4 часа при комнатной температуре или на ночь в холодильнике.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Нанизайте мясо на шампуры или выложите на решетку. Жарьте на горячих углях до готовности, регулярно переворачивая, чтобы мясо подрумянилось со всех сторон. Подавайте с овощами и свежей зеленью.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из куриного бедра',
      description:
        'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
      keywords: ['шашлык', 'курица', 'кефир', 'маринад', 'лук', 'зелень', 'базилик', 'укроп', 'петрушка'],
      'og:title': 'Шашлык из куриного бедра',
      'og:description':
        'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kurinogo-bedra',
      'og:image': '/static/recipes/grill/shashlyk-iz-kurinogo-bedra.jpeg',
      twitterTitle: 'Шашлык из куриного бедра',
      twitterDescription:
        'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kurinogo-bedra.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinogo-bedra',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinogo-bedra',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['шашлык', 'курица', 'кефир', 'маринад', 'лук', 'зелень', 'базилик', 'укроп', 'петрушка'],
    categories: [{ name: 'grill' }],
    key: 'shashlyk-iz-kurinogo-bedra',
    name: 'shashlyk-iz-kurinogo-bedra',
    img: '/static/recipes/grill/shashlyk-iz-kurinogo-bedra.jpeg',
    title: 'Шашлык из куриного бедра',
    description:
      'Если вы хотите приготовить действительно сочный и ароматный шашлык из курицы — не нужно изобретать велосипед. Достаточно воспользоваться проверенным рецептом с простым, но эффективным маринадом на основе газированной воды. Такой способ маринования давно используют опытные кулинары: он придаёт мясу мягкость, делает его нежным и сохраняет сочность при жарке. Минимум усилий — максимум вкуса!',
    calories: 355,
    preparation: 120,
    time: 60,
    level: 1,
    rating: 5,
    portions: 8,
    used: [28.67, 14.61, 28.2],
    ingredients: [
      {
        ...INGREDIENTS.chickenThighFillet,
        count: 1,
      },
      {
        ...INGREDIENTS.carbonatedMineralWater,
        count: 100,
      },
      {
        ...INGREDIENTS.salt,
        count: 12,
      },
      {
        ...INGREDIENTS.groundBlackPepper,
        count: 2,
      },
      {
        ...INGREDIENTS.vegetableOil,
        count: 2,
      },
      {
        ...INGREDIENTS.onion,
        count: 1,
      },
      {
        ...INGREDIENTS.lavash,
        count: 2,
      },
      {
        ...INGREDIENTS.greens,
        count: 16,
      },
    ],
    equipments: [
      EQUIPMENTS.knife,
      EQUIPMENTS.cutBoard,
      EQUIPMENTS.bowl,
      EQUIPMENTS.spoon,
      EQUIPMENTS.lid,
      EQUIPMENTS.tongs,
      EQUIPMENTS.grill,
      EQUIPMENTS.skewers,
      EQUIPMENTS.paperTowel,
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Филе куриного бедра тщательно промойте, обсушите бумажными полотенцами. Нарежьте мясо на крупные куски размером около 5–7 см. Посыпьте солью и молотым перцем, аккуратно перемешайте.',
        ingredients: [
          { ...INGREDIENTS.chickenThighFillet },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Очистите лук и нарежьте его полукольцами толщиной около 0.5–1 см. Добавьте его к мясу вместе с растительным маслом. Всё тщательно перемешайте ложкой или руками.',
        ingredients: [{ ...INGREDIENTS.onion }, { ...INGREDIENTS.vegetableOil }],
      },
      {
        img: null,
        video: null,
        description:
          'Влейте в мясо с луком газированную минеральную воду. Перемешайте всё ещё раз, накройте миску крышкой и оставьте мариноваться минимум на 2 часа.',
        ingredients: [{ ...INGREDIENTS.carbonatedMineralWater }],
      },
      {
        img: null,
        video: null,
        description:
          'Когда мясо замаринуется, удалите лишний лук. Нанизывайте курицу на шампуры или деревянные шпажки. Обжаривайте на гриле или сковороде-гриль до золотистой корочки со всех сторон.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Готовый шашлык подавайте с рубленой зеленью и свежим лавашом. Блюдо особенно вкусно в горячем виде прямо с огня.',
        ingredients: [{ ...INGREDIENTS.greens }, { ...INGREDIENTS.lavash }],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из куриных грудок в лимонно-медовом маринаде',
      description:
        'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
      keywords: ['шашлык', 'курица', 'грудка', 'маринад', 'лимон', 'мед', 'чеснок', 'гриль'],
      'og:title': 'Шашлык из куриных грудок в лимонно-медовом маринаде',
      'og:description':
        'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kurinyh-grudok',
      'og:image': '/static/recipes/grill/shashlyk-iz-kurinyh-grudok.jpeg',
      twitterTitle: 'Шашлык из куриных грудок в лимонно-медовом маринаде',
      twitterDescription:
        'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kurinyh-grudok.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinyh-grudok',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kurinyh-grudok',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['шашлык', 'курица', 'грудка', 'маринад', 'лимон', 'мед', 'чеснок', 'гриль'],
    categories: [{ name: 'grill' }],
    key: 'shashlyk-iz-kurinyh-grudok',
    name: 'shashlyk-iz-kurinyh-grudok',
    img: '/static/recipes/grill/shashlyk-iz-kurinyh-grudok.jpeg',
    title: 'Шашлык из куриных грудок в лимонно-медовом маринаде',
    description:
      'Нежный и сочный шашлык из куриной грудки с медово-лимонным маринадом. Простой способ приготовления, но результат — мясо с золотистой корочкой и насыщенным вкусом.',
    calories: 320,
    preparation: 180,
    time: 30,
    level: 1,
    rating: 5,
    portions: 6,
    used: [25.5, 15.2, 22.8],
    ingredients: [
      { ...INGREDIENTS.chickenBreastFillet, count: 1 },
      { ...INGREDIENTS.lemon, count: 1 },
      { ...INGREDIENTS.honey, count: 30 },
      { ...INGREDIENTS.garlic, count: 3 },
      { ...INGREDIENTS.oliveOil, count: 30 },
      { ...INGREDIENTS.salt, count: 10 },
      { ...INGREDIENTS.groundBlackPepper, count: 2 },
    ],
    equipments: [
      EQUIPMENTS.knife,
      EQUIPMENTS.cutBoard,
      EQUIPMENTS.bowl,
      EQUIPMENTS.spoon,
      EQUIPMENTS.lid,
      EQUIPMENTS.tongs,
      EQUIPMENTS.grill,
      EQUIPMENTS.skewers,
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Куриную грудку нарежьте кубиками 4–5 см. Посолите, поперчите.',
        ingredients: [
          { ...INGREDIENTS.chickenBreastFillet },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Смешайте сок лимона, мёд, измельчённый чеснок и оливковое масло. Залейте маринадом курицу, перемешайте, накройте и оставьте на 3 часа.',
        ingredients: [
          { ...INGREDIENTS.lemon },
          { ...INGREDIENTS.honey },
          { ...INGREDIENTS.garlic },
          { ...INGREDIENTS.oliveOil },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Нанижите мясо на шпажки и жарьте на гриле 10–12 минут, переворачивая, до румяной корочки.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из курицы в кефирном маринаде — сочный и ароматный',
      description:
        'Идеальный шашлык из курицы: нежный кефирный маринад с чесноком и специями делает мясо удивительно сочным. Секреты правильного маринования и жарки.',
      keywords: [
        'шашлык из курицы',
        'куриный шашлык',
        'кефирный маринад',
        'маринад для шашлыка',
        'шашлык на кефире',
        'сочный шашлык',
        'рецепт шашлыка',
        'шашлык на мангале',
        'летний шашлык',
        'курица на гриле',
        'пряный шашлык',
        'шашлык с чесноком',
        'быстрый маринад',
        'шашлык для пикника',
        'восточный шашлык',
        'шашлык за 2 часа',
        'диетический шашлык',
        'шашлык без уксуса',
        'куриные бедра на гриле',
        'грудка на мангале',
        'шашлык с зеленью',
      ],
      'og:title': 'Шашлык из курицы в кефирном маринаде — сочный и ароматный',
      'og:description':
        'Идеальный шашлык из курицы: нежный кефирный маринад с чесноком и специями делает мясо удивительно сочным.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-kefirnom-marinade',
      'og:image': '/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg',
      twitterTitle: 'Шашлык из курицы в кефирном маринаде — сочный и ароматный',
      twitterDescription:
        'Идеальный шашлык из курицы: нежный кефирный маринад с чесноком и специями делает мясо удивительно сочным.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-kefirnom-marinade',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-kefirnom-marinade',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из курицы', 'кефирный маринад', 'курица на мангале', 'сочный шашлык'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-kuritsy-v-kefirnom-marinade',
    name: 'shashlyk-iz-kuritsy-v-kefirnom-marinade',
    img: '/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg',
    title: 'Шашлык из курицы в кефирном маринаде',
    description:
      'Невероятно сочный шашлык из курицы: кефирный маринад с чесноком и пряностями делает мясо мягким и ароматным. Идеальный вариант для пикника.',
    calories: 210,
    preparation: 20,
    time: 140,
    level: 2,
    rating: 4.8,
    portions: 4,
    used: [25, 12, 3],
    ingredients: [
      {
        name: 'Куриные бедра',
        gauge: 'г',
        count: 800,
        img: null,
      },
      {
        name: 'Кефир',
        gauge: 'мл',
        count: 250,
        img: null,
      },
      {
        name: 'Лук репчатый',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 4,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Паприка сладкая',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Кориандр молотый',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Зира',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Черный перец',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Свежая зелень (кинза/петрушка)',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Мангал или гриль',
        img: null,
      },
      {
        name: 'Шампуры или решетка',
        img: null,
      },
      {
        name: 'Глубокая миска для маринования',
        img: null,
      },
      {
        name: 'Нож шеф-повара',
        img: null,
      },
      {
        name: 'Разделочная доска',
        img: null,
      },
      {
        name: 'Щипцы для гриля',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Подготовьте курицу: бедра промойте, обсушите и нарежьте на куски среднего размера (примерно 4-5 см). Удалите лишний жир и кожу при желании.',
        ingredients: [
          {
            name: 'Куриные бедра',
            gauge: 'г',
            count: 800,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: в глубокой миске смешайте кефир, нарезанный кольцами лук, измельченный чеснок, оливковое масло и все специи. Тщательно перемешайте.',
        ingredients: [
          {
            name: 'Кефир',
            gauge: 'мл',
            count: 250,
            img: null,
          },
          {
            name: 'Лук репчатый',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 4,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Папика сладкая',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Кориандр молотый',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Зира',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Соль',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Черный перец',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Добавьте курицу в маринад, хорошо перемешайте, чтобы все кусочки были покрыты. Накройте пищевой пленкой и уберите в холодильник минимум на 2 часа (лучше на 4-6 часов).',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разожгите мангал. Когда угли покроются белым пеплом, нанижите курицу на шампуры, чередуя с луком из маринада. Жарьте 15-20 минут, регулярно переворачивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Подавайте горячим, посыпав свежей рубленой зеленью. Идеально сочетается с овощами-гриль и лавашом.',
        ingredients: [
          {
            name: 'Свежая зелень (кинза/петрушка)',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из курицы в соевом маринаде — азиатский акцент',
      description:
        'Ароматный шашлык с ярким азиатским характером: соевый соус, свежий имбирь и чеснок создают идеальный баланс вкусов. Советы по приготовлению на углях.',
      keywords: [
        'шашлык из курицы',
        'соевый маринад',
        'имбирный маринад',
        'азиатский шашлык',
        'курица в соевом соусе',
        'шашлык с имбирем',
        'восточный шашлык',
        'быстрый маринад',
        'шашлык за 1 час',
        'куриные крылья на гриле',
        'шашлык с медом',
        'кисло-сладкий шашлык',
        'курица по-азиатски',
        'шашлык для пикника',
        'маринад с кунжутом',
        'диетический шашлык',
        'шашлык без уксуса',
        'куриная грудка на мангале',
        'острый шашлык',
        'шашлык с кунжутом',
        'восточные специи',
      ],
      'og:title': 'Шашлык из курицы в соевом маринаде — азиатский акцент',
      'og:description':
        'Ароматный шашлык с ярким азиатским характером: соевый соус, свежий имбирь и чеснок создают идеальный баланс вкусов.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-soevom-marinade',
      'og:image': '/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg',
      twitterTitle: 'Шашлык из курицы в соевом маринаде — азиатский акцент',
      twitterDescription:
        'Ароматный шашлык с ярким азиатским характером: соевый соус, свежий имбирь и чеснок создают идеальный баланс вкусов.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-soevom-marinade',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-kuritsy-v-soevom-marinade',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из курицы', 'соевый маринад', 'курица с имбирем', 'азиатский шашлык'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-kuritsy-v-soevom-marinade',
    name: 'shashlyk-iz-kuritsy-v-soevom-marinade',
    img: '/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg',
    title: 'Шашлык из курицы в соевом маринаде',
    description:
      'Азиатская версия шашлыка: соевый маринад с имбирем и медом придает курице насыщенный вкус с кисло-сладкими нотками. Быстрое маринование и аппетитная корочка.',
    calories: 230,
    preparation: 15,
    time: 75,
    level: 2,
    rating: 4.7,
    portions: 4,
    used: [27, 10, 5],
    ingredients: [
      {
        name: 'Куриная грудка',
        gauge: 'г',
        count: 800,
        img: null,
      },
      {
        name: 'Соевый соус',
        gauge: 'мл',
        count: 100,
        img: null,
      },
      {
        name: 'Мед',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Свежий имбирь',
        gauge: 'см',
        count: 5,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 3,
        img: null,
      },
      {
        name: 'Кунжутное масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Красный перец хлопьями',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Кунжут',
        gauge: 'ч.л',
        count: 2,
        img: null,
      },
      {
        name: 'Зеленый лук',
        gauge: 'шт',
        count: 3,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Мангал или гриль',
        img: null,
      },
      {
        name: 'Шампуры или решетка',
        img: null,
      },
      {
        name: 'Пластиковый контейнер для маринования',
        img: null,
      },
      {
        name: 'Терка для имбиря',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
      {
        name: 'Кулинарная кисть',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Куриную грудку промойте, обсушите и нарежьте на кубики примерно 4х4 см. Удалите все пленки и лишний жир.',
        ingredients: [
          {
            name: 'Куриная грудка',
            gauge: 'г',
            count: 800,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: в миске смешайте соевый соус, мед, натертый имбирь, измельченный чеснок, кунжутное масло, лимонный сок и красный перец. Взбейте венчиком до однородности.',
        ingredients: [
          {
            name: 'Соевый соус',
            gauge: 'мл',
            count: 100,
            img: null,
          },
          {
            name: 'Мед',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Свежий имбирь',
            gauge: 'см',
            count: 5,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 3,
            img: null,
          },
          {
            name: 'Кунжутное масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Красный перец хлопьями',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Залейте курицу маринадом, перемешайте, чтобы все кусочки были покрыты. Оставьте мариноваться при комнатной температуре 30 минут, затем уберите в холодильник еще на 30 минут.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разожгите мангал. Нанижите курицу на шампуры. Жарьте 10-12 минут, часто переворачивая и смазывая остатками маринада с помощью кисточки в последние 2 минуты.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Готовый шашлык посыпьте кунжутом и нарезанным зеленым луком. Подавайте сразу же, пока горячий.',
        ingredients: [
          {
            name: 'Кунжут',
            gauge: 'ч.л',
            count: 2,
            img: null,
          },
          {
            name: 'Зеленый лук',
            gauge: 'шт',
            count: 3,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из свинины в гранатовом соусе — кавказская классика',
      description:
        'Сочный шашлык из свиной шеи в кисло-сладком гранатовом маринаде. Секреты кавказских мастеров: правильный выбор мяса и техника жарки.',
      keywords: [
        'шашлык из свинины',
        'гранатовый маринад',
        'кавказский шашлык',
        'свиная шея на мангале',
        'шашлык с гранатовым соусом',
        'маринад для свинины',
        'шашлык по-грузински',
        'шашлык с наршарабом',
        'восточный шашлык',
        'сочный шашлык',
        'рецепт шашлыка',
        'шашлык на углях',
        'мясо на косточке',
        'шашлык для пикника',
        'грузинская кухня',
        'ароматный шашлык',
        'шашлык с гранатом',
        'свинина на гриле',
        'маринад без уксуса',
        'шашлык с аджикой',
      ],
      'og:title': 'Шашлык из свинины в гранатовом соусе — кавказская классика',
      'og:description': 'Сочный шашлык из свиной шеи в кисло-сладком гранатовом маринаде. Секреты кавказских мастеров.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-svininy-v-granatovom-souse',
      'og:image': '/static/recipes/grill/shashlyk-iz-svininy-v-granatovom-souse.jpeg',
      twitterTitle: 'Шашлык из свинины в гранатовом соусе — кавказская классика',
      twitterDescription: 'Сочный шашлык из свиной шеи в кисло-сладком гранатовом маринаде.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-svininy-v-granatovom-souse.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-svininy-v-granatovom-souse',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-svininy-v-granatovom-souse',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из свинины', 'гранатовый маринад', 'кавказский шашлык', 'свиная шея на мангале'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-svininy-v-granatovom-souse',
    name: 'shashlyk-iz-svininy-v-granatovom-souse',
    img: '/static/recipes/grill/shashlyk-iz-svininy-v-granatovom-souse.jpeg',
    title: 'Шашлык из свинины в гранатовом соусе',
    description:
      'Кавказский вариант шашлыка: свиная шея в гранатовом маринаде с луком приобретает удивительную сочность и тонкий кисло-сладкий вкус.',
    calories: 310,
    preparation: 25,
    time: 185,
    level: 2,
    rating: 4.9,
    portions: 5,
    used: [22, 25, 8],
    ingredients: [
      {
        name: 'Свиная шея',
        gauge: 'г',
        count: 1000,
        img: null,
      },
      {
        name: 'Гранатовый соус (наршараб)',
        gauge: 'мл',
        count: 100,
        img: null,
      },
      {
        name: 'Лук репчатый',
        gauge: 'шт',
        count: 3,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 5,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Кинза свежая',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
      {
        name: 'Хмели-сунели',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль',
        gauge: 'ч.л',
        count: 1.5,
        img: null,
      },
      {
        name: 'Черный перец',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Мангал',
        img: null,
      },
      {
        name: 'Шампуры',
        img: null,
      },
      {
        name: 'Глубокая миска для маринования',
        img: null,
      },
      {
        name: 'Нож для мяса',
        img: null,
      },
      {
        name: 'Пресс для чеснока',
        img: null,
      },
      {
        name: 'Кулинарные щипцы',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Свиную шею нарежьте кусками по 4-5 см, удаляя лишний жир, но оставляя небольшие прослойки для сочности.',
        ingredients: [
          {
            name: 'Свиная шея',
            gauge: 'г',
            count: 1000,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: смешайте гранатовый соус, нарезанный кольцами лук, измельченный чеснок, оливковое масло, рубленую кинзу, хмели-сунели, соль и перец.',
        ingredients: [
          {
            name: 'Гранатовый соус (наршараб)',
            gauge: 'мл',
            count: 100,
            img: null,
          },
          {
            name: 'Лук репчатый',
            gauge: 'шт',
            count: 3,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 5,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
          {
            name: 'Кинза свежая',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
          {
            name: 'Хмели-сунели',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Соль',
            gauge: 'ч.л',
            count: 1.5,
            img: null,
          },
          {
            name: 'Черный перец',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Залейте мясо маринадом, хорошо перемешайте. Накройте и маринуйте в холодильнике минимум 3 часа (лучше 6-8 часов), периодически перемешивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разожгите мангал. Нанижите мясо на шампуры, чередуя с луком из маринада. Жарьте 15-20 минут, регулярно переворачивая и сбрызгивая соком лимона.',
        ingredients: [
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Подавайте горячим с грузинским лавашом, гранатовыми зернами и зеленью.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из баранины с розмарином — средиземноморский стиль',
      description:
        'Нежный шашлык из молодой баранины: маринад с розмарином, чесноком и лимоном придает мясу изысканный аромат. Правила выбора и подготовки баранины.',
      keywords: [
        'шашлык из баранины',
        'баранина на мангале',
        'маринад с розмарином',
        'средиземноморский шашлык',
        'шашлык по-гречески',
        'молодая баранина',
        'ягненок на гриле',
        'розмарин в маринаде',
        'шашлык с лимоном',
        'ароматный шашлык',
        'рецепт баранины',
        'мясо на косточке',
        'шашлык для праздника',
        'восточный шашлык',
        'сочная баранина',
        'шашлык с травами',
        'баранья нога на мангале',
        'маринад без уксуса',
        'шашлык с оливковым маслом',
        'греческая кухня',
      ],
      'og:title': 'Шашлык из баранины с розмарином — средиземноморский стиль',
      'og:description':
        'Нежный шашлык из молодой баранины: маринад с розмарином, чесноком и лимоном придает мясу изысканный аромат.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-baraniny-s-rozmarinom',
      'og:image': '/static/recipes/grill/shashlyk-iz-baraniny-s-rozmarinom.jpeg',
      twitterTitle: 'Шашлык из баранины с розмарином — средиземноморский стиль',
      twitterDescription:
        'Нежный шашлык из молодой баранины: маринад с розмарином, чесноком и лимоном придает мясу изысканный аромат.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-baraniny-s-rozmarinom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-baraniny-s-rozmarinom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-baraniny-s-rozmarinom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из баранины', 'маринад с розмарином', 'баранина на мангале', 'средиземноморский шашлык'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-baraniny-s-rozmarinom',
    name: 'shashlyk-iz-baraniny-s-rozmarinom',
    img: '/static/recipes/grill/shashlyk-iz-baraniny-s-rozmarinom.jpeg',
    title: 'Шашлык из баранины с розмарином',
    description:
      'Средиземноморская версия шашлыка: молодая баранина в маринаде с розмарином, чесноком и лимоном приобретает нежный вкус и аппетитную корочку.',
    calories: 290,
    preparation: 30,
    time: 150,
    level: 3,
    rating: 4.8,
    portions: 4,
    used: [25, 20, 2],
    ingredients: [
      {
        name: 'Баранина (окорок или корейка)',
        gauge: 'г',
        count: 800,
        img: null,
      },
      {
        name: 'Свежий розмарин',
        gauge: 'веточка',
        count: 4,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 6,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'мл',
        count: 80,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Морская соль',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Черный перец горошком',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Зира',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Болгарский перец',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Красный лук',
        gauge: 'шт',
        count: 2,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Мангал',
        img: null,
      },
      {
        name: 'Деревянные шампуры',
        img: null,
      },
      {
        name: 'Ступка для специй',
        img: null,
      },
      {
        name: 'Нож шеф-повара',
        img: null,
      },
      {
        name: 'Кулинарная кисть',
        img: null,
      },
      {
        name: 'Разделочная доска',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Баранину нарежьте кусками по 4-5 см, удаляя лишние пленки. Для шашлыка лучше использовать мясо с небольшими жировыми прослойками.',
        ingredients: [
          {
            name: 'Баранина (окорок или корейка)',
            gauge: 'г',
            count: 800,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: в ступке растолките 3 зубчика чеснока, розмарин, зиру, перец горошком и морскую соль. Смешайте с оливковым маслом и соком половины лимона.',
        ingredients: [
          {
            name: 'Свежий розмарин',
            gauge: 'веточка',
            count: 4,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 3,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'мл',
            count: 80,
            img: null,
          },
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Морская соль',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Черный перец горошком',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Зира',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Залейте мясо маринадом, добавьте оставшиеся зубчики чеснока (разрезанные пополам). Маринуйте в холодильнике 4-6 часов, периодически перемешивая.',
        ingredients: [
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 3,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Нанижите мясо на шампуры, чередуя с кусочками болгарского перца и красного лука. Жарьте на углях 12-15 минут, часто переворачивая и смазывая оставшимся маринадом.',
        ingredients: [
          {
            name: 'Болгарский перец',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Красный лук',
            gauge: 'шт',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Подавайте с дольками лимона, свежим розмарином и греческим салатом.',
        ingredients: [
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Шашлык из индейки в йогуртовом маринаде — диетический вариант',
      description:
        'Нежный шашлык из филе индейки: йогуртовый маринад с куркумой и чесноком делает мясо сочным и ароматным. Идеально для здорового питания.',
      keywords: [
        'шашлык из индейки',
        'индейка на мангале',
        'йогуртовый маринад',
        'диетический шашлык',
        'шашлык с куркумой',
        'здоровое питание',
        'филе индейки',
        'легкий шашлык',
        'низкокалорийный шашлык',
        'шашлык без жира',
        'рецепт индейки',
        'индейка на гриле',
        'шашлык для ПП',
        'восточный маринад',
        'сочная индейка',
        'шашлык с чесноком',
        'грудка индейки на мангале',
        'маринад без масла',
        'шашлык с лимоном',
        'пп рецепты',
      ],
      'og:title': 'Шашлык из индейки в йогуртовом маринаде — диетический вариант',
      'og:description':
        'Нежный шашлык из филе индейки: йогуртовый маринад с куркумой и чесноком делает мясо сочным и ароматным.',
      'og:url': 'https://povreshka.ru/recipe/shashlyk-iz-indeyki-v-yogurtovom-marinade',
      'og:image': '/static/recipes/grill/shashlyk-iz-indeyki-v-yogurtovom-marinade.jpeg',
      twitterTitle: 'Шашлык из индейки в йогуртовом маринаде — диетический вариант',
      twitterDescription:
        'Нежный шашлык из филе индейки: йогуртовый маринад с куркумой и чесноком делает мясо сочным и ароматным.',
      twitterImage: '/static/recipes/grill/shashlyk-iz-indeyki-v-yogurtovom-marinade.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/shashlyk-iz-indeyki-v-yogurtovom-marinade',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/shashlyk-iz-indeyki-v-yogurtovom-marinade',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['шашлык из индейки', 'йогуртовый маринад', 'диетический шашлык', 'индейка на гриле'],
    categories: [{ name: 'meat' }],
    key: 'shashlyk-iz-indeyki-v-yogurtovom-marinade',
    name: 'shashlyk-iz-indeyki-v-yogurtovom-marinade',
    img: '/static/recipes/grill/shashlyk-iz-indeyki-v-yogurtovom-marinade.jpeg',
    title: 'Шашлык из индейки в йогуртовом маринаде',
    description:
      'Диетический вариант шашлыка: филе индейки в йогуртовом маринаде с куркумой и чесноком остается удивительно сочным и нежным при жарке.',
    calories: 180,
    preparation: 20,
    time: 140,
    level: 2,
    rating: 4.6,
    portions: 4,
    used: [28, 8, 2],
    ingredients: [
      {
        name: 'Филе индейки',
        gauge: 'г',
        count: 800,
        img: null,
      },
      {
        name: 'Греческий йогурт',
        gauge: 'мл',
        count: 200,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 4,
        img: null,
      },
      {
        name: 'Куркума',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Молотый кориандр',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Кабачок',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Красный лук',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Свежая мята',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Гриль или мангал',
        img: null,
      },
      {
        name: 'Деревянные шпажки',
        img: null,
      },
      {
        name: 'Миска для маринования',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
      {
        name: 'Кулинарная кисть',
        img: null,
      },
      {
        name: 'Овощечистка',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Филе индейки нарежьте полосками толщиной 2-3 см и длиной 6-7 см. Удалите все пленки и жировые прослойки.',
        ingredients: [
          {
            name: 'Филе индейки',
            gauge: 'г',
            count: 800,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте маринад: смешайте йогурт, измельченный чеснок, куркуму, лимонный сок, оливковое масло, кориандр и соль до однородной массы.',
        ingredients: [
          {
            name: 'Греческий йогурт',
            gauge: 'мл',
            count: 200,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 4,
            img: null,
          },
          {
            name: 'Куркума',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Молотый кориандр',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Соль',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Залейте мясо маринадом, тщательно перемешайте. Накройте и маринуйте в холодильнике 2-3 часа.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Кабачок нарежьте толстыми кружками, лук — крупными дольками. Нанижите мясо на шпажки, чередуя с овощами.',
        ingredients: [
          {
            name: 'Кабачок',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Красный лук',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Жарьте на гриле 8-10 минут, переворачивая и смазывая остатками маринада. Не пересушите — индейка должна оставаться сочной.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Подавайте горячим, украсив листьями свежей мяты. Отлично сочетается с овощным салатом и зерновым хлебом.',
        ingredients: [
          {
            name: 'Свежая мята',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Овощи-гриль с бальзамической глазурью — летний веганский гарнир',
      description:
        'Ассорти из сезонных овощей с карамельной бальзамической глазурью. Секреты идеальной прожарки и подачи.',
      keywords: [
        'овощи гриль',
        'веганский рецепт',
        'бальзамическая глазурь',
        'гарнир на гриле',
        'летние овощи',
        'здоровое питание',
        'веганский шашлык',
        'овощи на мангале',
        'рецепт без мяса',
        'кабачки гриль',
        'баклажаны гриль',
        'перец гриль',
        'пп рецепты',
        'постное блюдо',
        'овощной микс',
        'средиземноморская кухня',
        'гриль без мяса',
        'веганский пикник',
        'диетический гарнир',
        'рататуй на гриле',
      ],
      'og:title': 'Овощи-гриль с бальзамической глазурью — летний веганский гарнир',
      'og:description': 'Ассорти из сезонных овощей с карамельной бальзамической глазурью.',
      'og:url': 'https://povreshka.ru/recipe/ovoschi-gril-s-balzamisceskoy-glazuryu',
      'og:image': '/static/recipes/grill/ovoschi-gril-s-balzamisceskoy-glazuryu.jpeg',
      twitterTitle: 'Овощи-гриль с бальзамической глазурью — летний веганский гарнир',
      twitterDescription: 'Ассорти из сезонных овощей с карамельной бальзамической глазурью.',
      twitterImage: '/static/recipes/grill/ovoschi-gril-s-balzamisceskoy-glazuryu.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/ovoschi-gril-s-balzamisceskoy-glazuryu',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/ovoschi-gril-s-balzamisceskoy-glazuryu',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['овощи гриль', 'веганский рецепт', 'бальзамическая глазурь', 'гарнир на гриле'],
    categories: [{ name: 'vegetarian' }],
    key: 'ovoschi-gril-s-balzamisceskoy-glazuryu',
    name: 'ovoschi-gril-s-balzamisceskoy-glazuryu',
    img: '/static/recipes/grill/ovoschi-gril-s-balzamisceskoy-glazuryu.jpeg',
    title: 'Овощи-гриль с бальзамиком',
    description:
      'Яркое ассорти из сезонных овощей с карамельной бальзамической глазурью. Идеальный летний гарнир или самостоятельное блюдо.',
    calories: 120,
    preparation: 20,
    time: 30,
    level: 1,
    rating: 4.7,
    portions: 4,
    used: [3, 7, 15],
    ingredients: [
      {
        name: 'Кабачок',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Баклажан',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Красный лук',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Болгарский перец',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Помидоры черри',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Бальзамический уксус',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Мед',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 2,
        img: null,
      },
      {
        name: 'Соль морская',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Смесь перцев',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Свежий базилик',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Решетка для гриля',
        img: null,
      },
      {
        name: 'Кулинарная кисть',
        img: null,
      },
      {
        name: 'Миска для смешивания',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
      {
        name: 'Силиконовая лопатка',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Приготовьте глазурь: смешайте бальзамический уксус, мед, 1 ст.л оливкового масла и измельченный чеснок. Доведите до кипения в сотейнике и уварите вдвое.',
        ingredients: [
          {
            name: 'Бальзамический уксус',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Мед',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Овощи нарежьте: кабачки и баклажаны - продольными пластинами 1 см, перец - четвертинками, лук - толстыми кольцами. Черри оставьте целыми.',
        ingredients: [
          {
            name: 'Кабачок',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Баклажан',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Болгарский перец',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Красный лук',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Помидоры черри',
            gauge: 'г',
            count: 200,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Сбрызните овощи оливковым маслом, посолите, поперчите. Жарьте на решетке гриля по 3-4 минуты с каждой стороны до характерных полос.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Соль морская',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Смесь перцев',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Готовые овощи выложите на блюдо, полейте теплой глазурью и украсьте листьями базилика. Подавайте сразу же.',
        ingredients: [
          {
            name: 'Свежий базилик',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Лосось на кедровой доске — изысканный рыбный рецепт',
      description:
        'Нежный лосось, приготовленный на кедровой доске с медово-горчичной глазурью. Техника копчения на гриле.',
      keywords: [
        'лосось на гриле',
        'рыба на кедровой доске',
        'медово-горчичный соус',
        'рецепт лосося',
        'здоровое питание',
        'рыба на гриле',
        'лосось с медом',
        'дачный рецепт',
        'изысканный ужин',
        'скандинавская кухня',
        'гриль с дымком',
        'пп рецепты',
        'омега-3',
        'красная рыба',
        'быстрый ужин',
        'рецепт для гостей',
        'домашнее копчение',
        'лосось стейк',
        'низкоуглеводный рецепт',
        'рыбный пикник',
      ],
      'og:title': 'Лосось на кедровой доске — изысканный рыбный рецепт',
      'og:description': 'Нежный лосось, приготовленный на кедровой доске с медово-горчичной глазурью.',
      'og:url': 'https://povreshka.ru/recipe/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
      'og:image': '/static/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.jpeg',
      twitterTitle: 'Лосось на кедровой доске — изысканный рыбный рецепт',
      twitterDescription: 'Нежный лосось, приготовленный на кедровой доске с медово-горчичной глазурью.',
      twitterImage: '/static/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['лосось на гриле', 'рыба на кедровой доске', 'медово-горчичный соус', 'изысканный рыбный рецепт'],
    categories: [{ name: 'fish' }],
    key: 'losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
    name: 'losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
    img: '/static/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.jpeg',
    title: 'Лосось на кедровой доске',
    description:
      'Стейк лосося с медово-горчичной глазурью, приготовленный на кедровой доске для легкого дымного аромата. Подается с дольками лимона.',
    calories: 280,
    preparation: 15,
    time: 35,
    level: 2,
    rating: 4.9,
    portions: 2,
    used: [25, 18, 5],
    ingredients: [
      {
        name: 'Стейк лосося',
        gauge: 'г',
        count: 400,
        img: null,
      },
      {
        name: 'Кедровая доска',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Дижонская горчица',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Мед',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 1,
        img: null,
      },
      {
        name: 'Укроп свежий',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
      {
        name: 'Морская соль',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Гриль или мангал',
        img: null,
      },
      {
        name: 'Кулинарные щипцы',
        img: null,
      },
      {
        name: 'Кисточка для глазури',
        img: null,
      },
      {
        name: 'Миска для смешивания',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Замочите кедровую доску в воде на 1-2 часа (можно с белым вином). Это предотвратит возгорание.',
        ingredients: [
          {
            name: 'Кедровая доска',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте горчицу, мед, лимонный сок, измельченный чеснок и рубленый укроп для глазури.',
        ingredients: [
          {
            name: 'Дижонская горчица',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Мед',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 1,
            img: null,
          },
          {
            name: 'Укроп свежий',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Лосося промокните салфеткой, сбрызните оливковым маслом, посолите. Намажьте 2/3 глазури.',
        ingredients: [
          {
            name: 'Стейк лосося',
            gauge: 'г',
            count: 400,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Морская соль',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Разогрейте гриль до 180°C. Положите лосося кожей вниз на доску. Готовьте 12-15 минут под крышкой.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'За 2 минуты до готовности намажьте оставшейся глазурью. Подавайте на доске с дольками лимона.',
        ingredients: [
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Креветки на гриле с чесночным маслом — средиземноморский деликатес',
      description:
        'Крупные тигровые креветки с ароматным чесночным маслом и лимоном. Секреты идеальной прожарки на решетке.',
      keywords: [
        'креветки гриль',
        'морепродукты на гриле',
        'чесночное масло',
        'тигровые креветки',
        'средиземноморский рецепт',
        'быстрый ужин',
        'рецепт с креветками',
        'деликатес на гриле',
        'морской коктейль',
        'испанская кухня',
        'чесночные креветки',
        'пп рецепты',
        'омега-3',
        'низкокалорийный ужин',
        'рецепт для гостей',
        'шашлык из креветок',
        'летний рецепт',
        'морепродукты на мангале',
        'быстрая закуска',
        'сочные креветки',
        'рецепт с чесноком',
      ],
      'og:title': 'Креветки на гриле с чесночным маслом — средиземноморский деликатес',
      'og:description': 'Крупные тигровые креветки с ароматным чесночным маслом и лимоном.',
      'og:url': 'https://povreshka.ru/recipe/krevetki-na-grile-s-chesnochnym-maslom',
      'og:image': '/static/recipes/grill/krevetki-na-grile-s-chesnochnym-maslom.jpeg',
      twitterTitle: 'Креветки на гриле с чесночным маслом — средиземноморский деликатес',
      twitterDescription: 'Крупные тигровые креветки с ароматным чесночным маслом и лимоном.',
      twitterImage: '/static/recipes/grill/krevetki-na-grile-s-chesnochnym-maslom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/krevetki-na-grile-s-chesnochnym-maslom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/krevetki-na-grile-s-chesnochnym-maslom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['креветки гриль', 'морепродукты на гриле', 'чесночное масло', 'тигровые креветки'],
    categories: [{ name: 'seafood' }],
    key: 'krevetki-na-grile-s-chesnochnym-maslom',
    name: 'krevetki-na-grile-s-chesnochnym-maslom',
    img: '/static/recipes/grill/krevetki-na-grile-s-chesnochnym-maslom.jpeg',
    title: 'Креветки на гриле',
    description:
      'Крупные тигровые креветки с хрустящей корочкой и чесночным маслом. Готовятся всего 5 минут — идеальная быстрая закуска.',
    calories: 150,
    preparation: 15,
    time: 20,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [20, 8, 2],
    ingredients: [
      {
        name: 'Крупные креветки (тигровые)',
        gauge: 'г',
        count: 400,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 4,
        img: null,
      },
      {
        name: 'Петрушка свежая',
        gauge: 'пучок',
        count: 1,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Красный перец хлопьями',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль морская',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Деревянные шпажки',
        gauge: 'шт',
        count: 8,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Решетка гриль',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
      {
        name: 'Миска для маринования',
        img: null,
      },
      {
        name: 'Чеснокодавилка',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Креветки очистите, оставив хвостики. Сделайте надрез вдоль спинки и удалите кишечную вену.',
        ingredients: [
          {
            name: 'Крупные креветки (тигровые)',
            gauge: 'г',
            count: 400,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Приготовьте чесночное масло: смешайте оливковое масло, измельченный чеснок, рубленую петрушку, цедру половины лимона, красный перец и соль.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 4,
            img: null,
          },
          {
            name: 'Петрушка свежая',
            gauge: 'пучок',
            count: 1,
            img: null,
          },
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Красный перец хлопьями',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Соль морская',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Замаринуйте креветки в чесночном масле на 10 минут. Нанижите на шпажки (по 3-4 штуки).',
        ingredients: [
          {
            name: 'Деревянные шпажки',
            gauge: 'шт',
            count: 8,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Жарьте на раскаленном гриле по 2-3 минуты с каждой стороны до появления румяных полос.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Подавайте с дольками лимона, полив оставшимся чесночным маслом. Идеально сочетается с белым вином.',
        ingredients: [
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Гриль-сэндвич с сыром халуми — хрустящий вегетарианский обед',
      description:
        'Сочный сэндвич с обжаренным сыром халуми, овощами-гриль и песто. Секреты идеальной корочки и сочетания вкусов.',
      keywords: [
        'гриль сэндвич',
        'халуми на гриле',
        'вегетарианский рецепт',
        'сырный сэндвич',
        'рецепт с халуми',
        'овощи гриль',
        'быстрый обед',
        'сэндвич на гриле',
        'средиземноморская кухня',
        'веганский вариант',
        'сыр который жарится',
        'пп рецепты',
        'постный рецепт',
        'летний обед',
        'рецепт для пикника',
        'хрустящий сэндвич',
        'зеленый песто',
        'быстрый перекус',
        'сэндвич без мяса',
        'кипрская кухня',
        'рецепт с песто',
      ],
      'og:title': 'Гриль-сэндвич с сыром халуми — хрустящий вегетарианский обед',
      'og:description': 'Сочный сэндвич с обжаренным сыром халуми, овощами-гриль и песто.',
      'og:url': 'https://povreshka.ru/recipe/gril-sendvich-s-halloumi-i-ovoschami',
      'og:image': '/static/recipes/grill/gril-sendvich-s-halloumi-i-ovoschami.jpeg',
      twitterTitle: 'Гриль-сэндвич с сыром халуми — хрустящий вегетарианский обед',
      twitterDescription: 'Сочный сэндвич с обжаренным сыром халуми, овощами-гриль и песто.',
      twitterImage: '/static/recipes/grill/gril-sendvich-s-halloumi-i-ovoschami.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/gril-sendvich-s-halloumi-i-ovoschami',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/gril-sendvich-s-halloumi-i-ovoschami',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['гриль сэндвич', 'халуми на гриле', 'вегетарианский рецепт', 'сырный сэндвич'],
    categories: [{ name: 'vegetarian' }],
    key: 'gril-sendvich-s-halloumi-i-ovoschami',
    name: 'gril-sendvich-s-halloumi-i-ovoschami',
    img: '/static/recipes/grill/gril-sendvich-s-halloumi-i-ovoschami.jpeg',
    title: 'Сэндвич с халуми',
    description:
      'Хрустящий сэндвич с обжаренным сыром халуми, кабачками-гриль и домашним песто. Вегетарианский вариант с мясным вкусом.',
    calories: 380,
    preparation: 15,
    time: 25,
    level: 2,
    rating: 4.7,
    portions: 2,
    used: [18, 25, 20],
    ingredients: [
      {
        name: 'Хлеб чиабатта',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Сыр халуми',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Кабачок',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Красный лук',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Песто зеленый',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Руккола',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 1,
        img: null,
      },
      {
        name: 'Соль морская',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Пресс для сэндвичей (опционально)',
        img: null,
      },
      {
        name: 'Решетка гриль',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
      {
        name: 'Кисточка для масла',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Кабачок нарежьте вдоль пластинами 0.5 см. Лук - толстыми кольцами. Сбрызните оливковым маслом с лимонным соком и измельченным чесноком.',
        ingredients: [
          {
            name: 'Кабачок',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Красный лук',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Обжарьте овощи на гриле по 2 минуты с каждой стороны до мягкости. Халуми нарежьте пластинами 1 см и жарьте 1-2 минуты до золотистых полос.',
        ingredients: [
          {
            name: 'Сыр халуми',
            gauge: 'г',
            count: 200,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Чиабатту разрежьте пополам и слегка поджарьте на гриле. На нижнюю часть намажьте песто, выложите рукколу, овощи и сыр. Накройте второй половинкой.',
        ingredients: [
          {
            name: 'Хлеб чиабатта',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Песто зеленый',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
          {
            name: 'Руккола',
            gauge: 'г',
            count: 50,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Верните сэндвич на гриль под пресс на 1-2 минуты для хрустящей корочки. Разрежьте пополам и подавайте сразу же.',
        ingredients: [],
      },
    ],
  },
]
