import { EQUIPMENTS } from '../equipments'
import { INGREDIENTS } from '../ingredients'

export const HEALTHY = [
  {
    metaSeo: {
      title: 'Рагу из кабачков в сметане',
      description:
        'Рагу из кабачков в сметане — это легкое и питательное блюдо, которое идеально подходит для летнего обеда или ужина. Кабачки, богатые витаминами и минералами, готовятся в нежном соусе из сметаны, что придает блюду особую кремовую текстуру и вкус. Это рагу можно подавать как самостоятельное блюдо или в качестве гарнира к мясу или рыбе.',
      keywords: ['рагу', 'кабачки', 'сметана', 'сытный ужин', 'ужин', 'легкий ужин'],
      'og:title': 'Рубленые котлеты из куриного филе на сковороде',
      'og:description':
        'Рагу из кабачков в сметане — это легкое и питательное блюдо, которое идеально подходит для летнего обеда или ужина. Кабачки, богатые витаминами и минералами, готовятся в нежном соусе из сметаны, что придает блюду особую кремовую текстуру и вкус. Это рагу можно подавать как самостоятельное блюдо или в качестве гарнира к мясу или рыбе.',
      'og:url': 'https://povreshka.ru/recipe/ragu-iz-kabachkov-v-smetane',
      'og:image': '/static/recipes/healthy/ragu-iz-kabachkov-v-smetane.jpeg',
      twitterTitle: 'Рубленые котлеты из куриного филе на сковороде',
      twitterDescription:
        'Рагу из кабачков в сметане — это легкое и питательное блюдо, которое идеально подходит для летнего обеда или ужина. Кабачки, богатые витаминами и минералами, готовятся в нежном соусе из сметаны, что придает блюду особую кремовую текстуру и вкус. Это рагу можно подавать как самостоятельное блюдо или в качестве гарнира к мясу или рыбе.',
      twitterImage: '/static/recipes/healthy/ragu-iz-kabachkov-v-smetane.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/ragu-iz-kabachkov-v-smetane',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/ragu-iz-kabachkov-v-smetane',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['рагу', 'кабачки', 'сметана', 'сытный ужин', 'ужин', 'легкий ужин'],
    categories: [{ name: 'healthy' }, { name: 'supper' }],
    key: 'ragu-iz-kabachkov-v-smetane',
    name: 'ragu-iz-kabachkov-v-smetane',
    img: '/static/recipes/healthy/ragu-iz-kabachkov-v-smetane.jpeg',
    title: 'Рагу из кабачков в сметане',
    description:
      'Рагу из кабачков в сметане — это легкое и питательное блюдо, которое идеально подходит для летнего обеда или ужина. Кабачки, богатые витаминами и минералами, готовятся в нежном соусе из сметаны, что придает блюду особую кремовую текстуру и вкус. Это рагу можно подавать как самостоятельное блюдо или в качестве гарнира к мясу или рыбе.',
    calories: 365.5,
    preparation: null,
    time: 20,
    level: 1,
    rating: 5,
    portions: 4,
    used: [5.7, 22.7, 34.1],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Тщательно промойте кабачки, удалите кончики с обеих сторон. Молодые кабачки очищать не нужно — кожура у них нежная. Разрежьте вдоль на половинки, затем на четвертинки, после чего нарежьте поперек брусками длиной до 3 см.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Раздавите зубчики чеснока плоской стороной ножа, чтобы легко снять кожицу — она сойдёт сама. Затем мелко нарубите чеснок — он придаст блюду насыщенный аромат.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Промойте свежую петрушку, обсушите бумажными салфетками. Удалите жесткие стебли, а листья мелко нарежьте. Соедините зелень с чесноком и еще раз пройдитесь ножом для более равномерного вкуса.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Помидоры вымойте, удалите плодоножки. Кожицу оставьте — она сохранит форму томатов в рагу. Нарежьте помидоры средними кусочками, чтобы они не развалились при тепловой обработке.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'В глубокой сковороде или сотейнике разогрейте топленое масло. Добавьте кабачки и обжарьте на сильном огне до золотистой корочки — около 4–5 минут. Затем посыпьте мукой, приправьте солью и молотым перцем, готовьте еще минуту.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Добавьте в кабачки сметану, убавьте огонь до среднего и перемешайте. Когда смесь закипит, всыпьте нарезанные помидоры и чесночно-зелёную смесь. Прогрейте 2 минуты, снимите с огня и сразу подавайте сочное овощное рагу на стол.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Овсяноблин — идеальный завтрак для ПП | Рецепт с фото',
      description:
        'Правильный рецепт овсяноблина — вкусный, низкокалорийный завтрак за 10 минут. Секреты идеальной текстуры, 3 варианта начинки и советы по приготовлению в микроволновке или на сковороде.',
      keywords: [
        'овсяноблин',
        'пп завтрак',
        'рецепт овсяноблина',
        'диетические блины',
        'овсянка на завтрак',
        'быстрый завтрак',
        'здоровое питание',
        'низкокалорийные блины',
        'рецепт с овсяными хлопьями',
        'завтрак для похудения',
        'овсяноблин с бананом',
        'белковый овсяноблин',
        'рецепт без муки',
        'вкусный пп рецепт',
        'овсяный блинчик',
      ],
      'og:title': 'Овсяноблин — идеальный завтрак для ПП | Рецепт с фото',
      'og:description':
        'Правильный рецепт овсяноблина — вкусный, низкокалорийный завтрак за 10 минут. Секреты идеальной текстуры, 3 варианта начинки и советы по приготовлению.',
      'og:url': 'https://povreshka.ru/recipe/ovsyanoblin',
      'og:image': '/static/recipes/healthy/ovsyanoblin.jpeg',
      twitterTitle: 'Овсяноблин — идеальный завтрак для ПП | Рецепт с фото',
      twitterDescription:
        'Правильный рецепт овсяноблина — вкусный, низкокалорийный завтрак за 10 минут. Секреты идеальной текстуры, 3 варианта начинки и советы по приготовлению.',
      twitterImage: '/static/recipes/healthy/ovsyanoblin.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/ovsyanoblin',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/ovsyanoblin',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['овсяноблин', 'пп завтрак', 'диетические блины', 'рецепт овсяноблина', 'овсянка на завтрак'],
    categories: [{ name: 'breakfast' }, { name: 'healthy' }],
    key: 'ovsyanoblin',
    name: 'ovsyanoblin',
    img: '/static/recipes/healthy/ovsyanoblin.jpeg',
    title: 'Овсяноблин классический',
    description:
      'Легендарный овсяноблин — золотая середина между блинчиком и омлетом. Идеальный завтрак для тех, кто следит за питанием: без муки, сахара и масла. Готовится за 10 минут, дарит чувство сытости на 3-4 часа и позволяет экспериментировать с начинками. В этом рецепте — базовый вариант с секретом идеальной эластичности!',
    calories: 280,
    preparation: 5,
    time: 10,
    level: 1,
    rating: 4.8,
    portions: 1,
    used: [12.5, 18.3, 5.2],
    ingredients: [
      {
        ...INGREDIENTS.oatmeal,
        count: 30,
      },
      {
        ...INGREDIENTS.eggs,
        count: 1,
      },
      {
        ...INGREDIENTS.milk,
        count: 50,
      },
      {
        ...INGREDIENTS.salt,
      },
      {
        ...INGREDIENTS.bakingPowder,
        count: 5,
      },
    ],
    equipments: [EQUIPMENTS.blender, EQUIPMENTS.pan, EQUIPMENTS.spatula, EQUIPMENTS.bowl],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Измельчите овсяные хлопья в блендере до состояния муки грубого помола. Это ключевой момент — цельнозерновая текстура даст правильную эластичность. Если нет блендера, используйте готовую овсяную муку.',
        ingredients: [
          {
            ...INGREDIENTS.oatmeal,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'В глубокой миске смешайте все ингредиенты: овсяную муку, яйцо, молоко, соль и разрыхлитель. Взбейте венчиком до однородности. Тесто должно напоминать жидкую сметану. Дайте постоять 3 минуты — хлопья впитают влагу.',
        ingredients: [
          {
            ...INGREDIENTS.eggs,
          },
          {
            ...INGREDIENTS.milk,
          },
          {
            ...INGREDIENTS.salt,
          },
          {
            ...INGREDIENTS.bakingPowder,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Разогрейте антипригарную сковороду на среднем огне (без масла!). Вылейте тесто тонким слоем, распределяя по диаметру. Жарьте 2-3 минуты до появления пузырьков.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Аккуратно переверните лопаткой. Держите на огне еще 1-2 минуты. Идеальный овсяноблин — золотистый снаружи, но мягкий внутри. Сразу добавьте начинку или сверните пополам.',
        ingredients: [],
      },
    ],
    tips: [
      'Для белкового варианта: замените 1 яйцо на 2 белка',
      'Лучшие начинки: творог+зелень, банан+орехи, авокадо+лосось',
      'Если блин рвется — добавьте 1/2 ч.л. кукурузного крахмала',
      'В микроволновке: готовьте 2 минуты на 600 Вт',
    ],
  },
  {
    metaSeo: {
      title: 'Киноа-боул с лососем — полезный обед за 20 минут',
      description: 'Сбалансированный боул с киноа, запеченным лососем, авокадо и овощами. Без глютена, богат омега-3.',
      keywords: [
        'киноа боул',
        'рецепт с лососем',
        'пп обед',
        'здоровый рецепт',
        'боул с авокадо',
        'рецепт с киноа',
        'омега-3',
        'белковый обед',
        'низкоуглеводный рецепт',
        'сбалансированное питание',
        'диетический рецепт',
        'быстрый обед',
        'рецепт для похудения',
        'здоровая еда',
        'рецепт с овощами',
        'вкусно и полезно',
        'антиоксиданты',
        'без глютена',
        'протеиновый обед',
        'средиземноморская диета',
      ],
      'og:title': 'Киноа-боул с лососем — полезный обед за 20 минут',
      'og:description':
        'Сбалансированный боул с киноа, запеченным лососем, авокадо и овощами. Без глютена, богат омега-3.',
      'og:url': 'https://povreshka.ru/recipe/kinoa-boul-s-lososem',
      'og:image': '/static/recipes/healthy/kinoa-boul-s-lososem.jpeg',
      twitterTitle: 'Киноа-боул с лососем — полезный обед за 20 минут',
      twitterDescription: 'Сбалансированный боул с киноа, запеченным лососем и овощами. Без глютена, богат омега-3.',
      twitterImage: '/static/recipes/healthy/kinoa-boul-s-lososem.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/kinoa-boul-s-lososem',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/kinoa-boul-s-lososem',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['киноа боул', 'рецепт с лососем', 'пп обед', 'здоровый рецепт'],
    categories: [{ name: 'protein' }, { name: 'gluten-free' }],
    key: 'kinoa-boul-s-lososem',
    name: 'kinoa-boul-s-lososem',
    img: '/static/recipes/healthy/kinoa-boul-s-lososem.jpeg',
    title: 'Киноа-боул с лососем',
    description:
      'Питательный боул с киноа, запеченным лососем, авокадо и сезонными овощами. Идеальный баланс белков и полезных жиров.',
    calories: 420,
    preparation: 15,
    time: 25,
    level: 2,
    rating: 4.8,
    portions: 2,
    used: [15, 12, 10],
    ingredients: [
      {
        name: 'Киноа',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Лосось',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Авокадо',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Огурец',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Помидоры черри',
        gauge: 'шт',
        count: 10,
        img: null,
      },
      {
        name: 'Шпинат',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Духовка',
        img: null,
      },
      {
        name: 'Сковорода-гриль',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Киноа отварите согласно инструкции (15 минут). Лосось посолите, поперчите, сбрызните оливковым маслом и запеките при 180°C 12–15 минут.',
        ingredients: [
          {
            name: 'Киноа',
            gauge: 'г',
            count: 100,
            img: null,
          },
          {
            name: 'Лосось',
            gauge: 'г',
            count: 200,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Авокадо и огурец нарежьте ломтиками. Помидоры разрежьте пополам. Шпинат промойте.',
        ingredients: [
          {
            name: 'Авокадо',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Огурец',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Помидоры черри',
            gauge: 'шт',
            count: 10,
            img: null,
          },
          {
            name: 'Шпинат',
            gauge: 'г',
            count: 50,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Соберите боул: киноа, овощи, лосось. Полейте смесью оливкового масла и лимонного сока.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Добавьте семена чиа или льна для увеличения клетчатки.', 'Для веганской версии замените лосось на тофу.'],
    variations: [
      {
        name: 'С курицей',
        changes: 'Замените лосось на запеченное куриное филе.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Тыквенный суп-пюре с имбирем — витаминный обед',
      description: 'Нежный крем-суп из тыквы с имбирем и кокосовым молоком. Без сливок, подходит для веганов.',
      keywords: [
        'тыквенный суп',
        'суп-пюре',
        'рецепт с имбирем',
        'веганский суп',
        'здоровый обед',
        'низкокалорийный суп',
        'рецепт с кокосовым молоком',
        'иммунитет',
        'осенний суп',
        'диетический суп',
        'пп рецепт',
        'витаминный суп',
        'быстрый суп',
        'суп без сливок',
        'здоровая еда',
        'антиоксиданты',
        'рецепт для похудения',
        'вкусно и полезно',
        'без глютена',
        'детокс-рецепт',
      ],
      'og:title': 'Тыквенный суп-пюре с имбирем — витаминный обед',
      'og:description': 'Нежный крем-суп из тыквы с имбирем и кокосовым молоком. Без сливок, подходит для веганов.',
      'og:url': 'https://povreshka.ru/recipe/tykvennyj-sup-s-imbirem',
      'og:image': '/static/recipes/healthy/tykvennyj-sup-s-imbirem.jpeg',
      twitterTitle: 'Тыквенный суп-пюре с имбирем — витаминный обед',
      twitterDescription: 'Нежный крем-суп из тыквы с имбирем и кокосовым молоком. Без сливок.',
      twitterImage: '/static/recipes/healthy/tykvennyj-sup-s-imbirem.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/tykvennyj-sup-s-imbirem',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/tykvennyj-sup-s-imbirem',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['тыквенный суп', 'суп-пюре', 'рецепт с имбирем', 'веганский суп'],
    categories: [{ name: 'vegan' }, { name: 'soup' }],
    key: 'tykvennyj-sup-s-imbirem',
    name: 'tykvennyj-sup-s-imbirem',
    img: '/static/recipes/healthy/tykvennyj-sup-s-imbirem.jpeg',
    title: 'Тыквенный суп с имбирем',
    description:
      'Ароматный суп-пюре из тыквы с имбирем, чесноком и кокосовым молоком. Без глютена и молочных продуктов.',
    calories: 180,
    preparation: 10,
    time: 30,
    level: 2,
    rating: 4.7,
    portions: 4,
    used: [12, 10, 8],
    ingredients: [
      {
        name: 'Тыква',
        gauge: 'г',
        count: 500,
        img: null,
      },
      {
        name: 'Кокосовое молоко',
        gauge: 'мл',
        count: 200,
        img: null,
      },
      {
        name: 'Имбирь',
        gauge: 'см',
        count: 3,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 2,
        img: null,
      },
      {
        name: 'Лук репчатый',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Куркума',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Кастрюля',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Тыкву очистите и нарежьте кубиками. Лук, чеснок и имбирь обжарьте на оливковом масле 3 минуты.',
        ingredients: [
          {
            name: 'Тыква',
            gauge: 'г',
            count: 500,
            img: null,
          },
          {
            name: 'Лук репчатый',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 2,
            img: null,
          },
          {
            name: 'Имбирь',
            gauge: 'см',
            count: 3,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте тыкву, куркуму, залейте водой (500 мл) и варите 20 минут до мягкости.',
        ingredients: [
          {
            name: 'Куркума',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Измельчите суп блендером, влейте кокосовое молоко, посолите и поперчите. Подавайте с тыквенными семечками.',
        ingredients: [
          {
            name: 'Кокосовое молоко',
            gauge: 'мл',
            count: 200,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для пикантности добавьте щепотку кайенского перца.', 'Храните в холодильнике до 3 дней.'],
    variations: [
      {
        name: 'С яблоком',
        changes: 'Добавьте 1 яблоко для легкой кислинки.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Смузи-боул с чиа и ягодами — полезный завтрак',
      description:
        'Энергетический завтрак с семенами чиа, греческим йогуртом и свежими ягодами. Без сахара, богат клетчаткой.',
      keywords: [
        'смузи боул',
        'рецепт с чиа',
        'пп завтрак',
        'здоровый завтрак',
        'боул с ягодами',
        'рецепт с йогуртом',
        'низкокалорийный завтрак',
        'диетический завтрак',
        'веганский вариант',
        'антиоксиданты',
        'рецепт для похудения',
        'быстрый завтрак',
        'омега-3',
        'здоровая еда',
        'рецепт без сахара',
        'детокс-завтрак',
        'вкусно и полезно',
        'летний завтрак',
        'протеиновый завтрак',
        'классический боул',
      ],
      'og:title': 'Смузи-боул с чиа и ягодами — полезный завтрак',
      'og:description':
        'Энергетический завтрак с семенами чиа, греческим йогуртом и свежими ягодами. Без сахара, богат клетчаткой.',
      'og:url': 'https://povreshka.ru/recipe/smuzi-boul-s-chia',
      'og:image': '/static/recipes/healthy/smuzi-boul-s-chia.jpeg',
      twitterTitle: 'Смузи-боул с чиа и ягодами — полезный завтрак',
      twitterDescription: 'Энергетический завтрак с семенами чиа, греческим йогуртом и свежими ягодами.',
      twitterImage: '/static/recipes/healthy/smuzi-boul-s-chia.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/smuzi-boul-s-chia',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/smuzi-boul-s-chia',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['смузи боул', 'рецепт с чиа', 'пп завтрак', 'здоровый завтрак'],
    categories: [{ name: 'breakfast' }, { name: 'vegan' }],
    key: 'smuzi-boul-s-chia',
    name: 'smuzi-boul-s-chia',
    img: '/static/recipes/healthy/smuzi-boul-s-chia.jpeg',
    title: 'Смузи-боул с чиа и ягодами',
    description:
      'Питательный завтрак с пудингом из чиа, греческим йогуртом, свежими ягодами и мёдом. Готовится с вечера!',
    calories: 250,
    preparation: 5,
    time: 240, // + 4 часа настаивания
    level: 1,
    rating: 4.9,
    portions: 1,
    used: [8, 6, 5],
    ingredients: [
      {
        name: 'Семена чиа',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Миндальное молоко',
        gauge: 'мл',
        count: 150,
        img: null,
      },
      {
        name: 'Греческий йогурт',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Клубника',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Черника',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Миндальные хлопья',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Прозрачный стакан или боул',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Смешайте чиа с миндальным молоком и оставьте на 4 часа (или на ночь) до образования пудинга.',
        ingredients: [
          {
            name: 'Семена чиа',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Миндальное молоко',
            gauge: 'мл',
            count: 150,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Выложите слоями: пудинг, йогурт, ягоды. Посыпьте миндальными хлопьями и полейте мёдом.',
        ingredients: [
          {
            name: 'Греческий йогурт',
            gauge: 'г',
            count: 100,
            img: null,
          },
          {
            name: 'Клубника',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Черника',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Мёд',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Миндальные хлопья',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для веганской версии замените йогурт на кокосовый.', 'Добавьте спирулину для суперфуда-эффекта.'],
    variations: [
      {
        name: 'С бананом',
        changes: 'Добавьте ½ банана для сладости.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Фаршированные перцы с киноа и тофу — веганский ужин',
      description: 'Ароматные перцы с начинкой из киноа, тофу и овощей. Без мяса, богаты белком и клетчаткой.',
      keywords: [
        'фаршированные перцы',
        'рецепт с киноа',
        'веганский ужин',
        'здоровый ужин',
        'рецепт с тофу',
        'низкокалорийный ужин',
        'белковый рецепт',
        'диетический ужин',
        'постный рецепт',
        'киноа и овощи',
        'пп рецепт',
        'средиземноморская кухня',
        'вкусно и полезно',
        'рецепт для похудения',
        'здоровая еда',
        'овощной ужин',
        'без глютена',
        'растительный белок',
        'протеиновый ужин',
        'легкий ужин',
      ],
      'og:title': 'Фаршированные перцы с киноа и тофу — веганский ужин',
      'og:description': 'Ароматные перцы с начинкой из киноа, тофу и овощей. Без мяса, богаты белком и клетчаткой.',
      'og:url': 'https://povreshka.ru/recipe/farshirovannye-pertsy-s-kinoa',
      'og:image': '/static/recipes/healthy/farshirovannye-pertsy-s-kinoa.jpeg',
      twitterTitle: 'Фаршированные перцы с киноа и тофу — веганский ужин',
      twitterDescription: 'Ароматные перцы с начинкой из киноа, тофу и овощей. Без мяса.',
      twitterImage: '/static/recipes/healthy/farshirovannye-pertsy-s-kinoa.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/farshirovannye-pertsy-s-kinoa',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/farshirovannye-pertsy-s-kinoa',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['фаршированные перцы', 'рецепт с киноа', 'веганский ужин', 'здоровый ужин'],
    categories: [{ name: 'vegan' }, { name: 'protein' }],
    key: 'farshirovannye-pertsy-s-kinoa',
    name: 'farshirovannye-pertsy-s-kinoa',
    img: '/static/recipes/healthy/farshirovannye-pertsy-s-kinoa.jpeg',
    title: 'Фаршированные перцы с киноа',
    description: 'Сочные перцы с начинкой из киноа, тофу, томатов и зелени. Запекаются в духовке с пряными травами.',
    calories: 290,
    preparation: 20,
    time: 50,
    level: 2,
    rating: 4.6,
    portions: 4,
    used: [20, 15, 12],
    ingredients: [
      {
        name: 'Болгарские перцы',
        gauge: 'шт',
        count: 4,
        img: null,
      },
      {
        name: 'Киноа',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Тофу',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Помидоры',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Лук репчатый',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 2,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Зира',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Духовка',
        img: null,
      },
      {
        name: 'Сковорода',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Киноа отварите согласно инструкции. Тофу нарежьте кубиками и обжарьте с луком и чесноком 5 минут.',
        ingredients: [
          {
            name: 'Киноа',
            gauge: 'г',
            count: 100,
            img: null,
          },
          {
            name: 'Тофу',
            gauge: 'г',
            count: 200,
            img: null,
          },
          {
            name: 'Лук репчатый',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Помидоры нарежьте кубиками, смешайте с киноа, тофу, зирой, солью и перцем.',
        ingredients: [
          {
            name: 'Помидоры',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Зира',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Перцы очистите от семян, наполните начинкой. Запекайте 30 минут при 180°C до мягкости.',
        ingredients: [
          {
            name: 'Болгарские перцы',
            gauge: 'шт',
            count: 4,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для сытности добавьте грибы или нут.', 'Подавайте с соусом песто или тхиной.'],
    variations: [
      {
        name: 'С сыром',
        changes: 'Посыпьте сверху веганским сыром перед запеканием.',
      },
    ],
  },
]
