export const REFRESHING_DRINKS = [
  {
    metaSeo: {
      title: 'Домашний лимонад с мятой и имбирём — витаминный заряд',
      description: 'Освежающий лимонад с натуральными ингредиентами: лимон, мята и имбирь. Без сахара, с мёдом.',
      keywords: [
        'домашний лимонад',
        'рецепт лимонада',
        'напиток с мятой',
        'имбирный лимонад',
        'летний напиток',
        'освежающий напиток',
        'напиток без сахара',
        'витаминный напиток',
        'напиток для похудения',
        'детокс-напиток',
        'напиток с лимоном',
        'здоровый напиток',
        'быстрый напиток',
        'напиток в жару',
        'натуральный лимонад',
        'домашние напитки',
        'напиток с медом',
        'охлаждающий напиток',
        'пп напиток',
        'рецепт для тонуса',
      ],
      'og:title': 'Домашний лимонад с мятой и имбирём — витаминный заряд',
      'og:description': 'Освежающий лимонад с лимоном, мятой и имбирём. Без сахара, с мёдом.',
      'og:url': 'https://povreshka.ru/recipe/limonad-s-myatoj',
      'og:image': '/static/recipes/refreshingDrinks/limonad-s-myatoj.jpeg',
      twitterTitle: 'Домашний лимонад с мятой и имбирём — витаминный заряд',
      twitterDescription: 'Освежающий лимонад с натуральными ингредиентами.',
      twitterImage: '/static/recipes/refreshingDrinks/limonad-s-myatoj.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/limonad-s-myatoj',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/limonad-s-myatoj',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['домашний лимонад', 'напиток с мятой', 'имбирный лимонад', 'освежающий напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'detox' }],
    key: 'limonad-s-myatoj',
    name: 'limonad-s-myatoj',
    img: '/static/recipes/refreshingDrinks/limonad-s-myatoj.jpeg',
    title: 'Лимонад с мятой и имбирём',
    description:
      'Освежающий лимонад с цитрусовой кислинкой, пряным имбирём и мятной свежестью. Без искусственных добавок!',
    calories: 50,
    preparation: 5,
    time: 10,
    level: 1,
    rating: 4.9,
    portions: 4,
    used: [5, 3, 2],
    ingredients: [
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Мята свежая',
        gauge: 'г',
        count: 20,
        img: null,
      },
      {
        name: 'Имбирь (свежий)',
        gauge: 'см',
        count: 3,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Вода (минеральная или фильтрованная)',
        gauge: 'л',
        count: 1,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кувшин',
        img: null,
      },
      {
        name: 'Деревянная ложка',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Из 1 лимона выжмите сок, второй нарежьте кружочками. Имбирь очистите и натрите на тёрке.',
        ingredients: [
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Имбирь (свежий)',
            gauge: 'см',
            count: 3,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В кувшин добавьте лимонный сок, мёд, имбирь и мяту. Залейте водой и перемешайте.',
        ingredients: [
          {
            name: 'Мёд',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Мята свежая',
            gauge: 'г',
            count: 20,
            img: null,
          },
          {
            name: 'Вода (минеральная или фильтрованная)',
            gauge: 'л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте лёд и дольки лимона. Дайте настояться 5 минут и подавайте.',
        ingredients: [
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для большей свежести добавьте огурец.', 'Замените мёд на стевию для диабетического варианта.'],
    variations: [
      {
        name: 'Ягодный',
        changes: 'Добавьте 100 г размятых ягод (клубника, малина).',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Огуречный детокс-напиток — свежесть и лёгкость',
      description: 'Освежающий напиток с огурцом, лаймом и мятой. Выводит токсины, идеален для жарких дней.',
      keywords: [
        'огуречный напиток',
        'детокс-напиток',
        'напиток с лаймом',
        'освежающий напиток',
        'напиток для похудения',
        'напиток без сахара',
        'летний напиток',
        'напиток в жару',
        'здоровый напиток',
        'низкокалорийный напиток',
        'напиток с мятой',
        'водный баланс',
        'напиток с огурцом',
        'пп напиток',
        'вкусно и полезно',
        'быстрый напиток',
        'натуральный напиток',
        'очищающий напиток',
        'тонизирующий напиток',
        'рецепт для тонуса',
      ],
      'og:title': 'Огуречный детокс-напиток — свежесть и лёгкость',
      'og:description': 'Освежающий напиток с огурцом, лаймом и мятой. Выводит токсины, идеален для жарких дней.',
      'og:url': 'https://povreshka.ru/recipe/ogurechnyj-detoks-napitok',
      'og:image': '/static/recipes/refreshingDrinks/ogurechnyj-detoks-napitok.jpeg',
      twitterTitle: 'Огуречный детокс-напиток — свежесть и лёгкость',
      twitterDescription: 'Освежающий напиток с огурцом, лаймом и мятой. Выводит токсины.',
      twitterImage: '/static/recipes/refreshingDrinks/ogurechnyj-detoks-napitok.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/ogurechnyj-detoks-napitok',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/ogurechnyj-detoks-napitok',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['огуречный напиток', 'детокс-напиток', 'напиток с лаймом', 'освежающий напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'detox' }],
    key: 'ogurechnyj-detoks-napitok',
    name: 'ogurechnyj-detoks-napitok',
    img: '/static/recipes/refreshingDrinks/ogurechnyj-detoks-napitok.jpeg',
    title: 'Огуречный детокс-напиток',
    description: 'Лёгкий напиток с огурцом, лаймом и мятой для восстановления водного баланса и очищения организма.',
    calories: 20,
    preparation: 5,
    time: 10,
    level: 1,
    rating: 4.7,
    portions: 2,
    used: [3, 2, 1],
    ingredients: [
      {
        name: 'Огурец',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Лайм',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Мята свежая',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Вода (минеральная)',
        gauge: 'мл',
        count: 500,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Стевия (по желанию)',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Сито',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Огурец нарежьте кружочками. Лайм разрежьте на четвертинки. Мяту промойте.',
        ingredients: [
          {
            name: 'Огурец',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Лайм',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Мята свежая',
            gauge: 'г',
            count: 10,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В блендере измельчите огурец, мяту и сок лайма. Процедите через сито.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте с водой, добавьте лёд. По желанию подсластите стевией.',
        ingredients: [
          {
            name: 'Вода (минеральная)',
            gauge: 'мл',
            count: 500,
            img: null,
          },
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
          {
            name: 'Стевия (по желанию)',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для пикантности добавьте щепотку морской соли.', 'Подавайте с дольками огурца и лайма.'],
    variations: [
      {
        name: 'С имбирём',
        changes: 'Добавьте 1 ч.л. тёртого имбиря.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Ягодный морс без варки — натуральный витаминный напиток',
      description: 'Освежающий морс из свежих или замороженных ягод без термической обработки. Сохраняет все витамины!',
      keywords: [
        'ягодный морс',
        'морс без варки',
        'напиток из ягод',
        'витаминный напиток',
        'освежающий напиток',
        'напиток без сахара',
        'летний напиток',
        'напиток для иммунитета',
        'здоровый напиток',
        'напиток с мёдом',
        'домашний морс',
        'натуральный напиток',
        'быстрый напиток',
        'напиток в жару',
        'пп напиток',
        'вкусно и полезно',
        'напиток из смородины',
        'напиток из малины',
        'охлаждающий напиток',
        'рецепт для детей',
      ],
      'og:title': 'Ягодный морс без варки — натуральный витаминный напиток',
      'og:description':
        'Освежающий морс из свежих или замороженных ягод без термической обработки. Сохраняет все витамины!',
      'og:url': 'https://povreshka.ru/recipe/yagodnyj-mors',
      'og:image': '/static/recipes/refreshingDrinks/yagodnyj-mors.jpeg',
      twitterTitle: 'Ягодный морс без варки — натуральный витаминный напиток',
      twitterDescription: 'Освежающий морс из свежих или замороженных ягод без варки.',
      twitterImage: '/static/recipes/refreshingDrinks/yagodnyj-mors.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/yagodnyj-mors',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/yagodnyj-mors',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['ягодный морс', 'морс без варки', 'напиток из ягод', 'витаминный напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'vitamin' }],
    key: 'yagodnyj-mors',
    name: 'yagodnyj-mors',
    img: '/static/recipes/refreshingDrinks/yagodnyj-mors.jpeg',
    title: 'Ягодный морс без варки',
    description: 'Натуральный морс из любых ягод (смородина, малина, клубника) с мёдом или стевией. Без кипячения!',
    calories: 60,
    preparation: 10,
    time: 30, // + настаивание
    level: 1,
    rating: 4.8,
    portions: 4,
    used: [8, 5, 3],
    ingredients: [
      {
        name: 'Ягоды (смородина/малина/клубника)',
        gauge: 'г',
        count: 300,
        img: null,
      },
      {
        name: 'Вода (фильтрованная)',
        gauge: 'л',
        count: 1,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Марля или сито',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Ягоды разомните вилкой или взбейте блендером. Процедите через марлю, чтобы удалить косточки.',
        ingredients: [
          {
            name: 'Ягоды (смородина/малина/клубника)',
            gauge: 'г',
            count: 300,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте ягодный сок с водой, добавьте мёд и лимонный сок. Перемешайте до растворения мёда.',
        ingredients: [
          {
            name: 'Вода (фильтрованная)',
            gauge: 'л',
            count: 1,
            img: null,
          },
          {
            name: 'Мёд',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте лёд и дайте настояться 20 минут в холодильнике. Подавайте с целыми ягодами.',
        ingredients: [
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: [
      'Замороженные ягоды не размораживайте — так морс будет холоднее.',
      'Для детокса добавьте веточку розмарина.',
    ],
    variations: [
      {
        name: 'С имбирём',
        changes: 'Добавьте 1 ч.л. тёртого имбиря.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Арбузный смузи с мятой — охлаждение в стакане',
      description: 'Лёгкий смузи из арбуза, лайма и мяты. Напиток для жарких дней — без сахара и молочных продуктов.',
      keywords: [
        'арбузный смузи',
        'напиток с арбузом',
        'освежающий смузи',
        'летний напиток',
        'напиток в жару',
        'низкокалорийный напиток',
        'напиток без сахара',
        'веганский напиток',
        'здоровый напиток',
        'напиток с мятой',
        'быстрый напиток',
        'натуральный напиток',
        'охлаждающий напиток',
        'пп напиток',
        'вкусно и полезно',
        'напиток для похудения',
        'напиток с лаймом',
        'детокс-напиток',
        'протеиновый вариант',
        'рецепт для тонуса',
      ],
      'og:title': 'Арбузный смузи с мятой — охлаждение в стакане',
      'og:description': 'Лёгкий смузи из арбуза, лайма и мяты. Напиток для жарких дней — без сахара.',
      'og:url': 'https://povreshka.ru/recipe/arbuznyj-smuzi',
      'og:image': '/static/recipes/refreshingDrinks/arbuznyj-smuzi.jpeg',
      twitterTitle: 'Арбузный смузи с мятой — охлаждение в стакане',
      twitterDescription: 'Лёгкий смузи из арбуза, лайма и мяты. Без сахара и молочных продуктов.',
      twitterImage: '/static/recipes/refreshingDrinks/arbuznyj-smuzi.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/arbuznyj-smuzi',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/arbuznyj-smuzi',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['арбузный смузи', 'напиток с арбузом', 'освежающий смузи', 'летний напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'vegan' }],
    key: 'arbuznyj-smuzi',
    name: 'arbuznyj-smuzi',
    img: '/static/recipes/refreshingDrinks/arbuznyj-smuzi.jpeg',
    title: 'Арбузный смузи с мятой',
    description: 'Нежный смузи из спелого арбуза с мятой и соком лайма. Освежает и восстанавливает водный баланс.',
    calories: 70,
    preparation: 5,
    time: 5,
    level: 1,
    rating: 4.9,
    portions: 2,
    used: [6, 4, 2],
    ingredients: [
      {
        name: 'Арбуз (мякоть)',
        gauge: 'г',
        count: 400,
        img: null,
      },
      {
        name: 'Лайм',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Мята свежая',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Вода (по необходимости)',
        gauge: 'мл',
        count: 50,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Стаканы для подачи',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Арбуз очистите от косточек и нарежьте кубиками. Лайм выжмите.',
        ingredients: [
          {
            name: 'Арбуз (мякоть)',
            gauge: 'г',
            count: 400,
            img: null,
          },
          {
            name: 'Лайм',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В блендере смешайте арбуз, сок лайма, мяту и лёд. Добавьте воды, если слишком густо.',
        ingredients: [
          {
            name: 'Мята свежая',
            gauge: 'г',
            count: 10,
            img: null,
          },
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
          {
            name: 'Вода (по необходимости)',
            gauge: 'мл',
            count: 50,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Разлейте по стаканам, украсьте мятой и долькой лайма.',
        ingredients: [],
      },
    ],
    tips: [
      'Для кремообразности добавьте 50 г кокосового молока.',
      'Подавайте сразу — арбузный сок быстро расслаивается.',
    ],
    variations: [
      {
        name: 'С огурцом',
        changes: 'Добавьте ½ огурца без кожицы.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Мятно-лимонный детокс-напиток с огурцом — очищение и свежесть',
      description: 'Освежающий напиток с мятой, лимоном и огурцом для детокса и восстановления водного баланса.',
      keywords: [
        'детокс-напиток',
        'напиток с огурцом',
        'мятный напиток',
        'лимонный напиток',
        'очищающий напиток',
        'напиток для похудения',
        'освежающий напиток',
        'летний напиток',
        'здоровый напиток',
        'напиток без сахара',
        'напиток в жару',
        'витаминный напиток',
        'домашний лимонад',
        'натуральный напиток',
        'пп напиток',
        'быстрый напиток',
        'напиток для тонуса',
        'низкокалорийный напиток',
        'напиток с мятой и лимоном',
        'рецепт для здоровья',
      ],
      'og:title': 'Мятно-лимонный детокс-напиток с огурцом — очищение и свежесть',
      'og:description': 'Освежающий напиток с мятой, лимоном и огурцом для детокса и восстановления водного баланса.',
      'og:url': 'https://povreshka.ru/recipe/myatno-limonnij-detoks-napitok',
      'og:image': '/static/recipes/refreshingDrinks/myatno-limonnij-detoks-napitok.jpeg',
      twitterTitle: 'Мятно-лимонный детокс-напиток с огурцом — очищение и свежесть',
      twitterDescription: 'Освежающий напиток с мятой, лимоном и огурцом для детокса.',
      twitterImage: '/static/recipes/refreshingDrinks/myatno-limonnij-detoks-napitok.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/myatno-limonnij-detoks-napitok',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/myatno-limonnij-detoks-napitok',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['детокс-напиток', 'напиток с огурцом', 'мятный напиток', 'освежающий напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'detox' }],
    key: 'myatno-limonnij-detoks-napitok',
    name: 'myatno-limonnij-detoks-napitok',
    img: '/static/recipes/refreshingDrinks/myatno-limonnij-detoks-napitok.jpeg',
    title: 'Мятно-лимонный детокс-напиток',
    description: 'Освежающий напиток с мятой, лимоном и огурцом. Идеален для детокса и жарких дней.',
    calories: 15,
    preparation: 5,
    time: 10,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [3, 2, 1],
    ingredients: [
      {
        name: 'Огурец',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Мята свежая',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Вода (минеральная)',
        gauge: 'мл',
        count: 500,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Стевия (по желанию)',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кувшин',
        img: null,
      },
      {
        name: 'Деревянная ложка',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Огурец нарежьте тонкими кружочками. Лимон нарежьте дольками. Мяту промойте.',
        ingredients: [
          {
            name: 'Огурец',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Мята свежая',
            gauge: 'г',
            count: 10,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В кувшин добавьте огурец, лимон, мяту и залейте водой. Дайте настояться 5 минут.',
        ingredients: [
          {
            name: 'Вода (минеральная)',
            gauge: 'мл',
            count: 500,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте лёд и по желанию стевию. Подавайте охлаждённым.',
        ingredients: [
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
          {
            name: 'Стевия (по желанию)',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для усиления детокс-эффекта добавьте 1 ч.л. тёртого имбиря.', 'Подавайте с соломинкой и долькой лимона.'],
    variations: [
      {
        name: 'С лаймом',
        changes: 'Замените лимон на лайм для более яркого вкуса.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Имбирный лимонад с мёдом — согревающий и освежающий',
      description: 'Полезный лимонад с имбирём, мёдом и лимоном. Идеален для иммунитета и освежения в жару.',
      keywords: [
        'имбирный лимонад',
        'напиток с имбирём',
        'лимонный напиток',
        'напиток с мёдом',
        'освежающий напиток',
        'напиток для иммунитета',
        'зимний напиток',
        'летний напиток',
        'здоровый напиток',
        'натуральный лимонад',
        'домашний лимонад',
        'пп напиток',
        'напиток без сахара',
        'тонизирующий напиток',
        'вкусно и полезно',
        'быстрый напиток',
        'напиток в жару',
        'напиток для тонуса',
        'антипростудный напиток',
        'рецепт для здоровья',
      ],
      'og:title': 'Имбирный лимонад с мёдом — согревающий и освежающий',
      'og:description': 'Полезный лимонад с имбирём, мёдом и лимоном. Идеален для иммунитета и освежения в жару.',
      'og:url': 'https://povreshka.ru/recipe/imbirnyj-limonad-s-medom',
      'og:image': '/static/recipes/refreshingDrinks/imbirnyj-limonad-s-medom.jpeg',
      twitterTitle: 'Имбирный лимонад с мёдом — согревающий и освежающий',
      twitterDescription: 'Полезный лимонад с имбирём, мёдом и лимоном для иммунитета.',
      twitterImage: '/static/recipes/refreshingDrinks/imbirnyj-limonad-s-medom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/imbirnyj-limonad-s-medom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/imbirnyj-limonad-s-medom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['имбирный лимонад', 'напиток с имбирём', 'лимонный напиток', 'освежающий напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'immunity' }],
    key: 'imbirnyj-limonad-s-medom',
    name: 'imbirnyj-limonad-s-medom',
    img: '/static/recipes/refreshingDrinks/imbirnyj-limonad-s-medom.jpeg',
    title: 'Имбирный лимонад с мёдом',
    description: 'Ароматный лимонад с имбирём, мёдом и лимоном. Освежает в жару и укрепляет иммунитет.',
    calories: 80,
    preparation: 10,
    time: 20,
    level: 1,
    rating: 4.7,
    portions: 4,
    used: [5, 3, 2],
    ingredients: [
      {
        name: 'Имбирь (свежий)',
        gauge: 'см',
        count: 5,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Вода (кипячёная)',
        gauge: 'л',
        count: 1,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Мята (по желанию)',
        gauge: 'г',
        count: 5,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кастрюля',
        img: null,
      },
      {
        name: 'Кувшин',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Имбирь очистите и нарежьте тонкими ломтиками. Лимон выжмите, оставив несколько долек для украшения.',
        ingredients: [
          {
            name: 'Имбирь (свежий)',
            gauge: 'см',
            count: 5,
            img: null,
          },
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'В кастрюле доведите воду до кипения, добавьте имбирь и варите 5 минут. Остудите до комнатной температуры.',
        ingredients: [
          {
            name: 'Вода (кипячёная)',
            gauge: 'л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Процедите отвар, добавьте лимонный сок и мёд. Перемешайте до растворения мёда. Подавайте со льдом и мятой.',
        ingredients: [
          {
            name: 'Мёд',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
          {
            name: 'Мята (по желанию)',
            gauge: 'г',
            count: 5,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для пряного вкуса добавьте 1 звёздочку бадьяна.', 'Храните в холодильнике до 3 дней.'],
    variations: [
      {
        name: 'С апельсином',
        changes: 'Замените 1 лимон на апельсин для сладости.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Клубнично-базиликовый лимонад — летний освежающий напиток',
      description: 'Нежный лимонад с клубникой, базиликом и лимоном. Без сахара, с натуральной сладостью ягод.',
      keywords: [
        'клубничный лимонад',
        'напиток с клубникой',
        'базиликовый напиток',
        'освежающий напиток',
        'летний напиток',
        'напиток без сахара',
        'здоровый напиток',
        'натуральный лимонад',
        'домашний лимонад',
        'пп напиток',
        'вкусно и полезно',
        'быстрый напиток',
        'напиток в жару',
        'ягодный напиток',
        'напиток с базиликом',
        'охлаждающий напиток',
        'рецепт для тонуса',
        'низкокалорийный напиток',
        'витаминный напиток',
        'рецепт для здоровья',
      ],
      'og:title': 'Клубнично-базиликовый лимонад — летний освежающий напиток',
      'og:description': 'Нежный лимонад с клубникой, базиликом и лимоном. Без сахара, с натуральной сладостью ягод.',
      'og:url': 'https://povreshka.ru/recipe/klubnichno-bazilikovyj-limonad',
      'og:image': '/static/recipes/refreshingDrinks/klubnichno-bazilikovyj-limonad.jpeg',
      twitterTitle: 'Клубнично-базиликовый лимонад — летний освежающий напиток',
      twitterDescription: 'Нежный лимонад с клубникой, базиликом и лимоном. Без сахара.',
      twitterImage: '/static/recipes/refreshingDrinks/klubnichno-bazilikovyj-limonad.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/klubnichno-bazilikovyj-limonad',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/klubnichno-bazilikovyj-limonad',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['клубничный лимонад', 'напиток с клубникой', 'базиликовый напиток', 'освежающий напиток'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'summer' }],
    key: 'klubnichno-bazilikovyj-limonad',
    name: 'klubnichno-bazilikovyj-limonad',
    img: '/static/recipes/refreshingDrinks/klubnichno-bazilikovyj-limonad.jpeg',
    title: 'Клубнично-базиликовый лимонад',
    description: 'Ароматный лимонад с клубникой, свежим базиликом и лимоном. Освежает и дарит летнее настроение!',
    calories: 60,
    preparation: 10,
    time: 15,
    level: 1,
    rating: 4.8,
    portions: 4,
    used: [8, 5, 3],
    ingredients: [
      {
        name: 'Клубника',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Базилик свежий',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Лимон',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Вода (газированная или обычная)',
        gauge: 'л',
        count: 1,
        img: null,
      },
      {
        name: 'Мёд или сироп агавы',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Сито',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Клубнику промойте, удалите хвостики. Базилик промойте и отделите листья от стеблей.',
        ingredients: [
          {
            name: 'Клубника',
            gauge: 'г',
            count: 200,
            img: null,
          },
          {
            name: 'Базилик свежий',
            gauge: 'г',
            count: 10,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В блендере измельчите клубнику, базилик и сок лимона. Процедите через сито.',
        ingredients: [
          {
            name: 'Лимон',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте с водой, добавьте мёд и лёд. Перемешайте и подавайте с листочками базилика.',
        ingredients: [
          {
            name: 'Вода (газированная или обычная)',
            gauge: 'л',
            count: 1,
            img: null,
          },
          {
            name: 'Мёд или сироп агавы',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для игристого варианта используйте газированную воду.', 'Замороженная клубника тоже подойдёт.'],
    variations: [
      {
        name: 'С мятой',
        changes: 'Добавьте 5 г мяты для свежести.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Тропический смузи с манго и кокосом — вкус отпуска',
      description: 'Нежный смузи с манго, кокосовым молоком и бананом. Без сахара, с натуральной сладостью фруктов.',
      keywords: [
        'тропический смузи',
        'смузи с манго',
        'кокосовый смузи',
        'освежающий смузи',
        'летний напиток',
        'напиток без сахара',
        'здоровый напиток',
        'натуральный смузи',
        'пп смузи',
        'вкусно и полезно',
        'быстрый напиток',
        'напиток в жару',
        'фруктовый смузи',
        'смузи с бананом',
        'охлаждающий напиток',
        'рецепт для тонуса',
        'низкокалорийный напиток',
        'витаминный напиток',
        'рецепт для здоровья',
        'напиток для настроения',
      ],
      'og:title': 'Тропический смузи с манго и кокосом — вкус отпуска',
      'og:description':
        'Нежный смузи с манго, кокосовым молоком и бананом. Без сахара, с натуральной сладостью фруктов.',
      'og:url': 'https://povreshka.ru/recipe/tropicheskij-smuzi-s-mango',
      'og:image': '/static/recipes/refreshingDrinks/tropicheskij-smuzi-s-mango.jpeg',
      twitterTitle: 'Тропический смузи с манго и кокосом — вкус отпуска',
      twitterDescription: 'Нежный смузи с манго, кокосовым молоком и бананом. Без сахара.',
      twitterImage: '/static/recipes/refreshingDrinks/tropicheskij-smuzi-s-mango.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/tropicheskij-smuzi-s-mango',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/tropicheskij-smuzi-s-mango',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['тропический смузи', 'смузи с манго', 'кокосовый смузи', 'освежающий смузи'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'summer' }],
    key: 'tropicheskij-smuzi-s-mango',
    name: 'tropicheskij-smuzi-s-mango',
    img: '/static/recipes/refreshingDrinks/tropicheskij-smuzi-s-mango.jpeg',
    title: 'Тропический смузи с манго',
    description: 'Сладкий смузи с манго, бананом и кокосовым молоком. Напоминает вкус тропиков!',
    calories: 120,
    preparation: 5,
    time: 5,
    level: 1,
    rating: 4.9,
    portions: 2,
    used: [8, 5, 3],
    ingredients: [
      {
        name: 'Манго (мякоть)',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Банан',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Кокосовое молоко',
        gauge: 'мл',
        count: 200,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Стаканы для подачи',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Манго и банан очистите от кожуры и нарежьте кубиками.',
        ingredients: [
          {
            name: 'Манго (мякоть)',
            gauge: 'г',
            count: 200,
            img: null,
          },
          {
            name: 'Банан',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В блендере смешайте манго, банан, кокосовое молоко, лёд и лимонный сок.',
        ingredients: [
          {
            name: 'Кокосовое молоко',
            gauge: 'мл',
            count: 200,
            img: null,
          },
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Разлейте по стаканам и украсьте долькой манго.',
        ingredients: [],
      },
    ],
    tips: ['Для густоты добавьте 1 ст.л. овсяных хлопьев.', 'Замороженное манго не требует льда.'],
    variations: [
      {
        name: 'С ананасом',
        changes: 'Замените половину манго на ананас.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Огуречно-лаймовый спритцер — идеальный напиток для жаркого дня',
      description:
        'Лёгкий и освежающий спритцер с огурцом, лаймом и газированной водой. Минимум калорий, максимум свежести!',
      keywords: [
        'огуречный напиток',
        'лаймовый спритцер',
        'освежающий напиток',
        'напиток с огурцом',
        'низкокалорийный напиток',
        'летний напиток',
        'напиток в жару',
        'газированный напиток',
        'домашний лимонад',
        'здоровый напиток',
        'напиток без сахара',
        'детокс напиток',
        'быстрый напиток',
        'напиток для похудения',
        'спритцер рецепт',
        'напиток с лаймом',
        'освежающий спритцер',
        'напиток за 5 минут',
        'пп напиток',
        'вкусно и полезно',
      ],
      'og:title': 'Огуречно-лаймовый спритцер — идеальный напиток для жаркого дня',
      'og:description':
        'Лёгкий и освежающий спритцер с огурцом, лаймом и газированной водой. Минимум калорий, максимум свежести!',
      'og:url': 'https://povreshka.ru/recipe/ogurechno-lajmovyj-spritser',
      'og:image': '/static/recipes/refreshingDrinks/ogurechno-lajmovyj-spritser.jpeg',
      twitterTitle: 'Огуречно-лаймовый спритцер — идеальный напиток для жаркого дня',
      twitterDescription: 'Освежающий спритцер с огурцом и лаймом — идеален в жару!',
      twitterImage: '/static/recipes/refreshingDrinks/ogurechno-lajmovyj-spritser.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/ogurechno-lajmovyj-spritser',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/ogurechno-lajmovyj-spritser',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['огуречный напиток', 'лаймовый спритцер', 'освежающий напиток', 'напиток с огурцом'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'low-calorie' }],
    key: 'ogurechno-lajmovyj-spritser',
    name: 'ogurechno-lajmovyj-spritser',
    img: '/static/recipes/refreshingDrinks/ogurechno-lajmovyj-spritser.jpeg',
    title: 'Огуречно-лаймовый спритцер',
    description: 'Невероятно освежающий напиток с тонким вкусом огурца и цитрусовой кислинкой лайма. Идеален в жару!',
    calories: 15,
    preparation: 5,
    time: 5,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [3, 2, 1],
    ingredients: [
      {
        name: 'Огурец',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Лайм',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Газированная вода',
        gauge: 'мл',
        count: 500,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Мята свежая',
        gauge: 'лист',
        count: 5,
        img: null,
      },
      {
        name: 'Стевия (по желанию)',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кувшин',
        img: null,
      },
      {
        name: 'Деревянная ложка',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Огурец нарежьте тонкими кружочками. Лайм разрежьте на дольки.',
        ingredients: [
          {
            name: 'Огурец',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Лайм',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В кувшин положите огурец, лайм и мяту. Добавьте лёд.',
        ingredients: [
          {
            name: 'Мята свежая',
            gauge: 'лист',
            count: 5,
            img: null,
          },
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Залейте газированной водой, аккуратно перемешайте. По желанию добавьте стевию.',
        ingredients: [
          {
            name: 'Газированная вода',
            gauge: 'мл',
            count: 500,
            img: null,
          },
          {
            name: 'Стевия (по желанию)',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для красивого вида используйте прозрачный кувшин.', 'Подавайте сразу — так сохранится максимум пузырьков.'],
    variations: [
      {
        name: 'С имбирём',
        changes: 'Добавьте 1 ч.л. тёртого имбиря для пикантности.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Малиновый чайный фреш с базиликом — ягодное наслаждение',
      description: 'Ароматный холодный чай с малиной, базиликом и лаймом. Натуральный энергетик без кофеина!',
      keywords: [
        'малиновый чай',
        'холодный чай',
        'напиток с малиной',
        'чай с базиликом',
        'освежающий чай',
        'летний напиток',
        'ягодный чай',
        'напиток без сахара',
        'здоровый напиток',
        'домашний чай',
        'напиток с лаймом',
        'фруктовый чай',
        'пп напиток',
        'вкусно и полезно',
        'быстрый напиток',
        'напиток в жару',
        'охлаждающий чай',
        'напиток для тонуса',
        'витаминный напиток',
        'рецепт для здоровья',
      ],
      'og:title': 'Малиновый чайный фреш с базиликом — ягодное наслаждение',
      'og:description': 'Ароматный холодный чай с малиной, базиликом и лаймом. Натуральный энергетик без кофеина!',
      'og:url': 'https://povreshka.ru/recipe/malinovyj-chajnyj-fresh',
      'og:image': '/static/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.jpeg',
      twitterTitle: 'Малиновый чайный фреш с базиликом — ягодное наслаждение',
      twitterDescription: 'Холодный чай с малиной и базиликом — вкусно и полезно!',
      twitterImage: '/static/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/malinovyj-chajnyj-fresh',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/malinovyj-chajnyj-fresh',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['малиновый чай', 'холодный чай', 'напиток с малиной', 'чай с базиликом'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'tea' }],
    key: 'malinovyj-chajnyj-fresh',
    name: 'malinovyj-chajnyj-fresh',
    img: '/static/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.jpeg',
    title: 'Малиновый чайный фреш',
    description: 'Изысканный холодный чай с малиной, свежим базиликом и цитрусовыми нотами лайма. Бодрит без кофеина!',
    calories: 40,
    preparation: 10,
    time: 30,
    level: 1,
    rating: 4.7,
    portions: 2,
    used: [5, 3, 2],
    ingredients: [
      {
        name: 'Малина (свежая или замороженная)',
        gauge: 'г',
        count: 150,
        img: null,
      },
      {
        name: 'Зелёный чай',
        gauge: 'ч.л',
        count: 2,
        img: null,
      },
      {
        name: 'Базилик свежий',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Лайм',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ч.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Чайник',
        img: null,
      },
      {
        name: 'Кувшин',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Заварите зелёный чай 500 мл воды 70°C, дайте настояться 3 минуты, затем охладите.',
        ingredients: [
          {
            name: 'Зелёный чай',
            gauge: 'ч.л',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Малину разомните вилкой, базилик порвите руками. Добавьте в чай вместе с соком лайма и мёдом.',
        ingredients: [
          {
            name: 'Малина (свежая или замороженная)',
            gauge: 'г',
            count: 150,
            img: null,
          },
          {
            name: 'Базилик свежий',
            gauge: 'г',
            count: 10,
            img: null,
          },
          {
            name: 'Лайм',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Мёд',
            gauge: 'ч.л',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте лёд, дайте настояться 15 минут в холодильнике. Процедите перед подачей.',
        ingredients: [
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для насыщенного цвета добавьте больше малины.', 'Подавайте с веточкой базилика для украшения.'],
    variations: [
      {
        name: 'С клубникой',
        changes: 'Замените половину малины на клубнику.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Персиковый холодный латте с куркумой — золотой эликсир',
      description: 'Нежный латте с персиком, куркумой и кокосовым молоком. Без кофеина, с антиоксидантами!',
      keywords: [
        'персиковый латте',
        'холодный латте',
        'напиток с куркумой',
        'золотое молоко',
        'здоровый латте',
        'напиток без кофеина',
        'кокосовый латте',
        'летний напиток',
        'напиток с персиком',
        'антиоксидантный напиток',
        'пп напиток',
        'вкусно и полезно',
        'освежающий латте',
        'напиток в жару',
        'домашний латте',
        'натуральный напиток',
        'напиток для иммунитета',
        'рецепт для здоровья',
        'веганский латте',
        'низкокалорийный напиток',
      ],
      'og:title': 'Персиковый холодный латте с куркумой — золотой эликсир',
      'og:description': 'Нежный латте с персиком, куркумой и кокосовым молоком. Без кофеина, с антиоксидантами!',
      'og:url': 'https://povreshka.ru/recipe/persikovyj-latte',
      'og:image': '/static/recipes/refreshingDrinks/persikovyj-latte.jpeg',
      twitterTitle: 'Персиковый холодный латте с куркумой — золотой эликсир',
      twitterDescription: 'Нежный латте с персиком и куркумой — вкусно и полезно!',
      twitterImage: '/static/recipes/refreshingDrinks/persikovyj-latte.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/persikovyj-latte',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/persikovyj-latte',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['персиковый латте', 'холодный латте', 'напиток с куркумой', 'золотое молоко'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'vegan' }],
    key: 'persikovyj-latte',
    name: 'persikovyj-latte',
    img: '/static/recipes/refreshingDrinks/persikovyj-latte.jpeg',
    title: 'Персиковый холодный латте',
    description: 'Бархатистый напиток с пюре персика, куркумой и кокосовым молоком. Напоминает летнее утро!',
    calories: 90,
    preparation: 10,
    time: 5,
    level: 2,
    rating: 4.9,
    portions: 2,
    used: [8, 5, 3],
    ingredients: [
      {
        name: 'Персики',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Кокосовое молоко',
        gauge: 'мл',
        count: 200,
        img: null,
      },
      {
        name: 'Куркума',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ч.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
      {
        name: 'Корица',
        gauge: 'щепотка',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Стаканы для подачи',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Персики очистите от кожицы, удалите косточки и взбейте в блендере до пюре.',
        ingredients: [
          {
            name: 'Персики',
            gauge: 'шт',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В блендере смешайте персиковое пюре, кокосовое молоко, куркуму и мёд.',
        ingredients: [
          {
            name: 'Кокосовое молоко',
            gauge: 'мл',
            count: 200,
            img: null,
          },
          {
            name: 'Куркума',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Мёд',
            gauge: 'ч.л',
            count: 2,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Наполните стаканы льдом, влейте напиток. Посыпьте корицей.',
        ingredients: [
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
          {
            name: 'Корица',
            gauge: 'щепотка',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для густоты добавьте 1/2 банана.', 'Подавайте с трубочкой и долькой персика.'],
    variations: [
      {
        name: 'С манго',
        changes: 'Замените 1 персик на 100 г манго.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Молочный коктейль с инжиром — восточная нежность',
      description: 'Нежный коктейль с инжиром, миндальным молоком и кардамоном. Без сахара, с натуральной сладостью!',
      keywords: [
        'молочный коктейль',
        'напиток с инжиром',
        'инжирный коктейль',
        'напиток с кардамоном',
        'восточный напиток',
        'здоровый коктейль',
        'напиток без сахара',
        'миндальный коктейль',
        'освежающий напиток',
        'пп коктейль',
        'вкусно и полезно',
        'быстрый напиток',
        'напиток в жару',
        'домашний коктейль',
        'натуральный напиток',
        'веганский коктейль',
        'рецепт для здоровья',
        'низкокалорийный напиток',
        'витаминный напиток',
        'рецепт для настроения',
      ],
      'og:title': 'Молочный коктейль с инжиром — восточная нежность',
      'og:description':
        'Нежный коктейль с инжиром, миндальным молоком и кардамоном. Без сахара, с натуральной сладостью!',
      'og:url': 'https://povreshka.ru/recipe/inzhirnyj-koktejl',
      'og:image': '/static/recipes/refreshingDrinks/inzhirnyj-koktejl.jpeg',
      twitterTitle: 'Молочный коктейль с инжиром — восточная нежность',
      twitterDescription: 'Нежный коктейль с инжиром и кардамоном — вкусно и полезно!',
      twitterImage: '/static/recipes/refreshingDrinks/inzhirnyj-koktejl.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/inzhirnyj-koktejl',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/inzhirnyj-koktejl',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['молочный коктейль', 'напиток с инжиром', 'инжирный коктейль', 'напиток с кардамоном'],
    categories: [{ name: 'refreshingDrinks' }, { name: 'vegan' }],
    key: 'inzhirnyj-koktejl',
    name: 'inzhirnyj-koktejl',
    img: '/static/recipes/refreshingDrinks/inzhirnyj-koktejl.jpeg',
    title: 'Инжирный молочный коктейль',
    description: 'Бархатистый коктейль со сладким инжиром, миндальным молоком и тёплыми нотами кардамона.',
    calories: 120,
    preparation: 10,
    time: 5,
    level: 2,
    rating: 4.8,
    portions: 2,
    used: [8, 5, 3],
    ingredients: [
      {
        name: 'Инжир свежий',
        gauge: 'шт',
        count: 4,
        img: null,
      },
      {
        name: 'Миндальное молоко',
        gauge: 'мл',
        count: 300,
        img: null,
      },
      {
        name: 'Кардамон (молотый)',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Мёд',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лёд',
        gauge: 'стакан',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Блендер',
        img: null,
      },
      {
        name: 'Коктейльные стаканы',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Инжир очистите от кожицы, разрежьте на четвертинки.',
        ingredients: [
          {
            name: 'Инжир свежий',
            gauge: 'шт',
            count: 4,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В блендере смешайте инжир, миндальное молоко, кардамон и мёд до однородности.',
        ingredients: [
          {
            name: 'Миндальное молоко',
            gauge: 'мл',
            count: 300,
            img: null,
          },
          {
            name: 'Кардамон (молотый)',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Мёд',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Наполните стаканы льдом, влейте коктейль. Украсьте долькой инжира.',
        ingredients: [
          {
            name: 'Лёд',
            gauge: 'стакан',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для густоты добавьте 1/2 банана.', 'Подавайте сразу — инжир быстро окисляется.'],
    variations: [
      {
        name: 'С финиками',
        changes: 'Замените мёд на 2 финика.',
      },
    ],
  },
]
