import { EQUIPMENTS } from '../equipments'
import { INGREDIENTS } from '../ingredients'

export const SALADS = [
  {
    metaSeo: {
      title: 'Греческий салат',
      description:
        'Это классика средиземноморской кухни: сочные помидоры, хрустящие огурцы, сладкий болгарский перец, красный лук, маслины и нежный сыр фета. Всё заправляется ароматным оливковым маслом и щепоткой орегано. Лёгкий, освежающий и невероятно вкусный салат, который идеально подходит как к мясным блюдам, так и в качестве самостоятельного приёма пищи.',
      keywords: ['салат', 'лук', 'помидоры', 'огурцы', 'сыр', 'маслины', 'перец', 'оливки'],
      'og:title': 'Греческий салат',
      'og:description':
        'Это классика средиземноморской кухни: сочные помидоры, хрустящие огурцы, сладкий болгарский перец, красный лук, маслины и нежный сыр фета. Всё заправляется ароматным оливковым маслом и щепоткой орегано. Лёгкий, освежающий и невероятно вкусный салат, который идеально подходит как к мясным блюдам, так и в качестве самостоятельного приёма пищи.',
      'og:url': 'https://povreshka.ru/recipe/grecheskij-salat',
      'og:image': '/static/recipes/salads/grecheskij-salat.jpeg',
      twitterTitle: 'Греческий салат',
      twitterDescription:
        'Это классика средиземноморской кухни: сочные помидоры, хрустящие огурцы, сладкий болгарский перец, красный лук, маслины и нежный сыр фета. Всё заправляется ароматным оливковым маслом и щепоткой орегано. Лёгкий, освежающий и невероятно вкусный салат, который идеально подходит как к мясным блюдам, так и в качестве самостоятельного приёма пищи.',
      twitterImage: '/static/recipes/salads/grecheskij-salat.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/grecheskij-salat',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/grecheskij-salat',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['салат', 'лук', 'помидоры', 'огурцы', 'сыр', 'маслины', 'перец', 'оливки'],
    categories: [{ name: 'salads' }, { name: 'salads' }],
    key: 'grecheskij-salat',
    name: 'grecheskij-salat',
    img: '/static/recipes/salads/grecheskij-salat.jpeg',
    title: 'Греческий салат',
    description:
      'Это классика средиземноморской кухни: сочные помидоры, хрустящие огурцы, сладкий болгарский перец, красный лук, маслины и нежный сыр фета. Всё заправляется ароматным оливковым маслом и щепоткой орегано. Лёгкий, освежающий и невероятно вкусный салат, который идеально подходит как к мясным блюдам, так и в качестве самостоятельного приёма пищи.',
    calories: 87.8,
    preparation: 5,
    time: 15,
    level: 1,
    rating: 5,
    portions: 4,
    used: [2.6, 6.4, 3.8],
    ingredients: [
      {
        ...INGREDIENTS.tomato,
        count: 2,
      },
      {
        ...INGREDIENTS.cucumber,
        count: 2,
      },
      {
        ...INGREDIENTS.redOnion,
        count: 0.5,
      },
      {
        ...INGREDIENTS.fetaCheese,
        count: 100,
      },
      {
        ...INGREDIENTS.olives,
        count: 100,
      },
      {
        ...INGREDIENTS.oreganoDry,
        count: 2,
      },
      {
        ...INGREDIENTS.garlic,
        count: 1,
      },
      {
        ...INGREDIENTS.lemonJuice,
        count: 15,
      },
      {
        ...INGREDIENTS.oliveOil,
        count: 30,
      },
      {
        ...INGREDIENTS.salt,
      },
      {
        ...INGREDIENTS.groundBlackPepper,
      },
    ],
    equipments: [EQUIPMENTS.bowl, EQUIPMENTS.knife, EQUIPMENTS.cutBoard],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Огурцы и помидоры нарежьте крупными дольками, чтобы сохранить их сочность. Красный лук нарежьте тонкими кольцами. Переложите всё в глубокую миску.',
        ingredients: [{ ...INGREDIENTS.tomato }, { ...INGREDIENTS.cucumber }, { ...INGREDIENTS.redOnion }],
      },
      {
        img: null,
        video: null,
        description:
          'Чеснок измельчите с помощью пресса. Смешайте с лимонным соком, орегано, солью и перцем. Постепенно влейте оливковое масло, взбивая вилкой до получения однородной заправки.',
        ingredients: [
          { ...INGREDIENTS.garlic },
          { ...INGREDIENTS.lemonJuice },
          { ...INGREDIENTS.oreganoDry },
          { ...INGREDIENTS.salt },
          { ...INGREDIENTS.groundBlackPepper },
          { ...INGREDIENTS.oliveOil },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Залейте овощи получившейся заправкой и аккуратно перемешайте, чтобы не повредить кусочки.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Добавьте в салат маслины, предварительно удалив косточки. Перемешивать не нужно — просто распределите их по поверхности.',
        ingredients: [{ ...INGREDIENTS.olives }],
      },
      {
        img: null,
        video: null,
        description:
          'Выложите сверху крупные кусочки феты. Посыпьте сушёным орегано и слегка сбрызните ещё немного оливковым маслом для аромата.',
        ingredients: [{ ...INGREDIENTS.fetaCheese }, { ...INGREDIENTS.oreganoDry }, { ...INGREDIENTS.oliveOil }],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Классический салат «Цезарь» с курицей — рецепт с хрустящими крутонами',
      description:
        'Нежные листья салата, курица-гриль, пармезан и домашние крутоны. Идеальный салат «Цезарь» по традиционному рецепту.',
      keywords: [
        'салат цезарь',
        'цезарь с курицей',
        'рецепт цезаря',
        'салат с крутонами',
        'курица гриль',
        'классический цезарь',
        'салат с пармезаном',
        'рецепт с соусом цезарь',
        'быстрый салат',
        'пп цезарь',
        'салат с листьями романо',
        'ресторанный салат',
        'сытный салат',
        'обеденный салат',
        'рецепт с анчоусами',
        'домашний цезарь',
        'салат с курицей',
        'вкусный салат',
        'рецепт для ужина',
        'праздничный салат',
      ],
      'og:title': 'Классический салат «Цезарь» с курицей — рецепт с хрустящими крутонами',
      'og:description': 'Нежные листья салата, курица-гриль, пармезан и домашние крутоны.',
      'og:url': 'https://povreshka.ru/recipe/salat-cezar-s-kuritsey',
      'og:image': '/static/recipes/salads/salat-cezar-s-kuritsey.jpeg',
      twitterTitle: 'Классический салат «Цезарь» с курицей — рецепт с хрустящими крутонами',
      twitterDescription: 'Нежные листья салата, курица-гриль, пармезан и домашние крутоны.',
      twitterImage: '/static/recipes/salads/salat-cezar-s-kuritsey.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-cezar-s-kuritsey',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-cezar-s-kuritsey',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат цезарь', 'цезарь с курицей', 'рецепт цезаря', 'салат с крутонами'],
    categories: [{ name: 'meat' }, { name: 'classic' }],
    key: 'salat-cezar-s-kuritsey',
    name: 'salat-cezar-s-kuritsey',
    img: '/static/recipes/salads/salat-cezar-s-kuritsey.jpeg',
    title: 'Салат «Цезарь» с курицей',
    description: 'Классический салат «Цезарь» с курицей-гриль, хрустящими крутонами, пармезаном и соусом.',
    calories: 350,
    preparation: 15,
    time: 25,
    level: 2,
    rating: 4.8,
    portions: 2,
    used: [12, 15, 10],
    ingredients: [
      {
        name: 'Листья романо',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Куриное филе',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Пармезан',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Белый хлеб',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 1,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Соус «Цезарь»',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Сковорода',
        img: null,
      },
      {
        name: 'Духовка',
        img: null,
      },
      {
        name: 'Салатница',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Хлеб нарежьте кубиками, сбрызните оливковым маслом с чесноком и запеките в духовке при 180°C до хрустящей корочки (10 минут).',
        ingredients: [
          {
            name: 'Белый хлеб',
            gauge: 'г',
            count: 100,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 1,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Куриное филе нарежьте полосками, обжарьте на оливковом масле до готовности. Посолите и поперчите.',
        ingredients: [
          {
            name: 'Куриное филе',
            gauge: 'г',
            count: 200,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Листья романо порвите руками, выложите в салатницу. Добавьте курицу, крутоны и тертый пармезан. Полейте соусом.',
        ingredients: [
          {
            name: 'Листья романо',
            gauge: 'г',
            count: 100,
            img: null,
          },
          {
            name: 'Пармезан',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Соус «Цезарь»',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для более насыщенного вкуса добавьте анчоусы в соус.', 'Крутоны можно заменить на чипсы из лаваша.'],
    variations: [
      {
        name: 'С креветками',
        changes: 'Замените курицу на обжаренные креветки.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Салат с авокадо и креветками — легкий и изысканный ужин',
      description:
        'Нежный салат с авокадо, креветками, рукколой и лимонно-медовой заправкой. Быстро, вкусно и полезно.',
      keywords: [
        'салат с авокадо',
        'салат с креветками',
        'легкий ужин',
        'рецепт с морепродуктами',
        'изысканный салат',
        'пп салат',
        'салат с рукколой',
        'быстрый ужин',
        'здоровый салат',
        'рецепт с медом',
        'салат с лимоном',
        'ресторанный салат',
        'сочный салат',
        'салат для гурманов',
        'рецепт для романтического ужина',
        'вкусный салат',
        'салат без майонеза',
        'рецепт с оливковым маслом',
        'летний салат',
        'питательный салат',
      ],
      'og:title': 'Салат с авокадо и креветками — легкий и изысканный ужин',
      'og:description': 'Нежный салат с авокадо, креветками, рукколой и лимонно-медовой заправкой.',
      'og:url': 'https://povreshka.ru/recipe/salat-s-avokado-i-krevetkami',
      'og:image': '/static/recipes/salads/salat-s-avokado-i-krevetkami.jpeg',
      twitterTitle: 'Салат с авокадо и креветками — легкий и изысканный ужин',
      twitterDescription: 'Нежный салат с авокадо, креветками, рукколой и лимонно-медовой заправкой.',
      twitterImage: '/static/recipes/salads/salat-s-avokado-i-krevetkami.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-s-avokado-i-krevetkami',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-s-avokado-i-krevetkami',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат с авокадо', 'салат с креветками', 'легкий ужин', 'рецепт с морепродуктами'],
    categories: [{ name: 'seafood' }, { name: 'light' }],
    key: 'salat-s-avokado-i-krevetkami',
    name: 'salat-s-avokado-i-krevetkami',
    img: '/static/recipes/salads/salat-s-avokado-i-krevetkami.jpeg',
    title: 'Салат с авокадо и креветками',
    description:
      'Легкий и изысканный салат с авокадо, креветками, рукколой и лимонно-медовой заправкой. Идеальный ужин.',
    calories: 320,
    preparation: 10,
    time: 20,
    level: 2,
    rating: 4.7,
    portions: 2,
    used: [10, 12, 8],
    ingredients: [
      {
        name: 'Креветки',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Авокадо',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Руккола',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Помидоры черри',
        gauge: 'шт',
        count: 10,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Мед',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Сковорода',
        img: null,
      },
      {
        name: 'Салатница',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Креветки очистите, обжарьте на оливковом масле с чесноком до розового цвета (2-3 минуты). Посолите и поперчите.',
        ingredients: [
          {
            name: 'Креветки',
            gauge: 'г',
            count: 200,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 1,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Авокадо нарежьте ломтиками, помидоры черри — половинками. Рукколу порвите руками.',
        ingredients: [
          {
            name: 'Авокадо',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Помидоры черри',
            gauge: 'шт',
            count: 10,
            img: null,
          },
          {
            name: 'Руккола',
            gauge: 'г',
            count: 50,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте оливковое масло, лимонный сок, мед, соль и перец. Полейте салат.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Мед',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: [
      'Для пикантности добавьте кунжут или кедровые орехи.',
      'Авокадо лучше резать перед самой подачей, чтобы не потемнело.',
    ],
    variations: [
      {
        name: 'С лососем',
        changes: 'Замените креветки на слабосоленый лосось.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Салат «Капрезе» — итальянская классика с моцареллой и базиликом',
      description: 'Нежный салат с моцареллой, помидорами и свежим базиликом. Простота и вкус итальянской кухни.',
      keywords: [
        'салат капрезе',
        'моцарелла и помидоры',
        'итальянский салат',
        'рецепт с базиликом',
        'легкий салат',
        'летний салат',
        'салат с бальзамиком',
        'быстрый салат',
        'пп салат',
        'рецепт с оливковым маслом',
        'салат для гурманов',
        'вкусный салат',
        'ресторанный салат',
        'салат без мяса',
        'вегетарианский салат',
        'свежий салат',
        'рецепт для ужина',
        'праздничный салат',
        'итальянская кухня',
        'салат с сыром',
      ],
      'og:title': 'Салат «Капрезе» — итальянская классика с моцареллой и базиликом',
      'og:description': 'Нежный салат с моцареллой, помидорами и свежим базиликом.',
      'og:url': 'https://povreshka.ru/recipe/salat-kapreze',
      'og:image': '/static/recipes/salads/salat-kapreze.jpeg',
      twitterTitle: 'Салат «Капрезе» — итальянская классика с моцареллой и базиликом',
      twitterDescription: 'Нежный салат с моцареллой, помидорами и свежим базиликом.',
      twitterImage: '/static/recipes/salads/salat-kapreze.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-kapreze',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-kapreze',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат капрезе', 'моцарелла и помидоры', 'итальянский салат', 'рецепт с базиликом'],
    categories: [{ name: 'vegetarian' }, { name: 'italian' }],
    key: 'salat-kapreze',
    name: 'salat-kapreze',
    img: '/static/recipes/salads/salat-kapreze.jpeg',
    title: 'Салат «Капрезе»',
    description: 'Классический итальянский салат с моцареллой, помидорами, базиликом и бальзамическим соусом.',
    calories: 250,
    preparation: 5,
    time: 10,
    level: 1,
    rating: 4.9,
    portions: 2,
    used: [6, 8, 4],
    ingredients: [
      {
        name: 'Помидоры',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Моцарелла',
        gauge: 'г',
        count: 125,
        img: null,
      },
      {
        name: 'Базилик свежий',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Бальзамический соус',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Нож',
        img: null,
      },
      {
        name: 'Салатница',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Помидоры и моцареллу нарежьте кружочками одинаковой толщины. Выложите на тарелку, чередуя слои.',
        ingredients: [
          {
            name: 'Помидоры',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Моцарелла',
            gauge: 'г',
            count: 125,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Сверху разложите листья базилика. Полейте оливковым маслом и бальзамиком. Посолите и поперчите.',
        ingredients: [
          {
            name: 'Базилик свежий',
            gauge: 'г',
            count: 10,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Бальзамический соус',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для красоты можно свернуть листья базилика в трубочки.', 'Используйте только свежую моцареллу в рассоле.'],
    variations: [
      {
        name: 'С авокадо',
        changes: 'Добавьте ломтики авокадо.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Салат с тунцом и яйцом — сытный белковый обед',
      description:
        'Питательный салат с консервированным тунцом, яйцами, огурцами и легкой горчичной заправкой. Идеален для ПП.',
      keywords: [
        'салат с тунцом',
        'салат с яйцом',
        'белковый салат',
        'пп рецепт',
        'быстрый обед',
        'салат с огурцом',
        'рецепт с консервированным тунцом',
        'легкий салат',
        'сытный салат',
        'диетический салат',
        'салат для похудения',
        'рецепт с горчицей',
        'простой салат',
        'салат без майонеза',
        'здоровый обед',
        'салат с зеленью',
        'рецепт за 10 минут',
        'постный салат',
        'средиземноморский салат',
        'салат с лимоном',
      ],
      'og:title': 'Салат с тунцом и яйцом — сытный белковый обед',
      'og:description': 'Питательный салат с тунцом, яйцами, огурцами и горчичной заправкой. Идеален для ПП.',
      'og:url': 'https://povreshka.ru/recipe/salat-s-tuntsom-i-yaitsom',
      'og:image': '/static/recipes/salads/salat-s-tuntsom-i-yaitsom.jpeg',
      twitterTitle: 'Салат с тунцом и яйцом — сытный белковый обед',
      twitterDescription: 'Питательный салат с тунцом, яйцами, огурцами и горчичной заправкой.',
      twitterImage: '/static/recipes/salads/salat-s-tuntsom-i-yaitsom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-s-tuntsom-i-yaitsom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-s-tuntsom-i-yaitsom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат с тунцом', 'белковый салат', 'пп рецепт', 'салат с яйцом'],
    categories: [{ name: 'protein' }, { name: 'diet' }],
    key: 'salat-s-tuntsom-i-yaitsom',
    name: 'salat-s-tuntsom-i-yaitsom',
    img: '/static/recipes/salads/salat-s-tuntsom-i-yaitsom.jpeg',
    title: 'Салат с тунцом и яйцом',
    description:
      'Сытный салат с консервированным тунцом, вареными яйцами, свежим огурцом и пикантной горчичной заправкой.',
    calories: 290,
    preparation: 10,
    time: 15,
    level: 1,
    rating: 4.6,
    portions: 2,
    used: [8, 10, 5],
    ingredients: [
      {
        name: 'Тунец в собственном соку',
        gauge: 'банка',
        count: 1,
        img: null,
      },
      {
        name: 'Яйца',
        gauge: 'шт',
        count: 3,
        img: null,
      },
      {
        name: 'Огурец',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Зеленый лук',
        gauge: 'г',
        count: 20,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Горчица',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кастрюля для яиц',
        img: null,
      },
      {
        name: 'Нож',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Яйца сварите вкрутую (8–9 минут), остудите и нарежьте кубиками. Огурец нарежьте тонкими полукольцами.',
        ingredients: [
          {
            name: 'Яйца',
            gauge: 'шт',
            count: 3,
            img: null,
          },
          {
            name: 'Огурец',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Тунец разомните вилкой, смешайте с яйцами и огурцом. Добавьте мелко нарезанный зеленый лук.',
        ingredients: [
          {
            name: 'Тунец в собственном соку',
            gauge: 'банка',
            count: 1,
            img: null,
          },
          {
            name: 'Зеленый лук',
            gauge: 'г',
            count: 20,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Смешайте оливковое масло, лимонный сок, горчицу, соль и перец. Полейте салат и аккуратно перемешайте.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Горчица',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
    tips: [
      'Для сытности добавьте отварную киноа или нут.',
      'Можно заменить горчицу на дижонскую для более мягкого вкуса.',
    ],
    variations: [
      {
        name: 'С авокадо',
        changes: 'Добавьте ½ нарезанного авокадо.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Теплый салат с говядиной и рукколой — ресторанный рецепт',
      description: 'Нежное мясо, хрустящие овощи и пармезан с бальзамическим соусом. Идеальный ужин за 20 минут.',
      keywords: [
        'теплый салат',
        'салат с говядиной',
        'рецепт с рукколой',
        'ресторанный салат',
        'быстрый ужин',
        'салат с пармезаном',
        'рецепт с бальзамиком',
        'сытный салат',
        'мясной салат',
        'салат для мужчин',
        'пп салат',
        'рецепт с томатами',
        'итальянский салат',
        'вкусный ужин',
        'салат с грибами',
        'рецепт для гостей',
        'праздничный салат',
        'сочный салат',
        'салат с орехами',
        'здоровый ужин',
      ],
      'og:title': 'Теплый салат с говядиной и рукколой — ресторанный рецепт',
      'og:description': 'Нежное мясо, хрустящие овощи и пармезан с бальзамическим соусом. Идеальный ужин за 20 минут.',
      'og:url': 'https://povreshka.ru/recipe/teplyj-salat-s-govyadinoj',
      'og:image': '/static/recipes/salads/teplyj-salat-s-govyadinoj.jpeg',
      twitterTitle: 'Теплый салат с говядиной и рукколой — ресторанный рецепт',
      twitterDescription: 'Нежное мясо, хрустящие овощи и пармезан с бальзамическим соусом.',
      twitterImage: '/static/recipes/salads/teplyj-salat-s-govyadinoj.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/teplyj-salat-s-govyadinoj',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/teplyj-salat-s-govyadinoj',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['теплый салат', 'салат с говядиной', 'рецепт с рукколой', 'ресторанный салат'],
    categories: [{ name: 'meat' }, { name: 'restaurant' }],
    key: 'teplyj-salat-s-govyadinoj',
    name: 'teplyj-salat-s-govyadinoj',
    img: '/static/recipes/salads/teplyj-salat-s-govyadinoj.jpeg',
    title: 'Теплый салат с говядиной',
    description: 'Ароматный салат с обжаренной говядиной, рукколой, томатами черри и пармезаном. Подается теплым.',
    calories: 380,
    preparation: 15,
    time: 25,
    level: 2,
    rating: 4.8,
    portions: 2,
    used: [15, 12, 10],
    ingredients: [
      {
        name: 'Говядина (вырезка)',
        gauge: 'г',
        count: 250,
        img: null,
      },
      {
        name: 'Руккола',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Помидоры черри',
        gauge: 'шт',
        count: 10,
        img: null,
      },
      {
        name: 'Пармезан',
        gauge: 'г',
        count: 30,
        img: null,
      },
      {
        name: 'Кедровые орехи',
        gauge: 'г',
        count: 20,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Бальзамический соус',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Сковорода-гриль',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Говядину нарежьте тонкими ломтиками, обжарьте на оливковом масле с чесноком 3–4 минуты до medium rare. Посолите и поперчите.',
        ingredients: [
          {
            name: 'Говядина (вырезка)',
            gauge: 'г',
            count: 250,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 1,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'На тарелку выложите рукколу, разрезанные пополам томаты черри и теплую говядину. Посыпьте пармезаном и кедровыми орехами.',
        ingredients: [
          {
            name: 'Руккола',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Помидоры черри',
            gauge: 'шт',
            count: 10,
            img: null,
          },
          {
            name: 'Пармезан',
            gauge: 'г',
            count: 30,
            img: null,
          },
          {
            name: 'Кедровые орехи',
            gauge: 'г',
            count: 20,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Полейте бальзамическим соусом и оливковым маслом. Подавайте сразу.',
        ingredients: [
          {
            name: 'Бальзамический соус',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: [
      'Для medium прожарки готовьте мясо 5–6 минут.',
      'Кедровые орехи можно слегка обжарить для усиления аромата.',
    ],
    variations: [
      {
        name: 'С грибами',
        changes: 'Добавьте обжаренные шампиньоны.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Салат «Нисуаз» с тунцом — французская классика',
      description: 'Легендарный французский салат с тунцом, яйцами, стручковой фасолью и оливками. Элегантно и просто.',
      keywords: [
        'салат нисуаз',
        'рецепт с тунцом',
        'французский салат',
        'салат с фасолью',
        'летний салат',
        'рецепт с оливками',
        'изысканный салат',
        'салат с яйцом',
        'легкий ужин',
        'пп салат',
        'средиземноморская кухня',
        'рецепт с анчоусами',
        'салат для гурманов',
        'быстрый ужин',
        'здоровый салат',
        'рецепт с лимоном',
        'салат с картофелем',
        'ресторанный салат',
        'вкусный салат',
        'классический рецепт',
      ],
      'og:title': 'Салат «Нисуаз» с тунцом — французская классика',
      'og:description': 'Легендарный французский салат с тунцом, яйцами, стручковой фасолью и оливками.',
      'og:url': 'https://povreshka.ru/recipe/salat-nisuaz-s-tuntsom',
      'og:image': '/static/recipes/salads/salat-nisuaz-s-tuntsom.jpeg',
      twitterTitle: 'Салат «Нисуаз» с тунцом — французская классика',
      twitterDescription: 'Легендарный французский салат с тунцом, яйцами, стручковой фасолью и оливками.',
      twitterImage: '/static/recipes/salads/salat-nisuaz-s-tuntsom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-nisuaz-s-tuntsom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-nisuaz-s-tuntsom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат нисуаз', 'французский салат', 'рецепт с тунцом', 'салат с фасолью'],
    categories: [{ name: 'french' }, { name: 'seafood' }],
    key: 'salat-nisuaz-s-tuntsom',
    name: 'salat-nisuaz-s-tuntsom',
    img: '/static/recipes/salads/salat-nisuaz-s-tuntsom.jpeg',
    title: 'Салат «Нисуаз» с тунцом',
    description: 'Классический французский салат с тунцом, отварным картофелем, стручковой фасолью и яйцами пашот.',
    calories: 320,
    preparation: 20,
    time: 30,
    level: 2,
    rating: 4.7,
    portions: 2,
    used: [15, 12, 8],
    ingredients: [
      {
        name: 'Тунец стейк',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Картофель',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Стручковая фасоль',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Яйца',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Помидоры черри',
        gauge: 'шт',
        count: 8,
        img: null,
      },
      {
        name: 'Оливки',
        gauge: 'г',
        count: 30,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Дижонская горчица',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Сковорода-гриль',
        img: null,
      },
      {
        name: 'Кастрюля',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Картофель отварите в подсоленной воде до готовности (15 минут), нарежьте ломтиками. Фасоль бланшируйте 3 минуты.',
        ingredients: [
          {
            name: 'Картофель',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Стручковая фасоль',
            gauge: 'г',
            count: 100,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Тунец обжарьте на гриле по 2 минуты с каждой стороны (для medium rare). Посолите и поперчите.',
        ingredients: [
          {
            name: 'Тунец стейк',
            gauge: 'г',
            count: 200,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Яйца сварите пашот. На тарелку выложите картофель, фасоль, помидоры, оливки и нарезанный тунец. Сверху — яйцо.',
        ingredients: [
          {
            name: 'Яйца',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Помидоры черри',
            gauge: 'шт',
            count: 8,
            img: null,
          },
          {
            name: 'Оливки',
            gauge: 'г',
            count: 30,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте оливковое масло, лимонный сок, горчицу, соль и перец. Полейте салат.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Дижонская горчица',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: [
      'Для аутентичности добавьте анчоусы и каперсы.',
      'Тунец можно заменить на консервированный (в собственном соку).',
    ],
    variations: [
      {
        name: 'Вегетарианский',
        changes: 'Замените тунец на авокадо и тофу.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Салат «Вальдорф» с курицей — классика с орехами и сельдереем',
      description: 'Нежный салат с курицей, яблоками, грецкими орехами и йогуртовой заправкой. Идеален для бранча.',
      keywords: [
        'салат вальдорф',
        'рецепт с курицей',
        'салат с яблоком',
        'салат с орехами',
        'легкий салат',
        'рецепт с сельдереем',
        'пп салат',
        'салат с йогуртом',
        'быстрый обед',
        'классический салат',
        'салат для бранча',
        'вкусный салат',
        'рецепт с виноградом',
        'здоровый салат',
        'салат без майонеза',
        'сытный салат',
        'рецепт для гостей',
        'праздничный салат',
        'осенний салат',
        'американская кухня',
      ],
      'og:title': 'Салат «Вальдорф» с курицей — классика с орехами и сельдереем',
      'og:description': 'Нежный салат с курицей, яблоками, грецкими орехами и йогуртовой заправкой.',
      'og:url': 'https://povreshka.ru/recipe/salat-valdorf-s-kuritsey',
      'og:image': '/static/recipes/salads/salat-valdorf-s-kuritsey.jpeg',
      twitterTitle: 'Салат «Вальдорф» с курицей — классика с орехами и сельдереем',
      twitterDescription: 'Нежный салат с курицей, яблоками, грецкими орехами и йогуртовой заправкой.',
      twitterImage: '/static/recipes/salads/salat-valdorf-s-kuritsey.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-valdorf-s-kuritsey',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-valdorf-s-kuritsey',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат вальдорф', 'рецепт с курицей', 'салат с яблоком', 'салат с орехами'],
    categories: [{ name: 'meat' }, { name: 'classic' }],
    key: 'salat-valdorf-s-kuritsey',
    name: 'salat-valdorf-s-kuritsey',
    img: '/static/recipes/salads/salat-valdorf-s-kuritsey.jpeg',
    title: 'Салат «Вальдорф» с курицей',
    description:
      'Классический салат с отварной курицей, яблоками, сельдереем, грецкими орехами и легкой йогуртовой заправкой.',
    calories: 340,
    preparation: 15,
    time: 25,
    level: 2,
    rating: 4.5,
    portions: 2,
    used: [12, 10, 8],
    ingredients: [
      {
        name: 'Куриное филе',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Яблоко',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Сельдерей (стебли)',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Грецкие орехи',
        gauge: 'г',
        count: 30,
        img: null,
      },
      {
        name: 'Виноград',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Йогурт натуральный',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Горчица',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кастрюля для курицы',
        img: null,
      },
      {
        name: 'Нож',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Куриное филе отварите в подсоленной воде 20 минут, остудите и нарежьте кубиками.',
        ingredients: [
          {
            name: 'Куриное филе',
            gauge: 'г',
            count: 200,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Яблоко и сельдерей нарежьте тонкой соломкой. Виноград разрежьте пополам. Орехи измельчите.',
        ingredients: [
          {
            name: 'Яблоко',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Сельдерей (стебли)',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Виноград',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Грецкие орехи',
            gauge: 'г',
            count: 30,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте йогурт, лимонный сок, горчицу, соль и перец. Заправьте салат и аккуратно перемешайте.',
        ingredients: [
          {
            name: 'Йогурт натуральный',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Горчица',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
    ],
    tips: [
      'Яблоко можно сбрызнуть лимонным соком, чтобы не темнело.',
      'Для сладости добавьте изюм или мед в заправку.',
    ],
    variations: [
      {
        name: 'Вегетарианский',
        changes: 'Замените курицу на авокадо или тофу.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Крабовый салат с кукурузой — легкий и вкусный рецепт',
      description:
        'Нежный салат с крабовыми палочками, кукурузой, яйцами и свежим огурцом. Идеален для праздника и повседневного стола.',
      keywords: [
        'крабовый салат',
        'салат с кукурузой',
        'рецепт с крабовыми палочками',
        'праздничный салат',
        'легкий салат',
        'салат с яйцом',
        'быстрый салат',
        'салат с огурцом',
        'вкусный салат',
        'рецепт с майонезом',
        'салат на новый год',
        'летний салат',
        'пп салат',
        'салат с рисом',
        'простой салат',
        'салат для гостей',
        'детский салат',
        'салат без мяса',
        'быстрый перекус',
        'классический рецепт',
      ],
      'og:title': 'Крабовый салат с кукурузой — легкий и вкусный рецепт',
      'og:description': 'Нежный салат с крабовыми палочками, кукурузой, яйцами и свежим огурцом.',
      'og:url': 'https://povreshka.ru/recipe/krabovyi-salat-s-kukuruzoi',
      'og:image': '/static/recipes/salads/krabovyi-salat-s-kukuruzoi.jpeg',
      twitterTitle: 'Крабовый салат с кукурузой — легкий и вкусный рецепт',
      twitterDescription: 'Нежный салат с крабовыми палочками, кукурузой, яйцами и свежим огурцом.',
      twitterImage: '/static/recipes/salads/krabovyi-salat-s-kukuruzoi.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/krabovyi-salat-s-kukuruzoi',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/krabovyi-salat-s-kukuruzoi',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['крабовый салат', 'салат с кукурузой', 'рецепт с крабовыми палочками', 'праздничный салат'],
    categories: [{ name: 'seafood' }, { name: 'holiday' }],
    key: 'krabovyi-salat-s-kukuruzoi',
    name: 'krabovyi-salat-s-kukuruzoi',
    img: '/static/recipes/salads/krabovyi-salat-s-kukuruzoi.jpeg',
    title: 'Крабовый салат с кукурузой',
    description: 'Классический крабовый салат с нежными крабовыми палочками, кукурузой, яйцами и хрустящим огурцом.',
    calories: 280,
    preparation: 15,
    time: 20,
    level: 1,
    rating: 4.7,
    portions: 4,
    used: [10, 12, 8],
    ingredients: [
      {
        name: 'Крабовые палочки',
        gauge: 'г',
        count: 200,
        img: null,
      },
      {
        name: 'Кукуруза консервированная',
        gauge: 'банка',
        count: 1,
        img: null,
      },
      {
        name: 'Яйца',
        gauge: 'шт',
        count: 4,
        img: null,
      },
      {
        name: 'Огурец свежий',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Майонез',
        gauge: 'ст.л',
        count: 3,
        img: null,
      },
      {
        name: 'Укроп',
        gauge: 'г',
        count: 10,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кастрюля для яиц',
        img: null,
      },
      {
        name: 'Нож',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Яйца отварите вкрутую (8–9 минут), остудите и нарежьте кубиками. Крабовые палочки нарежьте тонкими кружочками.',
        ingredients: [
          {
            name: 'Яйца',
            gauge: 'шт',
            count: 4,
            img: null,
          },
          {
            name: 'Крабовые палочки',
            gauge: 'г',
            count: 200,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Огурец нарежьте мелкими кубиками. Укроп измельчите.',
        ingredients: [
          {
            name: 'Огурец свежий',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Укроп',
            gauge: 'г',
            count: 10,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте все ингредиенты, добавьте кукурузу, майонез, соль и перец. Аккуратно перемешайте.',
        ingredients: [
          {
            name: 'Кукуруза консервированная',
            gauge: 'банка',
            count: 1,
            img: null,
          },
          {
            name: 'Майонез',
            gauge: 'ст.л',
            count: 3,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для легкости замените майонез на греческий йогурт.', 'Добавьте авокадо для кремовой текстуры.'],
    variations: [
      {
        name: 'С рисом',
        changes: 'Добавьте 100 г отварного риса.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Салат «Оливье» классический — рецепт на Новый год',
      description: 'Традиционный салат с колбасой, картофелем, морковью и майонезом. Главное блюдо праздничного стола.',
      keywords: [
        'салат оливье',
        'классический оливье',
        'рецепт на новый год',
        'салат с колбасой',
        'праздничный салат',
        'салат с горошком',
        'вкусный салат',
        'рецепт с майонезом',
        'новогодний салат',
        'зимний салат',
        'салат с картошкой',
        'быстрый салат',
        'салат для гостей',
        'русская кухня',
        'любимый салат',
        'рецепт с огурцом',
        'детский салат',
        'простой салат',
        'сытный салат',
        'классический рецепт',
      ],
      'og:title': 'Салат «Оливье» классический — рецепт на Новый год',
      'og:description':
        'Традиционный салат с колбасой, картофелем, морковью и майонезом. Главное блюдо праздничного стола.',
      'og:url': 'https://povreshka.ru/recipe/salat-olivye-klassicheskii',
      'og:image': '/static/recipes/salads/salat-olivye-klassicheskii.jpeg',
      twitterTitle: 'Салат «Оливье» классический — рецепт на Новый год',
      twitterDescription: 'Традиционный салат с колбасой, картофелем, морковью и майонезом.',
      twitterImage: '/static/recipes/salads/salat-olivye-klassicheskii.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/salat-olivye-klassicheskii',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/salat-olivye-klassicheskii',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['салат оливье', 'классический оливье', 'рецепт на новый год', 'салат с колбасой'],
    categories: [{ name: 'holiday' }, { name: 'russian' }],
    key: 'salat-olivye-klassicheskii',
    name: 'salat-olivye-klassicheskii',
    img: '/static/recipes/salads/salat-olivye-klassicheskii.jpeg',
    title: 'Салат «Оливье» классический',
    description: 'Легендарный салат с вареной колбасой, картофелем, морковью, яйцами и майонезом. Символ Нового года!',
    calories: 350,
    preparation: 30,
    time: 60,
    level: 2,
    rating: 4.9,
    portions: 6,
    used: [20, 15, 12],
    ingredients: [
      {
        name: 'Докторская колбаса',
        gauge: 'г',
        count: 300,
        img: null,
      },
      {
        name: 'Картофель',
        gauge: 'шт',
        count: 4,
        img: null,
      },
      {
        name: 'Морковь',
        gauge: 'шт',
        count: 2,
        img: null,
      },
      {
        name: 'Яйца',
        gauge: 'шт',
        count: 4,
        img: null,
      },
      {
        name: 'Огурцы маринованные',
        gauge: 'шт',
        count: 3,
        img: null,
      },
      {
        name: 'Горошек консервированный',
        gauge: 'банка',
        count: 1,
        img: null,
      },
      {
        name: 'Майонез',
        gauge: 'ст.л',
        count: 5,
        img: null,
      },
      {
        name: 'Зеленый лук',
        gauge: 'г',
        count: 20,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Кастрюля для варки овощей',
        img: null,
      },
      {
        name: 'Нож',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Картофель и морковь отварите в мундире до готовности (25–30 минут). Яйца сварите вкрутую (8–9 минут). Остудите.',
        ingredients: [
          {
            name: 'Картофель',
            gauge: 'шт',
            count: 4,
            img: null,
          },
          {
            name: 'Морковь',
            gauge: 'шт',
            count: 2,
            img: null,
          },
          {
            name: 'Яйца',
            gauge: 'шт',
            count: 4,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Колбасу, картофель, морковь, яйца и огурцы нарежьте мелкими кубиками. Зеленый лук измельчите.',
        ingredients: [
          {
            name: 'Докторская колбаса',
            gauge: 'г',
            count: 300,
            img: null,
          },
          {
            name: 'Огурцы маринованные',
            gauge: 'шт',
            count: 3,
            img: null,
          },
          {
            name: 'Зеленый лук',
            gauge: 'г',
            count: 20,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте все ингредиенты, добавьте горошек, майонез, соль и перец. Аккуратно перемешайте.',
        ingredients: [
          {
            name: 'Горошек консервированный',
            gauge: 'банка',
            count: 1,
            img: null,
          },
          {
            name: 'Майонез',
            gauge: 'ст.л',
            count: 5,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для оригинального вкуса добавьте 1 ч.л. горчицы в майонез.', 'Подавайте охлажденным — так вкуснее!'],
    variations: [
      {
        name: 'Диетический',
        changes: 'Замените колбасу на отварную курицу, майонез — на йогурт.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Летний салат с клубникой и шпинатом — легкий и свежий',
      description: 'Сладкая клубника, нежный шпинат, сыр фета и орехи с медовой заправкой. Идеален для жарких дней.',
      keywords: [
        'летний салат',
        'салат с клубникой',
        'рецепт с шпинатом',
        'легкий салат',
        'салат с фетой',
        'сладкий салат',
        'салат с орехами',
        'пп салат',
        'быстрый салат',
        'здоровый салат',
        'рецепт с медом',
        'освежающий салат',
        'салат для похудения',
        'вегетарианский салат',
        'вкусный салат',
        'салат без мяса',
        'рецепт для пикника',
        'фруктовый салат',
        'сочный салат',
        'ресторанный салат',
      ],
      'og:title': 'Летний салат с клубникой и шпинатом — легкий и свежий',
      'og:description': 'Сладкая клубника, нежный шпинат, сыр фета и орехи с медовой заправкой.',
      'og:url': 'https://povreshka.ru/recipe/letnii-salat-s-klubnikoi',
      'og:image': '/static/recipes/salads/letnii-salat-s-klubnikoi.jpeg',
      twitterTitle: 'Летний салат с клубникой и шпинатом — легкий и свежий',
      twitterDescription: 'Сладкая клубника, нежный шпинат, сыр фета и орехи с медовой заправкой.',
      twitterImage: '/static/recipes/salads/letnii-salat-s-klubnikoi.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/letnii-salat-s-klubnikoi',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/letnii-salat-s-klubnikoi',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['летний салат', 'салат с клубникой', 'рецепт с шпинатом', 'легкий салат'],
    categories: [{ name: 'vegetarian' }, { name: 'summer' }],
    key: 'letnii-salat-s-klubnikoi',
    name: 'letnii-salat-s-klubnikoi',
    img: '/static/recipes/salads/letnii-salat-s-klubnikoi.jpeg',
    title: 'Летний салат с клубникой',
    description: 'Освежающий салат со сладкой клубникой, шпинатом, сыром фета и медово-горчичной заправкой.',
    calories: 220,
    preparation: 10,
    time: 15,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [8, 10, 5],
    ingredients: [
      {
        name: 'Шпинат свежий',
        gauge: 'г',
        count: 100,
        img: null,
      },
      {
        name: 'Клубника',
        gauge: 'г',
        count: 150,
        img: null,
      },
      {
        name: 'Сыр фета',
        gauge: 'г',
        count: 80,
        img: null,
      },
      {
        name: 'Грецкие орехи',
        gauge: 'г',
        count: 30,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Мед',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Горчица дижонская',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Нож',
        img: null,
      },
      {
        name: 'Салатница',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Шпинат промойте и обсушите. Клубнику нарежьте тонкими ломтиками. Сыр фета раскрошите.',
        ingredients: [
          {
            name: 'Шпинат свежий',
            gauge: 'г',
            count: 100,
            img: null,
          },
          {
            name: 'Клубника',
            gauge: 'г',
            count: 150,
            img: null,
          },
          {
            name: 'Сыр фета',
            gauge: 'г',
            count: 80,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Орехи измельчите и слегка обжарьте на сухой сковороде (1–2 минуты).',
        ingredients: [
          {
            name: 'Грецкие орехи',
            gauge: 'г',
            count: 30,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Смешайте оливковое масло, мед, горчицу, лимонный сок, соль и перец. Полейте салат и посыпьте орехами.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Мед',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Горчица дижонская',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Добавьте мяту для свежести.', 'Можно заменить клубнику на персики или манго.'],
    variations: [
      {
        name: 'С курицей',
        changes: 'Добавьте обжаренное куриное филе.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Грузинский салат с фасолью (Лобио) — острое и сытное блюдо',
      description:
        'Пикантный салат с красной фасолью, грецкими орехами, кинзой и чесноком. Вегетарианский вариант грузинской кухни.',
      keywords: [
        'грузинский салат',
        'салат лобио',
        'рецепт с фасолью',
        'вегетарианский салат',
        'салат с орехами',
        'острый салат',
        'рецепт с кинзой',
        'сытный салат',
        'грузинская кухня',
        'салат с чесноком',
        'пп салат',
        'постный салат',
        'вкусный салат',
        'салат без мяса',
        'рецепт для ужина',
        'национальный салат',
        'сочный салат',
        'салат с гранатом',
        'здоровый салат',
        'рецепт с аджикой',
      ],
      'og:title': 'Грузинский салат с фасолью (Лобио) — острое и сытное блюдо',
      'og:description': 'Пикантный салат с красной фасолью, грецкими орехами, кинзой и чесноком.',
      'og:url': 'https://povreshka.ru/recipe/gruzinskii-salat-lobio',
      'og:image': '/static/recipes/salads/gruzinskii-salat-lobio.jpeg',
      twitterTitle: 'Грузинский салат с фасолью (Лобио) — острое и сытное блюдо',
      twitterDescription: 'Пикантный салат с красной фасолью, грецкими орехами, кинзой и чесноком.',
      twitterImage: '/static/recipes/salads/gruzinskii-salat-lobio.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/gruzinskii-salat-lobio',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/gruzinskii-salat-lobio',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['грузинский салат', 'салат лобио', 'рецепт с фасолью', 'вегетарианский салат'],
    categories: [{ name: 'vegetarian' }, { name: 'georgian' }],
    key: 'gruzinskii-salat-lobio',
    name: 'gruzinskii-salat-lobio',
    img: '/static/recipes/salads/gruzinskii-salat-lobio.jpeg',
    title: 'Грузинский салат с фасолью (Лобио)',
    description:
      'Ароматный салат с красной фасолью, грецкими орехами, кинзой, чесноком и гранатом. Подается с лавашом.',
    calories: 310,
    preparation: 15,
    time: 30,
    level: 2,
    rating: 4.6,
    portions: 4,
    used: [15, 10, 8],
    ingredients: [
      {
        name: 'Фасоль красная (отварная)',
        gauge: 'г',
        count: 300,
        img: null,
      },
      {
        name: 'Грецкие орехи',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Кинза',
        gauge: 'г',
        count: 20,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 3,
        img: null,
      },
      {
        name: 'Гранатовые зерна',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Лук красный',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Винный уксус',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Хмели-сунели',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Сковорода для орехов',
        img: null,
      },
      {
        name: 'Ступка для чеснока',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Фасоль отварите до мягкости (или используйте консервированную). Лук нарежьте полукольцами.',
        ingredients: [
          {
            name: 'Фасоль красная (отварная)',
            gauge: 'г',
            count: 300,
            img: null,
          },
          {
            name: 'Лук красный',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Орехи обжарьте и измельчите. Чеснок раздавите в ступке с солью и хмели-сунели.',
        ingredients: [
          {
            name: 'Грецкие орехи',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 3,
            img: null,
          },
          {
            name: 'Хмели-сунели',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Смешайте фасоль, лук, кинзу, орехи и чесночную пасту. Полейте маслом и уксусом. Посыпьте гранатом.',
        ingredients: [
          {
            name: 'Кинза',
            gauge: 'г',
            count: 20,
            img: null,
          },
          {
            name: 'Гранатовые зерна',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Винный уксус',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
        ],
      },
    ],
    tips: ['Для остроты добавьте молотый перец чили.', 'Подавайте с теплым лавашом или кукурузными лепешками.'],
    variations: [
      {
        name: 'С мясом',
        changes: 'Добавьте обжаренную говядину.',
      },
    ],
  },
]
