import { EQUIPMENTS } from '../equipments'
import { INGREDIENTS } from '../ingredients'

export const SNACKS = [
  {
    metaSeo: {
      title: 'Рулетики из ветчины с сыром и чесноком',
      description:
        'Рулетики из ветчины с сырно-чесночной начинкой — отличная идея для закуски на фуршет или праздничный стол. Они эффектно выглядят, получаются сытными и яркими на вкус, а готовятся очень просто. Такой рецепт легко адаптировать под свой вкус — вариантов начинки множество. Мы предлагаем попробовать майонез с добавлением карри — он придаёт рулетикам красивый цвет и оригинальную нотку. А немного мелко нарезанного белого лука добавит пикантности и легкую свежесть. Если времени в обрез, можно ограничиться классикой — натертым сыром, чесноком и обычным майонезом. А если добавить ещё и отварные яйца, измельчённые на мелкой тёрке, начинка получится особенно нежной и в то же время выразительной.',
      keywords: ['рулетики', 'ветчина', 'сыр', 'чеснок', 'сытная закуска', 'легкая закуска'],
      'og:title': 'Рулетики из ветчины с сыром и чесноком',
      'og:description':
        'Рулетики из ветчины с сырно-чесночной начинкой — отличная идея для закуски на фуршет или праздничный стол. Они эффектно выглядят, получаются сытными и яркими на вкус, а готовятся очень просто. Такой рецепт легко адаптировать под свой вкус — вариантов начинки множество. Мы предлагаем попробовать майонез с добавлением карри — он придаёт рулетикам красивый цвет и оригинальную нотку. А немного мелко нарезанного белого лука добавит пикантности и легкую свежесть. Если времени в обрез, можно ограничиться классикой — натертым сыром, чесноком и обычным майонезом. А если добавить ещё и отварные яйца, измельчённые на мелкой тёрке, начинка получится особенно нежной и в то же время выразительной.',
      'og:url': 'https://povreshka.ru/recipe/rulety-iz-vetchiny-s-syrnom-i-chesnokom',
      'og:image': '/static/recipes/snacks/rulety-iz-vetchiny-s-syrnom-i-chesnokom.jpeg',
      twitterTitle: 'Рулетики из ветчины с сыром и чесноком',
      twitterDescription:
        'Рулетики из ветчины с сырно-чесночной начинкой — отличная идея для закуски на фуршет или праздничный стол. Они эффектно выглядят, получаются сытными и яркими на вкус, а готовятся очень просто. Такой рецепт легко адаптировать под свой вкус — вариантов начинки множество. Мы предлагаем попробовать майонез с добавлением карри — он придаёт рулетикам красивый цвет и оригинальную нотку. А немного мелко нарезанного белого лука добавит пикантности и легкую свежесть. Если времени в обрез, можно ограничиться классикой — натертым сыром, чесноком и обычным майонезом. А если добавить ещё и отварные яйца, измельчённые на мелкой тёрке, начинка получится особенно нежной и в то же время выразительной.',
      twitterImage: '/static/recipes/snacks/rulety-iz-vetchiny-s-syrnom-i-chesnokom.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/rulety-iz-vetchiny-s-syrnom-i-chesnokom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/rulety-iz-vetchiny-s-syrnom-i-chesnokom',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['рулетики', 'ветчина', 'сыр', 'чеснок', 'сытная закуска', 'легкая закуска'],
    categories: [{ name: 'snacks' }],
    key: 'rulety-iz-vetchiny-s-syrnom-i-chesnokom',
    name: 'rulety-iz-vetchiny-s-syrnom-i-chesnokom',
    img: '/static/recipes/snacks/rulety-iz-vetchiny-s-syrnom-i-chesnokom.jpeg',
    title: 'Рулетики из ветчины с сыром и чесноком',
    description:
      'Рулетики из ветчины с сырно-чесночной начинкой — отличная идея для закуски на фуршет или праздничный стол. Они эффектно выглядят, получаются сытными и яркими на вкус, а готовятся очень просто. Такой рецепт легко адаптировать под свой вкус — вариантов начинки множество. Мы предлагаем попробовать майонез с добавлением карри — он придаёт рулетикам красивый цвет и оригинальную нотку. А немного мелко нарезанного белого лука добавит пикантности и легкую свежесть. Если времени в обрез, можно ограничиться классикой — натертым сыром, чесноком и обычным майонезом. А если добавить ещё и отварные яйца, измельчённые на мелкой тёрке, начинка получится особенно нежной и в то же время выразительной.',
    calories: null,
    preparation: null,
    time: 20,
    level: 1,
    rating: 4.75,
    portions: 24,
    used: [8.6, 5, 0.7],
    ingredients: [],
    equipments: [],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Начните с приготовления начинки: сварите яйца вкрутую, остудите их под холодной водой и очистите. Мелко нарежьте яйца, а сыр натрите на крупной терке. Смешайте оба ингредиента в глубокой миске.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Очистите чеснок и натрите его на мелкой терке. Добавьте его к майонезу или натуральному йогурту, если хотите более легкий вариант. Приправьте черным перцем и паприкой, затем заправьте сырно-яичную смесь, тщательно перемешав до однородности.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Разложите ломтики ветчины и выложите на каждый немного начинки. Аккуратно сверните в рулетики. Выложите рулеты на сервировочную тарелку, украсьте зеленью или овощами по вкусу. Перед подачей уберите в холодильник минимум на 20 минут — так они станут плотнее и вкуснее.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Картофельные чипсы в микроволновке',
      description:
        'Любите домашние чипсы, но не хотите возиться с фритюром? Попробуйте этот простой рецепт картофельных чипсов в микроволновке — хрустящие, ароматные и гораздо полезнее магазинных! Всего 3 ингредиента, 5 минут — и вкусная закуска готова.',
      keywords: ['картофельные', 'чипсы', 'микроволновка', 'сытная закуска', 'легкая закуска'],
      'og:title': 'Картофельные чипсы в микроволновке',
      'og:description':
        'Любите домашние чипсы, но не хотите возиться с фритюром? Попробуйте этот простой рецепт картофельных чипсов в микроволновке — хрустящие, ароматные и гораздо полезнее магазинных! Всего 3 ингредиента, 5 минут — и вкусная закуска готова.',
      'og:url': 'https://povreshka.ru/recipe/kartofelnye-chipsy-v-mikrovolnovke',
      'og:image': '/static/recipes/snacks/kartofelnye-chipsy-v-mikrovolnovke.jpeg',
      twitterTitle: 'Картофельные чипсы в микроволновке',
      twitterDescription:
        'Любите домашние чипсы, но не хотите возиться с фритюром? Попробуйте этот простой рецепт картофельных чипсов в микроволновке — хрустящие, ароматные и гораздо полезнее магазинных! Всего 3 ингредиента, 5 минут — и вкусная закуска готова.',
      twitterImage: '/static/recipes/snacks/kartofelnye-chipsy-v-mikrovolnovke.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/kartofelnye-chipsy-v-mikrovolnovke',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/kartofelnye-chipsy-v-mikrovolnovke',
      robots: 'index, follow',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      viewport: 'width=device-width, initial-scale=1',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['яичница', 'болтунья', 'завтрак', 'яйца', 'легкий завтрак'],
    categories: [{ name: 'snacks' }],
    key: 'kartofelnye-chipsy-v-mikrovolnovke',
    name: 'kartofelnye-chipsy-v-mikrovolnovke',
    img: '/static/recipes/snacks/kartofelnye-chipsy-v-mikrovolnovke.jpeg',
    title: 'Картофельные чипсы в микроволновке',
    description:
      'Любите домашние чипсы, но не хотите возиться с фритюром? Попробуйте этот простой рецепт картофельных чипсов в микроволновке — хрустящие, ароматные и гораздо полезнее магазинных! Всего 3 ингредиента, 5 минут — и вкусная закуска готова.',
    calories: null,
    preparation: null,
    time: 15,
    level: 1,
    rating: 4.8,
    portions: 1,
    used: null,
    ingredients: [
      {
        ...INGREDIENTS.potato,
      },
      {
        ...INGREDIENTS.salt,
      },
    ],
    equipments: [
      {
        ...EQUIPMENTS.microwave,
      },
      {
        ...EQUIPMENTS.plate,
      },
      {
        ...EQUIPMENTS.knife,
      },
      {
        ...EQUIPMENTS.grater,
      },
      {
        ...EQUIPMENTS.cutBoard,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Чтобы начать готовку рубленых котлет из куриной грудки на сковороде, замочите мякиш белого хлеба в сливках — это сделает фарш более сочным и мягким. Пока хлеб впитывает сливки, подготовьте остальные ингредиенты.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Для домашнего фарша нарежьте куриные грудки сначала пластами, затем мелкими кубиками. Используйте тяжелый нож и большую разделочную доску. Порубите мясо в фарш, приправьте солью и перцем — это основа для вкусных котлет.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'В ароматную основу для фарша обжарьте нарезанные лук и чеснок на сильном огне до золотистости. Добавьте хлеб со сливками и измельчите все ингредиенты блендером до однородной массы — это придаст котлетам нежность.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Смешайте получившееся пюре из лука, чеснока и хлеба с рубленым куриным фаршем. Накройте пленкой и уберите в холодильник минимум на час — охлаждение улучшит структуру котлет.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Перед тем как жарить, разделите фарш на равные части по 100 граммов. Подготовьте сковороду с растительным маслом и слегка подсоленную муку для панировки — она поможет создать аппетитную корочку.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Сформируйте руками сочные, плотные котлеты и аккуратно обваляйте их в муке. Выложите на горячую сковороду, следя за тем, чтобы не класть слишком много за раз — котлеты должны равномерно обжариться.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description:
          'Обжаривайте куриные котлеты на среднем огне по 2 минуты с каждой стороны до румяной корочки. Затем накройте крышкой, уменьшите огонь и тушите еще 5–7 минут — это обеспечит полную готовность и сочность блюда.',
        ingredients: [],
      },
    ],
  },
  {
    metaSeo: {
      title: 'Сэндвич с авокадо и яйцом пашот — идеальный завтрак',
      description: 'Нежный тост с авокадо, яйцом пашот и хрустящим беконом. Простой рецепт сытного завтрака.',
      keywords: [
        'сэндвич с авокадо',
        'яйцо пашот',
        'завтрак с авокадо',
        'рецепт тоста',
        'быстрый завтрак',
        'питательный завтрак',
        'сэндвич с яйцом',
        'авокадо тост',
        'рецепт для бранча',
        'пп завтрак',
        'хрустящий бекон',
        'сочный завтрак',
        'рецепт с авокадо',
        'тосты на завтрак',
        'яичный сэндвич',
        'рецепт с яйцом пашот',
        'вкусный завтрак',
        'сэндвич с беконом',
        'здоровый завтрак',
        'рецепт для выходных',
      ],
      'og:title': 'Сэндвич с авокадо и яйцом пашот — идеальный завтрак',
      'og:description': 'Нежный тост с авокадо, яйцом пашот и хрустящим беконом.',
      'og:url': 'https://povreshka.ru/recipe/sendvich-s-avokado-i-yaitsom-pashot',
      'og:image': '/static/recipes/snacks/sendvich-s-avokado-i-yaitsom-pashot.jpeg',
      twitterTitle: 'Сэндвич с авокадо и яйцом пашот — идеальный завтрак',
      twitterDescription: 'Нежный тост с авокадо, яйцом пашот и хрустящим беконом.',
      twitterImage: '/static/recipes/snacks/sendvich-s-avokado-i-yaitsom-pashot.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/sendvich-s-avokado-i-yaitsom-pashot',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/sendvich-s-avokado-i-yaitsom-pashot',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['сэндвич с авокадо', 'яйцо пашот', 'завтрак с авокадо', 'рецепт тоста'],
    categories: [{ name: 'breakfast' }],
    key: 'sendvich-s-avokado-i-yaitsom-pashot',
    name: 'sendvich-s-avokado-i-yaitsom-pashot',
    img: '/static/recipes/snacks/sendvich-s-avokado-i-yaitsom-pashot.jpeg',
    title: 'Сэндвич с авокадо и яйцом пашот',
    description: 'Нежный тост с авокадо, яйцом пашот и хрустящим беконом. Идеальный завтрак для выходных.',
    calories: 420,
    preparation: 10,
    time: 20,
    level: 2,
    rating: 4.8,
    portions: 1,
    used: [12, 15, 8],
    ingredients: [
      {
        name: 'Хлеб чиабатта',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Авокадо',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Яйцо',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Бекон',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
      {
        name: 'Соль',
        gauge: 'щепотка',
        count: 1,
        img: null,
      },
      {
        name: 'Черный перец',
        gauge: 'щепотка',
        count: 1,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Тостер',
        img: null,
      },
      {
        name: 'Сковорода',
        img: null,
      },
      {
        name: 'Кастрюля для яйца пашот',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Обжарьте бекон до хрустящей корочки. Авокадо разомните вилкой, добавьте лимонный сок, соль и перец.',
        ingredients: [
          {
            name: 'Бекон',
            gauge: 'г',
            count: 50,
            img: null,
          },
          {
            name: 'Авокадо',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Поджарьте хлеб в тостере. Приготовьте яйцо пашот: в кипящую воду добавьте уксус, сделайте воронку и влейте яйцо. Варите 3 минуты.',
        ingredients: [
          {
            name: 'Хлеб чиабатта',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Яйцо',
            gauge: 'шт',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Намажьте авокадо на тост, сверху выложите бекон и яйцо пашот. Посыпьте солью и перцем.',
        ingredients: [],
      },
    ],
    tips: ['Для идеального яйца пашот используйте очень свежие яйца.', 'Можно заменить бекон на слабосоленую семгу.'],
    variations: [
      {
        name: 'Вегетарианский вариант',
        changes: 'Исключите бекон, добавьте помидоры черри.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Греческий сэндвич с фетой — средиземноморский вкус',
      description: 'Ароматный сэндвич с сыром фета, оливками, свежими овощами и орегано. Легкий и сытный обед.',
      keywords: [
        'греческий сэндвич',
        'сэндвич с фетой',
        'средиземноморская кухня',
        'рецепт с оливками',
        'вегетарианский сэндвич',
        'быстрый обед',
        'сэндвич с овощами',
        'рецепт с фетой',
        'греческая кухня',
        'летний сэндвич',
        'сэндвич с орегано',
        'сочный сэндвич',
        'легкий перекус',
        'рецепт для пикника',
        'сэндвич с огурцом',
        'пп рецепт',
        'быстрый сэндвич',
        'рецепт с помидорами',
        'сэндвич без мяса',
        'свежий обед',
      ],
      'og:title': 'Греческий сэндвич с фетой — средиземноморский вкус',
      'og:description': 'Ароматный сэндвич с сыром фета, оливками и свежими овощами.',
      'og:url': 'https://povreshka.ru/recipe/grecheskiy-sendvich-s-fetoy',
      'og:image': '/static/recipes/snacks/grecheskiy-sendvich-s-fetoy.jpeg',
      twitterTitle: 'Греческий сэндвич с фетой — средиземноморский вкус',
      twitterDescription: 'Ароматный сэндвич с сыром фета, оливками и свежими овощами.',
      twitterImage: '/static/recipes/snacks/grecheskiy-sendvich-s-fetoy.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/grecheskiy-sendvich-s-fetoy',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/grecheskiy-sendvich-s-fetoy',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['греческий сэндвич', 'сэндвич с фетой', 'средиземноморская кухня', 'вегетарианский сэндвич'],
    categories: [{ name: 'vegetarian' }, { name: 'mediterranean' }],
    key: 'grecheskiy-sendvich-s-fetoy',
    name: 'grecheskiy-sendvich-s-fetoy',
    img: '/static/recipes/snacks/grecheskiy-sendvich-s-fetoy.jpeg',
    title: 'Греческий сэндвич с фетой',
    description:
      'Ароматный сэндвич с сыром фета, оливками, огурцами и помидорами. Легкий и свежий обед в греческом стиле.',
    calories: 320,
    preparation: 10,
    time: 15,
    level: 1,
    rating: 4.5,
    portions: 1,
    used: [10, 12, 5],
    ingredients: [
      {
        name: 'Пита или чиабатта',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Сыр фета',
        gauge: 'г',
        count: 80,
        img: null,
      },
      {
        name: 'Оливки',
        gauge: 'г',
        count: 30,
        img: null,
      },
      {
        name: 'Помидор',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Огурец',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Красный лук',
        gauge: 'шт',
        count: 0.25,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Орегано',
        gauge: 'ч.л',
        count: 0.5,
        img: null,
      },
      {
        name: 'Лимонный сок',
        gauge: 'ч.л',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Нож для нарезки',
        img: null,
      },
      {
        name: 'Доска для нарезки',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Огурец и помидор нарежьте тонкими кружочками. Лук — полукольцами. Сыр фета разомните вилкой.',
        ingredients: [
          {
            name: 'Огурец',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Помидор',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Красный лук',
            gauge: 'шт',
            count: 0.25,
            img: null,
          },
          {
            name: 'Сыр фета',
            gauge: 'г',
            count: 80,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте оливковое масло с лимонным соком и орегано. Полейте овощи.',
        ingredients: [
          {
            name: 'Оливковое масло',
            gauge: 'ст.л',
            count: 1,
            img: null,
          },
          {
            name: 'Лимонный сок',
            gauge: 'ч.л',
            count: 1,
            img: null,
          },
          {
            name: 'Орегано',
            gauge: 'ч.л',
            count: 0.5,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Разрежьте питу, наполните сыром, овощами и оливками. Подавайте сразу.',
        ingredients: [
          {
            name: 'Пита или чиабатта',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Оливки',
            gauge: 'г',
            count: 30,
            img: null,
          },
        ],
      },
    ],
    tips: ['Можно добавить листья салата или рукколу.', 'Для пикантности — капля меда в заправку.'],
    variations: [
      {
        name: 'С курицей',
        changes: 'Добавьте обжаренное куриное филе.',
      },
    ],
  },
  {
    metaSeo: {
      title: 'Сэндвич с курицей и песто — сытный обед',
      description: 'Ароматный сэндвич с курицей-гриль, соусом песто и свежими овощами. Быстро и вкусно.',
      keywords: [
        'сэндвич с курицей',
        'рецепт с песто',
        'курица гриль',
        'сытный обед',
        'быстрый перекус',
        'сэндвич с овощами',
        'рецепт с куриным филе',
        'итальянская кухня',
        'сэндвич на гриле',
        'пп рецепт',
        'обед на работе',
        'сочный сэндвич',
        'рецепт с базиликом',
        'быстрый обед',
        'сэндвич с моцареллой',
        'рецепт для пикника',
        'куриный сэндвич',
        'вкусный перекус',
        'сэндвич с зеленым соусом',
        'рецепт с рукколой',
      ],
      'og:title': 'Сэндвич с курицей и песто — сытный обед',
      'og:description': 'Ароматный сэндвич с курицей-гриль, соусом песто и свежими овощами.',
      'og:url': 'https://povreshka.ru/recipe/sendvich-s-kuritsey-i-pesto',
      'og:image': '/static/recipes/snacks/sendvich-s-kuritsey-i-pesto.jpeg',
      twitterTitle: 'Сэндвич с курицей и песто — сытный обед',
      twitterDescription: 'Ароматный сэндвич с курицей-гриль, соусом песто и свежими овощами.',
      twitterImage: '/static/recipes/snacks/sendvich-s-kuritsey-i-pesto.jpeg',
      twitterUrl: 'https://povreshka.ru/recipe/sendvich-s-kuritsey-i-pesto',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://povreshka.ru/recipe/sendvich-s-kuritsey-i-pesto',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
    },
    searchRequests: ['сэндвич с курицей', 'рецепт с песто', 'курица гриль', 'сытный обед'],
    categories: [{ name: 'meat' }, { name: 'italian' }],
    key: 'sendvich-s-kuritsey-i-pesto',
    name: 'sendvich-s-kuritsey-i-pesto',
    img: '/static/recipes/snacks/sendvich-s-kuritsey-i-pesto.jpeg',
    title: 'Сэндвич с курицей и песто',
    description: 'Сочный сэндвич с курицей-гриль, песто, моцареллой и свежими овощами. Идеальный обед или перекус.',
    calories: 450,
    preparation: 15,
    time: 25,
    level: 2,
    rating: 4.6,
    portions: 1,
    used: [15, 18, 10],
    ingredients: [
      {
        name: 'Багет или чиабатта',
        gauge: 'шт',
        count: 1,
        img: null,
      },
      {
        name: 'Куриное филе',
        gauge: 'г',
        count: 150,
        img: null,
      },
      {
        name: 'Песто',
        gauge: 'ст.л',
        count: 2,
        img: null,
      },
      {
        name: 'Моцарелла',
        gauge: 'г',
        count: 50,
        img: null,
      },
      {
        name: 'Помидор',
        gauge: 'шт',
        count: 0.5,
        img: null,
      },
      {
        name: 'Руккола',
        gauge: 'г',
        count: 30,
        img: null,
      },
      {
        name: 'Оливковое масло',
        gauge: 'ст.л',
        count: 1,
        img: null,
      },
      {
        name: 'Чеснок',
        gauge: 'зубчик',
        count: 1,
        img: null,
      },
      {
        name: 'Соль и перец',
        gauge: 'по вкусу',
        count: 1,
        img: null,
      },
    ],
    equipments: [
      {
        name: 'Гриль или сковорода',
        img: null,
      },
      {
        name: 'Кухонные щипцы',
        img: null,
      },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Куриное филе нарежьте на полоски, посолите, поперчите, добавьте измельченный чеснок и обжарьте на гриле до готовности.',
        ingredients: [
          {
            name: 'Куриное филе',
            gauge: 'г',
            count: 150,
            img: null,
          },
          {
            name: 'Чеснок',
            gauge: 'зубчик',
            count: 1,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description:
          'Багет разрежьте вдоль, слегка поджарьте. Намажьте песто, выложите рукколу, помидоры, курицу и моцареллу.',
        ingredients: [
          {
            name: 'Багет или чиабатта',
            gauge: 'шт',
            count: 1,
            img: null,
          },
          {
            name: 'Песто',
            gauge: 'ст.л',
            count: 2,
            img: null,
          },
          {
            name: 'Руккола',
            gauge: 'г',
            count: 30,
            img: null,
          },
          {
            name: 'Помидор',
            gauge: 'шт',
            count: 0.5,
            img: null,
          },
          {
            name: 'Моцарелла',
            gauge: 'г',
            count: 50,
            img: null,
          },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Закройте сэндвич и слегка прижмите. Можно подогреть на гриле 1-2 минуты для расплавленного сыра.',
        ingredients: [],
      },
    ],
    tips: [
      'Можно добавить бальзамический соус для кислинки.',
      'Для хрустящей корочки — используйте пресс для сэндвичей.',
    ],
    variations: [
      {
        name: 'С авокадо',
        changes: 'Добавьте ломтики авокадо для кремовой текстуры.',
      },
    ],
  },
]
