import { RULETY_IZ_VETCHINY_S_SYRNOM_I_CHESNOKOM } from './snacks/rulety-iz-vetchiny-s-syrnom-i-chesnokom'
import { KARTOFELNYE_CHIPSY_V_MIKROVOLNOVKE } from './snacks/kartofelnye-chipsy-v-mikrovolnovke'
import { SENDVICH_S_AVOKADO_I_YAITSOM_PASHOT } from './snacks/sendvich-s-avokado-i-yaitsom-pashot'
import { GRECHESKIY_SENDVICH_S_FETOY } from './snacks/grecheskiy-sendvich-s-fetoy'
import { SENDVICH_S_KURITSEY_I_PESTO } from './snacks/sendvich-s-kuritsey-i-pesto'
import { TARTALETKI_S_IKROY } from './snacks/tartaletki-s-ikroy'
import { TARTALETKI_S_KURITSEY_I_GRIBAMI } from './snacks/tartaletki-s-kuritsey-i-gribami'
import {
  BRUSKETTA_S_TOMATAMI_I_BAZILIKOM,
  FARSHIROVANNYE_YAJTSA_S_GORCHICEJ,
  KABACHKOVYE_OLADI_S_SYROM,
  KANAPE_IZ_OGURTSA_S_LOSOSEM,
  KANAPE_S_SELDYU_I_SVEKLOY,
  RULETIKI_IZ_BAKLAZHANOV_S_FETOY,
  RULETIKI_IZ_LAVASHA_S_LOSOSEM,
  SHAMPINONY_S_SYROM_V_DUHOVKE,
  SYRNYE_SHARIKI_S_KUNZHUTOM,
  TARTALETKI_S_KRABOVYMI_PALOCHKAMI,
} from './snacks/quick-snacks'

export const SNACKS = [
  RULETY_IZ_VETCHINY_S_SYRNOM_I_CHESNOKOM,
  KARTOFELNYE_CHIPSY_V_MIKROVOLNOVKE,
  SENDVICH_S_AVOKADO_I_YAITSOM_PASHOT,
  GRECHESKIY_SENDVICH_S_FETOY,
  SENDVICH_S_KURITSEY_I_PESTO,
  TARTALETKI_S_IKROY,
  TARTALETKI_S_KURITSEY_I_GRIBAMI,
  BRUSKETTA_S_TOMATAMI_I_BAZILIKOM,
  RULETIKI_IZ_LAVASHA_S_LOSOSEM,
  FARSHIROVANNYE_YAJTSA_S_GORCHICEJ,
  KANAPE_IZ_OGURTSA_S_LOSOSEM,
  TARTALETKI_S_KRABOVYMI_PALOCHKAMI,
  SHAMPINONY_S_SYROM_V_DUHOVKE,
  RULETIKI_IZ_BAKLAZHANOV_S_FETOY,
  SYRNYE_SHARIKI_S_KUNZHUTOM,
  KANAPE_S_SELDYU_I_SVEKLOY,
  KABACHKOVYE_OLADI_S_SYROM,
]
