import type { Recipe } from '../recipes'

export const NEW_HEALTHY_RECIPES: Recipe[] = [
  {
    metaSeo: {
      title: 'Батат с красной фасолью и авокадо',
      description:
        'Запеченный батат с красной фасолью, авокадо, лаймом и зеленью. Сытный растительный ужин без сложной подготовки.',
      keywords: ['батат', 'красная фасоль', 'авокадо', 'здоровый ужин', 'растительный рецепт'],
      'og:title': 'Батат с красной фасолью и авокадо',
      'og:description':
        'Запеченный батат с красной фасолью, авокадо, лаймом и зеленью. Сытный растительный ужин без сложной подготовки.',
      'og:url': 'https://food-paradise.ru/recipe/batat-s-krasnoy-fasolyu-i-avokado',
      twitterTitle: 'Батат с красной фасолью и авокадо',
      twitterDescription: 'Сытный растительный ужин с бататом, фасолью, авокадо и лаймом.',
      twitterUrl: 'https://food-paradise.ru/recipe/batat-s-krasnoy-fasolyu-i-avokado',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/batat-s-krasnoy-fasolyu-i-avokado',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['батат с фасолью', 'батат с авокадо', 'запеченный батат', 'полезный ужин с фасолью'],
    categories: [{ name: 'healthy' }, { name: 'vegan' }],
    key: 'batat-s-krasnoy-fasolyu-i-avokado',
    name: 'batat-s-krasnoy-fasolyu-i-avokado',
    img: null,
    title: 'Батат с красной фасолью и авокадо',
    description: 'Мягкий запеченный батат, теплая фасоль и свежий авокадо собираются в простое, сытное и яркое блюдо.',
    calories: 390,
    preparation: 10,
    time: 45,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [35, 10, 5],
    ingredients: [
      { ingredientKey: 'sweetPotato', count: 2, gauge: 'шт.' },
      { ingredientKey: 'fasolKrasnaya', count: 220, gauge: 'г' },
      { ingredientKey: 'avocado', count: 1, gauge: 'шт.' },
      { ingredientKey: 'lime', count: 0.5, gauge: 'шт.' },
      { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'paprikaSladkaya', count: 0.5, gauge: 'ч.л.' },
      { ingredientKey: 'svezhayaZelen', count: 0.5, gauge: 'пучок' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'oven' },
      { equipmentKey: 'bakingTray' },
      { equipmentKey: 'parchment' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'bowl' },
      { equipmentKey: 'spoon' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description:
          'Батат хорошо вымойте, разрежьте вдоль пополам, смажьте оливковым маслом, посыпьте паприкой, солью и перцем.',
        ingredients: [
          { ingredientKey: 'sweetPotato', count: 2, gauge: 'шт.' },
          { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'paprikaSladkaya', count: 0.5, gauge: 'ч.л.' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Выложите батат срезом вверх на противень с пергаментом и запекайте при 200°C 30-35 минут.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Фасоль прогрейте в миске или небольшой кастрюле, затем смешайте с соком лайма.',
        ingredients: [
          { ingredientKey: 'fasolKrasnaya', count: 220, gauge: 'г' },
          { ingredientKey: 'lime', count: 0.5, gauge: 'шт.' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Авокадо нарежьте кубиками, зелень мелко порубите.',
        ingredients: [
          { ingredientKey: 'avocado', count: 1, gauge: 'шт.' },
          { ingredientKey: 'svezhayaZelen', count: 0.5, gauge: 'пучок' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Разомните мякоть батата вилкой, выложите сверху фасоль, авокадо и зелень. Подавайте теплым.',
        ingredients: [],
      },
    ],
    historyDescription:
      'Фаршированный батат часто встречается в современной домашней кухне как удобная альтернатива сложным гарнирам: корнеплод запекают целиком, а сверху добавляют бобовые, овощи и свежие соусы.',
    tips: [
      'Берите бататы похожего размера, чтобы они запеклись одновременно.',
      'Фасоль можно слегка размять с лаймом — начинка получится более кремовой.',
      'Если авокадо очень мягкий, добавляйте его уже в тарелку, чтобы сохранить форму кусочков.',
    ],
    serving: 'Подавайте с зеленым салатом или огурцами.',
    variations: [
      { name: 'Острее', changes: 'Добавьте хлопья красного перца или мелко нарезанный чили.' },
      { name: 'Сытнее', changes: 'Добавьте ложку натурального йогурта, если не нужен веганский вариант.' },
    ],
  },
  {
    metaSeo: {
      title: 'Треска с брокколи и лимоном',
      description: 'Нежная треска с брокколи, лимоном и оливковым маслом. Легкий ужин, который готовится в духовке.',
      keywords: ['треска с брокколи', 'рыба в духовке', 'легкий ужин', 'здоровая еда', 'филе трески'],
      'og:title': 'Треска с брокколи и лимоном',
      'og:description': 'Нежная треска с брокколи, лимоном и оливковым маслом. Легкий ужин в духовке.',
      'og:url': 'https://food-paradise.ru/recipe/treska-s-brokkoli-i-limonom',
      twitterTitle: 'Треска с брокколи и лимоном',
      twitterDescription: 'Простой ужин из трески, брокколи и лимонной заправки.',
      twitterUrl: 'https://food-paradise.ru/recipe/treska-s-brokkoli-i-limonom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/treska-s-brokkoli-i-limonom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['треска с брокколи', 'филе трески в духовке', 'рыба с овощами', 'легкий рыбный ужин'],
    categories: [{ name: 'healthy' }, { name: 'supper' }],
    key: 'treska-s-brokkoli-i-limonom',
    name: 'treska-s-brokkoli-i-limonom',
    img: null,
    title: 'Треска с брокколи и лимоном',
    description: 'Белая рыба запекается рядом с брокколи, а лимонная заправка делает вкус свежим и собранным.',
    calories: 260,
    preparation: 10,
    time: 30,
    level: 1,
    rating: 4.7,
    portions: 2,
    used: [20, 10, 5],
    ingredients: [
      { ingredientKey: 'fileTreski', count: 400, gauge: 'г' },
      { ingredientKey: 'broccoli', count: 300, gauge: 'г' },
      { ingredientKey: 'lemon', count: 0.5, gauge: 'шт.' },
      { ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' },
      { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
      { ingredientKey: 'dill', count: 0.5, gauge: 'пучок' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'oven' },
      { equipmentKey: 'bakingTray' },
      { equipmentKey: 'parchment' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'bowl' },
      { equipmentKey: 'brush' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Брокколи разберите на соцветия, крупные кусочки разрежьте пополам.',
        ingredients: [{ ingredientKey: 'broccoli', count: 300, gauge: 'г' }],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте оливковое масло, сок лимона, измельченный чеснок, соль и перец.',
        ingredients: [
          { ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' },
          { ingredientKey: 'lemon', count: 0.5, gauge: 'шт.' },
          { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Выложите треску и брокколи на противень с пергаментом, смажьте лимонной заправкой.',
        ingredients: [{ ingredientKey: 'fileTreski', count: 400, gauge: 'г' }],
      },
      {
        img: null,
        video: null,
        description: 'Запекайте при 190°C 15-18 минут, пока рыба легко не начнет разделяться вилкой.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Посыпьте блюдо рубленым укропом и подавайте сразу.',
        ingredients: [{ ingredientKey: 'dill', count: 0.5, gauge: 'пучок' }],
      },
    ],
    historyDescription:
      'Запекание рыбы с овощами — один из самых практичных домашних приемов: белок и гарнир готовятся одновременно, а вкус задают масло, цитрус и зелень.',
    tips: [
      'Не передерживайте треску: тонким кускам может хватить 12-14 минут.',
      'Если брокколи замороженная, предварительно обдайте ее горячей водой и обсушите.',
      'Лимонную цедру можно добавить в заправку для более яркого аромата.',
    ],
    serving: 'Хорошо сочетается с киноа, рисом или свежим огурцом.',
    variations: [
      { name: 'С пряностями', changes: 'Добавьте щепотку копченой паприки.' },
      { name: 'С зеленью', changes: 'Замените укроп петрушкой или кинзой.' },
    ],
  },
  {
    metaSeo: {
      title: 'Теплый салат с киноа, тыквой и рукколой',
      description: 'Теплый салат с запеченной тыквой, киноа, рукколой и тыквенными семечками.',
      keywords: ['салат с киноа', 'теплый салат', 'тыква', 'руккола', 'здоровый обед'],
      'og:title': 'Теплый салат с киноа, тыквой и рукколой',
      'og:description': 'Теплый салат с запеченной тыквой, киноа, рукколой и тыквенными семечками.',
      'og:url': 'https://food-paradise.ru/recipe/teplyj-salat-s-kinoa-tykvoy-i-rukkoloy',
      twitterTitle: 'Теплый салат с киноа, тыквой и рукколой',
      twitterDescription: 'Киноа, запеченная тыква и руккола в одном сытном салате.',
      twitterUrl: 'https://food-paradise.ru/recipe/teplyj-salat-s-kinoa-tykvoy-i-rukkoloy',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/teplyj-salat-s-kinoa-tykvoy-i-rukkoloy',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['теплый салат с киноа', 'киноа с тыквой', 'салат с рукколой', 'тыква в духовке салат'],
    categories: [{ name: 'healthy' }, { name: 'vegan' }],
    key: 'teplyj-salat-s-kinoa-tykvoy-i-rukkoloy',
    name: 'teplyj-salat-s-kinoa-tykvoy-i-rukkoloy',
    img: null,
    title: 'Теплый салат с киноа, тыквой и рукколой',
    description: 'Салат с мягкой запеченной тыквой, рассыпчатой киноа, рукколой и хрустящими семечками.',
    calories: 340,
    preparation: 15,
    time: 40,
    level: 1,
    rating: 4.8,
    portions: 3,
    used: [30, 10, 5],
    ingredients: [
      { ingredientKey: 'kinoa', count: 120, gauge: 'г' },
      { ingredientKey: 'water', count: 240, gauge: 'мл' },
      { ingredientKey: 'pumpkin', count: 450, gauge: 'г' },
      { ingredientKey: 'arugula', count: 70, gauge: 'г' },
      { ingredientKey: 'pumpkinSeeds', count: 25, gauge: 'г' },
      { ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' },
      { ingredientKey: 'lemonJuice', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'oven' },
      { equipmentKey: 'bakingTray' },
      { equipmentKey: 'pot' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'bowl' },
      { equipmentKey: 'spoon' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Киноа промойте, залейте водой и варите под крышкой 15 минут до мягкости.',
        ingredients: [
          { ingredientKey: 'kinoa', count: 120, gauge: 'г' },
          { ingredientKey: 'water', count: 240, gauge: 'мл' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Тыкву нарежьте кубиками, смешайте с 1 ст.л. оливкового масла, солью и перцем.',
        ingredients: [
          { ingredientKey: 'pumpkin', count: 450, gauge: 'г' },
          { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Запекайте тыкву при 200°C 20 минут до мягкости и легкой румяности.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте оставшееся масло с лимонным соком, солью и перцем.',
        ingredients: [
          { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'lemonJuice', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Соедините киноа, теплую тыкву и рукколу, полейте заправкой и посыпьте тыквенными семечками.',
        ingredients: [
          { ingredientKey: 'arugula', count: 70, gauge: 'г' },
          { ingredientKey: 'pumpkinSeeds', count: 25, gauge: 'г' },
        ],
      },
    ],
    historyDescription:
      'Теплые салаты стали популярны как формат полноценного обеда: крупа дает основу, запеченные овощи — насыщенный вкус, а свежая зелень освежает блюдо.',
    tips: [
      'Промывайте киноа перед варкой, чтобы убрать возможную горчинку.',
      'Тыкву нарезайте одинаковыми кубиками — так она запечется равномерно.',
      'Рукколу добавляйте в самом конце, чтобы она не завяла слишком сильно.',
    ],
    serving: 'Подавайте теплым или комнатной температуры.',
    variations: [
      { name: 'С сыром', changes: 'Добавьте немного феты, если не нужен веганский вариант.' },
      { name: 'С ореховым акцентом', changes: 'Замените тыквенные семечки кедровыми орехами.' },
    ],
  },
  {
    metaSeo: {
      title: 'Тофу с овощами в кунжутном соусе',
      description: 'Быстрый тофу с брокколи, кабачком, перцем и кунжутным соусом на сковороде.',
      keywords: ['тофу с овощами', 'кунжутный соус', 'веганский ужин', 'здоровая еда', 'овощной стир-фрай'],
      'og:title': 'Тофу с овощами в кунжутном соусе',
      'og:description': 'Быстрый тофу с брокколи, кабачком, перцем и кунжутным соусом на сковороде.',
      'og:url': 'https://food-paradise.ru/recipe/tofu-s-ovoshchami-v-kunzhutnom-souse',
      twitterTitle: 'Тофу с овощами в кунжутном соусе',
      twitterDescription: 'Овощной стир-фрай с тофу, соевым соусом и кунжутом.',
      twitterUrl: 'https://food-paradise.ru/recipe/tofu-s-ovoshchami-v-kunzhutnom-souse',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/tofu-s-ovoshchami-v-kunzhutnom-souse',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['тофу с овощами', 'тофу на сковороде', 'овощи с кунжутом', 'веганский ужин'],
    categories: [{ name: 'healthy' }, { name: 'vegan' }, { name: 'protein' }],
    key: 'tofu-s-ovoshchami-v-kunzhutnom-souse',
    name: 'tofu-s-ovoshchami-v-kunzhutnom-souse',
    img: null,
    title: 'Тофу с овощами в кунжутном соусе',
    description: 'Плотный тофу, хрустящие овощи и простой соус из соевого и кунжутного масла.',
    calories: 310,
    preparation: 15,
    time: 25,
    level: 1,
    rating: 4.7,
    portions: 3,
    used: [15, 7, 3],
    ingredients: [
      { ingredientKey: 'tofu', count: 300, gauge: 'г' },
      { ingredientKey: 'broccoli', count: 250, gauge: 'г' },
      { ingredientKey: 'zucchini', count: 1, gauge: 'шт.' },
      { ingredientKey: 'bolgarskiyPerets', count: 1, gauge: 'шт.' },
      { ingredientKey: 'soevyySous', count: 3, gauge: 'ст.л.' },
      { ingredientKey: 'kunzhutnoeMaslo', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'garlic', count: 2, gauge: 'зубчик' },
      { ingredientKey: 'sesameSeeds', count: 1, gauge: 'ст.л.' },
    ],
    equipments: [
      { equipmentKey: 'pan' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'bowl' },
      { equipmentKey: 'spatula' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Тофу обсушите и нарежьте кубиками.',
        ingredients: [{ ingredientKey: 'tofu', count: 300, gauge: 'г' }],
      },
      {
        img: null,
        video: null,
        description: 'Брокколи разберите на соцветия, кабачок и перец нарежьте кусочками.',
        ingredients: [
          { ingredientKey: 'broccoli', count: 250, gauge: 'г' },
          { ingredientKey: 'zucchini', count: 1, gauge: 'шт.' },
          { ingredientKey: 'bolgarskiyPerets', count: 1, gauge: 'шт.' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте соевый соус, кунжутное масло и измельченный чеснок.',
        ingredients: [
          { ingredientKey: 'soevyySous', count: 3, gauge: 'ст.л.' },
          { ingredientKey: 'kunzhutnoeMaslo', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'garlic', count: 2, gauge: 'зубчик' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Обжарьте тофу 3-4 минуты, добавьте овощи и готовьте еще 5-6 минут, помешивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Влейте соус, перемешайте и прогрейте 1 минуту. Посыпьте кунжутом перед подачей.',
        ingredients: [{ ingredientKey: 'sesameSeeds', count: 1, gauge: 'ст.л.' }],
      },
    ],
    historyDescription:
      'Стир-фрай удобен для домашней кухни: ингредиенты быстро готовятся на сильном огне, сохраняя текстуру и свежий вкус.',
    tips: [
      'Перед жаркой хорошо обсушите тофу, чтобы он лучше подрумянился.',
      'Не перегружайте сковороду: овощи должны жариться, а не тушиться.',
      'Соевый соус соленый, поэтому дополнительная соль обычно не нужна.',
    ],
    serving: 'Подавайте как самостоятельное блюдо или с рисом.',
    variations: [
      { name: 'С остротой', changes: 'Добавьте хлопья красного перца.' },
      { name: 'С грибами', changes: 'Часть брокколи замените шампиньонами.' },
    ],
  },
  {
    metaSeo: {
      title: 'Овощной суп с фасолью и шпинатом',
      description: 'Легкий овощной суп с красной фасолью, шпинатом, сельдереем и томатной основой.',
      keywords: ['овощной суп', 'суп с фасолью', 'суп со шпинатом', 'здоровый обед', 'веганский суп'],
      'og:title': 'Овощной суп с фасолью и шпинатом',
      'og:description': 'Легкий овощной суп с красной фасолью, шпинатом, сельдереем и томатной основой.',
      'og:url': 'https://food-paradise.ru/recipe/ovoshchnoy-sup-s-fasolyu-i-shpinatom',
      twitterTitle: 'Овощной суп с фасолью и шпинатом',
      twitterDescription: 'Простой суп с фасолью, овощами и шпинатом.',
      twitterUrl: 'https://food-paradise.ru/recipe/ovoshchnoy-sup-s-fasolyu-i-shpinatom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/ovoshchnoy-sup-s-fasolyu-i-shpinatom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['овощной суп с фасолью', 'суп со шпинатом', 'постный суп', 'суп с красной фасолью'],
    categories: [{ name: 'healthy' }, { name: 'vegan' }, { name: 'soup' }],
    key: 'ovoshchnoy-sup-s-fasolyu-i-shpinatom',
    name: 'ovoshchnoy-sup-s-fasolyu-i-shpinatom',
    img: null,
    title: 'Овощной суп с фасолью и шпинатом',
    description: 'Теплый суп с фасолью и овощами: простой, насыщенный и удобный для буднего обеда.',
    calories: 230,
    preparation: 15,
    time: 40,
    level: 1,
    rating: 4.7,
    portions: 4,
    used: [25, 10, 5],
    ingredients: [
      { ingredientKey: 'fasolKrasnaya', count: 300, gauge: 'г' },
      { ingredientKey: 'shpinatSvezhiy', count: 80, gauge: 'г' },
      { ingredientKey: 'carrot', count: 1, gauge: 'шт.' },
      { ingredientKey: 'onion', count: 1, gauge: 'шт.' },
      { ingredientKey: 'selderey', count: 2, gauge: 'шт.' },
      { ingredientKey: 'tomatoPaste', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'water', count: 900, gauge: 'мл' },
      { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'pot' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'spoon' },
      { equipmentKey: 'ladle' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Лук, морковь и сельдерей нарежьте небольшими кубиками.',
        ingredients: [
          { ingredientKey: 'onion', count: 1, gauge: 'шт.' },
          { ingredientKey: 'carrot', count: 1, gauge: 'шт.' },
          { ingredientKey: 'selderey', count: 2, gauge: 'шт.' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'В кастрюле разогрейте оливковое масло и обжарьте овощи 5 минут.',
        ingredients: [{ ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' }],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте томатную пасту, фасоль, воду, соль и перец. Варите 20 минут.',
        ingredients: [
          { ingredientKey: 'tomatoPaste', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'fasolKrasnaya', count: 300, gauge: 'г' },
          { ingredientKey: 'water', count: 900, gauge: 'мл' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Шпинат промойте, крупные листья порвите руками.',
        ingredients: [{ ingredientKey: 'shpinatSvezhiy', count: 80, gauge: 'г' }],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте шпинат в суп, прогрейте 1-2 минуты и снимите с огня.',
        ingredients: [],
      },
    ],
    historyDescription:
      'Овощные супы с бобовыми ценят за простую логику: немного овощей для аромата, фасоль для плотности и зелень в конце для свежести.',
    tips: [
      'Если используете консервированную фасоль, промойте ее от жидкости из банки.',
      'Шпинат добавляйте в самом конце, чтобы он сохранил цвет.',
      'Часть фасоли можно размять ложкой, чтобы суп стал гуще.',
    ],
    serving: 'Подавайте с зеленью или ломтиком цельнозернового хлеба.',
    variations: [
      { name: 'С крупой', changes: 'Добавьте 2-3 ст.л. готовой киноа в тарелку.' },
      { name: 'С лимоном', changes: 'Перед подачей добавьте немного лимонного сока.' },
    ],
  },
  {
    metaSeo: {
      title: 'Индейка с кабачком и зеленью',
      description: 'Филе индейки с кабачком, чесноком и зеленью на сковороде. Быстрый белковый ужин.',
      keywords: ['индейка с кабачком', 'филе индейки', 'здоровый ужин', 'ужин на сковороде', 'белковый ужин'],
      'og:title': 'Индейка с кабачком и зеленью',
      'og:description': 'Филе индейки с кабачком, чесноком и зеленью на сковороде. Быстрый белковый ужин.',
      'og:url': 'https://food-paradise.ru/recipe/indeyka-s-kabachkom-i-zelenyu',
      twitterTitle: 'Индейка с кабачком и зеленью',
      twitterDescription: 'Быстрая индейка с кабачком и свежей зеленью.',
      twitterUrl: 'https://food-paradise.ru/recipe/indeyka-s-kabachkom-i-zelenyu',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/indeyka-s-kabachkom-i-zelenyu',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['индейка с кабачком', 'филе индейки на сковороде', 'быстрый ужин из индейки', 'индейка с овощами'],
    categories: [{ name: 'healthy' }, { name: 'protein' }, { name: 'supper' }],
    key: 'indeyka-s-kabachkom-i-zelenyu',
    name: 'indeyka-s-kabachkom-i-zelenyu',
    img: null,
    title: 'Индейка с кабачком и зеленью',
    description: 'Нежное филе индейки быстро обжаривается с кабачком, чесноком и свежей зеленью.',
    calories: 285,
    preparation: 10,
    time: 25,
    level: 1,
    rating: 4.8,
    portions: 3,
    used: [15, 7, 3],
    ingredients: [
      { ingredientKey: 'fileIndeyki', count: 500, gauge: 'г' },
      { ingredientKey: 'zucchini', count: 1, gauge: 'шт.' },
      { ingredientKey: 'garlic', count: 2, gauge: 'зубчик' },
      { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'lemonJuice', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'svezhayaZelen', count: 0.5, gauge: 'пучок' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'pan' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'spatula' },
      { equipmentKey: 'bowl' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Индейку нарежьте полосками, посолите, поперчите и сбрызните лимонным соком.',
        ingredients: [
          { ingredientKey: 'fileIndeyki', count: 500, gauge: 'г' },
          { ingredientKey: 'lemonJuice', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Кабачок нарежьте полукружьями, чеснок измельчите.',
        ingredients: [
          { ingredientKey: 'zucchini', count: 1, gauge: 'шт.' },
          { ingredientKey: 'garlic', count: 2, gauge: 'зубчик' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'На сковороде разогрейте оливковое масло и обжарьте индейку 5-6 минут.',
        ingredients: [{ ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' }],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте кабачок и чеснок, готовьте еще 5 минут, помешивая.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Посыпьте рубленой зеленью, перемешайте и снимите с огня.',
        ingredients: [{ ingredientKey: 'svezhayaZelen', count: 0.5, gauge: 'пучок' }],
      },
    ],
    historyDescription:
      'Индейка с овощами — формат быстрого ужина, где важно не переготовить мясо и дать овощам остаться сочными.',
    tips: [
      'Нарезайте индейку поперек волокон, так кусочки будут мягче.',
      'Кабачок не нужно долго тушить: легкая плотность делает блюдо вкуснее.',
      'Добавляйте чеснок вместе с кабачком, чтобы он не успел подгореть.',
    ],
    serving: 'Подавайте с салатом, киноа или гречкой.',
    variations: [
      { name: 'С перцем', changes: 'Добавьте болгарский перец тонкими полосками.' },
      { name: 'С йогуртом', changes: 'Подавайте с ложкой натурального йогурта.' },
    ],
  },
  {
    metaSeo: {
      title: 'Салат с тунцом, яйцом и авокадо',
      description: 'Сытный салат с тунцом, яйцом, авокадо, огурцом и лимонной заправкой.',
      keywords: ['салат с тунцом', 'салат с авокадо', 'салат с яйцом', 'здоровый салат', 'быстрый обед'],
      'og:title': 'Салат с тунцом, яйцом и авокадо',
      'og:description': 'Сытный салат с тунцом, яйцом, авокадо, огурцом и лимонной заправкой.',
      'og:url': 'https://food-paradise.ru/recipe/salat-s-tuntsom-yaytsom-i-avokado',
      twitterTitle: 'Салат с тунцом, яйцом и авокадо',
      twitterDescription: 'Быстрый салат с тунцом, яйцом, авокадо и свежим огурцом.',
      twitterUrl: 'https://food-paradise.ru/recipe/salat-s-tuntsom-yaytsom-i-avokado',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/salat-s-tuntsom-yaytsom-i-avokado',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['салат с тунцом и авокадо', 'салат с тунцом и яйцом', 'быстрый салат с тунцом', 'полезный салат'],
    categories: [{ name: 'healthy' }, { name: 'salads' }, { name: 'protein' }],
    key: 'salat-s-tuntsom-yaytsom-i-avokado',
    name: 'salat-s-tuntsom-yaytsom-i-avokado',
    img: null,
    title: 'Салат с тунцом, яйцом и авокадо',
    description: 'Быстрый салат для обеда: тунец, яйцо, авокадо, огурец и простая лимонная заправка.',
    calories: 360,
    preparation: 10,
    time: 20,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [10, 5, 5],
    ingredients: [
      { ingredientKey: 'tunetsVSobstvennomSoku', count: 1, gauge: 'банка' },
      { ingredientKey: 'eggs', count: 2, gauge: 'шт.' },
      { ingredientKey: 'avocado', count: 1, gauge: 'шт.' },
      { ingredientKey: 'cucumber', count: 1, gauge: 'шт.' },
      { ingredientKey: 'arugula', count: 60, gauge: 'г' },
      { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'lemonJuice', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'pot' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'bowl' },
      { equipmentKey: 'spoon' },
      { equipmentKey: 'sieve' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Яйца отварите 8-9 минут, остудите и нарежьте дольками.',
        ingredients: [{ ingredientKey: 'eggs', count: 2, gauge: 'шт.' }],
      },
      {
        img: null,
        video: null,
        description: 'Тунец откиньте на сито и разберите вилкой на крупные кусочки.',
        ingredients: [{ ingredientKey: 'tunetsVSobstvennomSoku', count: 1, gauge: 'банка' }],
      },
      {
        img: null,
        video: null,
        description: 'Авокадо и огурец нарежьте ломтиками.',
        ingredients: [
          { ingredientKey: 'avocado', count: 1, gauge: 'шт.' },
          { ingredientKey: 'cucumber', count: 1, gauge: 'шт.' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Смешайте оливковое масло, лимонный сок, соль и перец.',
        ingredients: [
          { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'lemonJuice', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Выложите рукколу, тунец, авокадо, огурец и яйца, полейте заправкой.',
        ingredients: [{ ingredientKey: 'arugula', count: 60, gauge: 'г' }],
      },
    ],
    historyDescription:
      'Салаты с консервированным тунцом давно стали домашним способом быстро собрать полноценный обед без долгой готовки.',
    tips: [
      'Выбирайте тунец в собственном соку, чтобы заправка не получилась слишком тяжелой.',
      'Авокадо нарезайте перед сборкой салата, чтобы оно не потемнело.',
      'Яйца можно сварить заранее и хранить в холодильнике.',
    ],
    serving: 'Подавайте сразу после заправки.',
    variations: [
      { name: 'Сытнее', changes: 'Добавьте отварную киноа или фасоль.' },
      { name: 'Зеленее', changes: 'Замените часть рукколы шпинатом.' },
    ],
  },
  {
    metaSeo: {
      title: 'Рис с овощами и креветками',
      description: 'Рассыпчатый рис с креветками, овощами, имбирем и легким соевым соусом.',
      keywords: ['рис с креветками', 'креветки с овощами', 'здоровый ужин', 'рис с овощами', 'быстрое блюдо'],
      'og:title': 'Рис с овощами и креветками',
      'og:description': 'Рассыпчатый рис с креветками, овощами, имбирем и легким соевым соусом.',
      'og:url': 'https://food-paradise.ru/recipe/ris-s-ovoshchami-i-krevetkami',
      twitterTitle: 'Рис с овощами и креветками',
      twitterDescription: 'Рис, креветки и овощи на сковороде с имбирем и соевым соусом.',
      twitterUrl: 'https://food-paradise.ru/recipe/ris-s-ovoshchami-i-krevetkami',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/ris-s-ovoshchami-i-krevetkami',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: [
      'рис с креветками',
      'креветки с овощами',
      'рис с овощами на сковороде',
      'быстрый ужин с креветками',
    ],
    categories: [{ name: 'healthy' }, { name: 'supper' }, { name: 'seafood' }],
    key: 'ris-s-ovoshchami-i-krevetkami',
    name: 'ris-s-ovoshchami-i-krevetkami',
    img: null,
    title: 'Рис с овощами и креветками',
    description: 'Быстрое блюдо в одной сковороде: рис, креветки, овощи, имбирь и немного соевого соуса.',
    calories: 410,
    preparation: 15,
    time: 35,
    level: 1,
    rating: 4.7,
    portions: 3,
    used: [20, 10, 5],
    ingredients: [
      { ingredientKey: 'rice', count: 160, gauge: 'г' },
      { ingredientKey: 'water', count: 320, gauge: 'мл' },
      { ingredientKey: 'krevetki', count: 300, gauge: 'г' },
      { ingredientKey: 'carrot', count: 1, gauge: 'шт.' },
      { ingredientKey: 'bolgarskiyPerets', count: 1, gauge: 'шт.' },
      { ingredientKey: 'greenOnion', count: 3, gauge: 'шт.' },
      { ingredientKey: 'svezhiyImbir', count: 2, gauge: 'см' },
      { ingredientKey: 'soevyySous', count: 2, gauge: 'ст.л.' },
      { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
    ],
    equipments: [
      { equipmentKey: 'pot' },
      { equipmentKey: 'pan' },
      { equipmentKey: 'knife' },
      { equipmentKey: 'cutBoard' },
      { equipmentKey: 'spatula' },
      { equipmentKey: 'sieve' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Рис промойте, залейте водой и варите под крышкой 15 минут.',
        ingredients: [
          { ingredientKey: 'rice', count: 160, gauge: 'г' },
          { ingredientKey: 'water', count: 320, gauge: 'мл' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Морковь и перец нарежьте тонкой соломкой, зеленый лук — кольцами, имбирь натрите.',
        ingredients: [
          { ingredientKey: 'carrot', count: 1, gauge: 'шт.' },
          { ingredientKey: 'bolgarskiyPerets', count: 1, gauge: 'шт.' },
          { ingredientKey: 'greenOnion', count: 3, gauge: 'шт.' },
          { ingredientKey: 'svezhiyImbir', count: 2, gauge: 'см' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Креветки обсушите. В сковороде разогрейте оливковое масло и обжарьте их 2 минуты.',
        ingredients: [
          { ingredientKey: 'krevetki', count: 300, gauge: 'г' },
          { ingredientKey: 'oliveOil', count: 1, gauge: 'ст.л.' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте овощи и имбирь, готовьте еще 3-4 минуты.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Добавьте рис и соевый соус, перемешайте и прогрейте 1-2 минуты.',
        ingredients: [{ ingredientKey: 'soevyySous', count: 2, gauge: 'ст.л.' }],
      },
    ],
    historyDescription:
      'Рис с овощами и морепродуктами — удобный домашний формат, где заранее сваренная крупа быстро превращается в полноценное блюдо.',
    tips: [
      'Для лучшей текстуры используйте уже остывший рис.',
      'Креветки готовьте быстро, иначе они станут плотными.',
      'Соевый соус добавляйте в конце и пробуйте блюдо перед досаливанием.',
    ],
    serving: 'Подавайте горячим, можно посыпать кунжутом.',
    variations: [
      { name: 'С яйцом', changes: 'Добавьте в сковороду быстро размешанное яйцо.' },
      { name: 'С брокколи', changes: 'Замените часть перца мелкими соцветиями брокколи.' },
    ],
  },
  {
    metaSeo: {
      title: 'Запеканка из брокколи с яйцом',
      description: 'Простая запеканка из брокколи, яиц, молока и сыра для завтрака или легкого ужина.',
      keywords: ['запеканка из брокколи', 'брокколи с яйцом', 'здоровый завтрак', 'легкий ужин', 'яичная запеканка'],
      'og:title': 'Запеканка из брокколи с яйцом',
      'og:description': 'Простая запеканка из брокколи, яиц, молока и сыра для завтрака или легкого ужина.',
      'og:url': 'https://food-paradise.ru/recipe/zapekanka-iz-brokkoli-s-yaytsom',
      twitterTitle: 'Запеканка из брокколи с яйцом',
      twitterDescription: 'Брокколи, яйца, молоко и сыр в простой запеканке.',
      twitterUrl: 'https://food-paradise.ru/recipe/zapekanka-iz-brokkoli-s-yaytsom',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/zapekanka-iz-brokkoli-s-yaytsom',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['запеканка из брокколи', 'брокколи с яйцом', 'омлет с брокколи в духовке', 'легкая запеканка'],
    categories: [{ name: 'healthy' }, { name: 'breakfast' }],
    key: 'zapekanka-iz-brokkoli-s-yaytsom',
    name: 'zapekanka-iz-brokkoli-s-yaytsom',
    img: null,
    title: 'Запеканка из брокколи с яйцом',
    description: 'Нежная запеканка из брокколи, яиц и молока с тонкой сырной корочкой.',
    calories: 290,
    preparation: 10,
    time: 35,
    level: 1,
    rating: 4.7,
    portions: 3,
    used: [20, 10, 5],
    ingredients: [
      { ingredientKey: 'broccoli', count: 350, gauge: 'г' },
      { ingredientKey: 'eggs', count: 4, gauge: 'шт.' },
      { ingredientKey: 'milk', count: 120, gauge: 'мл' },
      { ingredientKey: 'hardCheese', count: 60, gauge: 'г' },
      { ingredientKey: 'oliveOil', count: 1, gauge: 'ч.л.' },
      { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
    ],
    equipments: [
      { equipmentKey: 'oven' },
      { equipmentKey: 'formaDlyaZapekaniya' },
      { equipmentKey: 'pot' },
      { equipmentKey: 'bowl' },
      { equipmentKey: 'whisk' },
      { equipmentKey: 'grater' },
      { equipmentKey: 'colander' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Брокколи разберите на соцветия и отварите 2 минуты в кипящей воде, затем откиньте на дуршлаг.',
        ingredients: [{ ingredientKey: 'broccoli', count: 350, gauge: 'г' }],
      },
      {
        img: null,
        video: null,
        description: 'Яйца взбейте с молоком, солью и перцем.',
        ingredients: [
          { ingredientKey: 'eggs', count: 4, gauge: 'шт.' },
          { ingredientKey: 'milk', count: 120, gauge: 'мл' },
          { ingredientKey: 'solIPerets', count: ' ', gauge: 'по вкусу' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Форму смажьте оливковым маслом и выложите брокколи.',
        ingredients: [{ ingredientKey: 'oliveOil', count: 1, gauge: 'ч.л.' }],
      },
      {
        img: null,
        video: null,
        description: 'Залейте брокколи яичной смесью и посыпьте тертым сыром.',
        ingredients: [{ ingredientKey: 'hardCheese', count: 60, gauge: 'г' }],
      },
      {
        img: null,
        video: null,
        description: 'Запекайте при 180°C 20-25 минут, пока центр не схватится.',
        ingredients: [],
      },
    ],
    historyDescription:
      'Овощные запеканки удобны тем, что превращают простые продукты в цельное блюдо: овощи дают объем, яйца связывают, а сыр добавляет румяную корочку.',
    tips: [
      'Не переваривайте брокколи перед запеканием, иначе она станет слишком мягкой.',
      'Дайте запеканке постоять 5 минут перед нарезкой.',
      'Сыр натирайте мелко — так корочка получится равномернее.',
    ],
    serving: 'Подавайте теплой с салатом из огурцов.',
    variations: [
      { name: 'С зеленью', changes: 'Добавьте укроп или зеленый лук в яичную смесь.' },
      { name: 'С грибами', changes: 'Добавьте заранее обжаренные шампиньоны.' },
    ],
  },
  {
    metaSeo: {
      title: 'Смузи с черникой и овсянкой',
      description: 'Густой смузи с черникой, бананом, овсянкой и миндальным молоком для быстрого завтрака.',
      keywords: ['смузи с черникой', 'смузи с овсянкой', 'здоровый завтрак', 'ягодный смузи', 'быстрый завтрак'],
      'og:title': 'Смузи с черникой и овсянкой',
      'og:description': 'Густой смузи с черникой, бананом, овсянкой и миндальным молоком для быстрого завтрака.',
      'og:url': 'https://food-paradise.ru/recipe/smuzi-s-chernikoy-i-ovsyankoy',
      twitterTitle: 'Смузи с черникой и овсянкой',
      twitterDescription: 'Черника, банан, овсянка и миндальное молоко в густом смузи.',
      twitterUrl: 'https://food-paradise.ru/recipe/smuzi-s-chernikoy-i-ovsyankoy',
      'twitter:card': 'summary_large_image',
      canonicalUrl: 'https://food-paradise.ru/recipe/smuzi-s-chernikoy-i-ovsyankoy',
      robots: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      googlebot: 'index, follow',
      yandex: 'index, follow',
      selfwork: 'index, follow',
      'max-image-preview': 'large',
      author: 'food-paradise',
      'theme-color': '#ffffff',
    },
    searchRequests: ['смузи с черникой', 'смузи с овсянкой', 'черничный смузи', 'быстрый завтрак смузи'],
    categories: [{ name: 'healthy' }, { name: 'breakfast' }, { name: 'vegan' }],
    key: 'smuzi-s-chernikoy-i-ovsyankoy',
    name: 'smuzi-s-chernikoy-i-ovsyankoy',
    img: null,
    title: 'Смузи с черникой и овсянкой',
    description: 'Густой ягодный смузи с овсянкой и бананом, который удобно готовить на завтрак.',
    calories: 280,
    preparation: 5,
    time: 7,
    level: 1,
    rating: 4.8,
    portions: 2,
    used: [5, 2, 1],
    ingredients: [
      { ingredientKey: 'chernika', count: 160, gauge: 'г' },
      { ingredientKey: 'banan', count: 1, gauge: 'шт.' },
      { ingredientKey: 'oatmeal', count: 40, gauge: 'г' },
      { ingredientKey: 'mindalnoeMoloko', count: 300, gauge: 'мл' },
      { ingredientKey: 'semenaChia', count: 1, gauge: 'ст.л.' },
      { ingredientKey: 'cinnamon', count: 0.25, gauge: 'ч.л.' },
    ],
    equipments: [
      { equipmentKey: 'blender' },
      { equipmentKey: 'measuringSpoon' },
      { equipmentKey: 'stakanyDlyaPodachi' },
    ],
    cookingRecipe: [
      {
        img: null,
        video: null,
        description: 'Овсянку залейте миндальным молоком на 3-5 минут, чтобы хлопья немного размягчились.',
        ingredients: [
          { ingredientKey: 'oatmeal', count: 40, gauge: 'г' },
          { ingredientKey: 'mindalnoeMoloko', count: 300, gauge: 'мл' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Банан очистите и разломите на кусочки.',
        ingredients: [{ ingredientKey: 'banan', count: 1, gauge: 'шт.' }],
      },
      {
        img: null,
        video: null,
        description: 'Положите в блендер чернику, банан, овсянку с молоком, чиа и корицу.',
        ingredients: [
          { ingredientKey: 'chernika', count: 160, gauge: 'г' },
          { ingredientKey: 'semenaChia', count: 1, gauge: 'ст.л.' },
          { ingredientKey: 'cinnamon', count: 0.25, gauge: 'ч.л.' },
        ],
      },
      {
        img: null,
        video: null,
        description: 'Взбейте до гладкой густой текстуры.',
        ingredients: [],
      },
      {
        img: null,
        video: null,
        description: 'Разлейте по стаканам и подавайте сразу.',
        ingredients: [],
      },
    ],
    historyDescription:
      'Смузи с овсянкой появился как удобный завтрак для занятых дней: напиток остается быстрым, но получается плотнее обычного ягодного коктейля.',
    tips: [
      'Если используете замороженную чернику, молока может понадобиться чуть больше.',
      'Для более гладкой текстуры берите мелкие овсяные хлопья.',
      'Банан дает сладость, поэтому дополнительный подсластитель обычно не нужен.',
    ],
    serving: 'Подавайте в охлажденных стаканах.',
    variations: [
      { name: 'Гуще', changes: 'Уменьшите молоко до 250 мл и подайте как смузи-боул.' },
      { name: 'С ягодами', changes: 'Замените часть черники малиной или клубникой.' },
    ],
  },
]
