export const MALINOVYJ_CHAJNYJ_FRESH = {
  metaSeo: {
    title: 'Малиновый чайный фреш с базиликом — ягодное наслаждение',
    description: 'Ароматный холодный чай с малиной, базиликом и лаймом. Натуральный энергетик без кофеина!',
    keywords: [
      'малиновый чай',
      'холодный чай',
      'напиток с малиной',
      'чай с базиликом',
      'освежающий чай',
      'летний напиток',
      'ягодный чай',
      'напиток без сахара',
      'здоровый напиток',
      'домашний чай',
      'напиток с лаймом',
      'фруктовый чай',
      'пп напиток',
      'вкусно и полезно',
      'быстрый напиток',
      'напиток в жару',
      'охлаждающий чай',
      'напиток для тонуса',
      'витаминный напиток',
      'рецепт для здоровья',
    ],
    'og:title': 'Малиновый чайный фреш с базиликом — ягодное наслаждение',
    'og:description': 'Ароматный холодный чай с малиной, базиликом и лаймом. Натуральный энергетик без кофеина!',
    'og:url': 'https://food-paradise.ru/recipe/malinovyj-chajnyj-fresh',
    'og:image': '/optimize/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.webp',
    twitterTitle: 'Малиновый чайный фреш с базиликом — ягодное наслаждение',
    twitterDescription: 'Холодный чай с малиной и базиликом — вкусно и полезно!',
    twitterImage: '/optimize/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/malinovyj-chajnyj-fresh',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/malinovyj-chajnyj-fresh',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'базилик',
    'базилик домашний',
    'базилика',
    'замораживают ли малину',
    'зеленый чай',
    'зеленый чай повышает давление',
    'зеленый чай польза',
    'как заморозить малину',
    'как заморозить малину на зиму',
    'купить малину свежую',
    'лайм',
    'лед',
    'ли пить зеленый чай',
    'листьев малины',
    'листья малины чай в домашних условиях',
    'листья малины чай из листьев малины',
    'листья малины чай польза',
    'малина',
    'малина на зиму',
    'малина осенью',
    'малина фреш',
    'малиновый',
    'малиновый чай',
    'малину можно замораживать',
    'мед',
    'можно зеленый чай',
    'можно ли чай с малиной',
    'найди зеленый чай',
    'пил зеленый чай',
    'с малином',
    'свежая малина',
    'свежая малина для организма',
    'свежая малина с сахаром',
    'свежая малина с сахаром на зиму',
    'фреш',
    'чай',
    'чай из базилика',
    'чай из листьев малины',
    'чай листья малины смородины',
    'чай малина мята',
    'чай с базиликом',
    'чай с лаймом',
    'чай с малиновым вареньем',
    'чай с малиной',
    'чай с малиной пьете',
    'чай смородина малина',
    'черный или зеленый чай',
    'ягода малина',
  ],
  categories: [{ name: 'refreshingDrinks' }, { name: 'tea' }],
  key: 'malinovyj-chajnyj-fresh',
  name: 'malinovyj-chajnyj-fresh',
  img: '/optimize/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.webp',
  title: 'Малиновый чайный фреш',
  description: 'Изысканный холодный чай с малиной, свежим базиликом и цитрусовыми нотами лайма. Бодрит без кофеина!',
  calories: 40,
  preparation: 10,
  time: 30,
  level: 1,
  rating: 4.7,
  portions: 2,
  used: [5, 3, 2],
  ingredients: [
    {
      ingredientKey: 'malina',
      gauge: 'г',
      count: 150,
    },
    {
      ingredientKey: 'zelenyyChay',
      gauge: 'ч.л',
      count: 2,
    },
    {
      ingredientKey: 'bazilikSvezhiy',
      gauge: 'г',
      count: 10,
    },
    {
      ingredientKey: 'lime',
      gauge: 'шт.',
      count: 0.5,
    },
    {
      ingredientKey: 'honey',
      gauge: 'ч.л',
      count: 2,
    },
    {
      ingredientKey: 'led',
      gauge: 'стакан',
      count: 1,
    },
  ],
  equipments: [
    {
      equipmentKey: 'chaynik',
    },
    {
      equipmentKey: 'kuvshin',
    },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Заварите зелёный чай 500 мл воды 70°C, дайте настояться 3 минуты, затем охладите.',
      ingredients: [
        {
          ingredientKey: 'zelenyyChay',
          gauge: 'ч.л',
          count: 2,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Малину разомните вилкой, базилик порвите руками. Добавьте в чай вместе с соком лайма и мёдом.',
      ingredients: [
        {
          ingredientKey: 'malina',
          gauge: 'г',
          count: 150,
        },
        {
          ingredientKey: 'bazilikSvezhiy',
          gauge: 'г',
          count: 10,
        },
        {
          ingredientKey: 'lime',
          gauge: 'шт.',
          count: 0.5,
        },
        {
          ingredientKey: 'honey',
          gauge: 'ч.л',
          count: 2,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Добавьте лёд, дайте настояться 15 минут в холодильнике. Процедите перед подачей.',
      ingredients: [
        {
          ingredientKey: 'led',
          gauge: 'стакан',
          count: 1,
        },
      ],
    },
  ],
  tips: ['Для насыщенного цвета добавьте больше малины.', 'Подавайте с веточкой базилика для украшения.'],
  variations: [
    {
      name: 'С клубникой',
      changes: 'Замените половину малины на клубнику.',
    },
  ],
  historyDescription:
    'Малиновый чайный фреш вырос из традиции домашних прохладительных напитков, которые готовили из сезонных фруктов, ягод, трав и холодной воды. Сегодня такие напитки ценят за натуральный вкус и гибкость: сладость легко регулировать, а основу можно менять под настроение и время года.',
}
