export const LOSOS_POD_SYRNOY_KOROCHKOY = {
  metaSeo: {
    title: 'Лосось под сырной корочкой — изысканный ужин за 25 минут',
    description: 'Нежное филе лосося с хрустящей сырной корочкой и лимонным соусом. Просто и элегантно.',
    keywords: [
      'лосось под сыром',
      'рецепт лосося',
      'ужин за 25 минут',
      'рыбные блюда',
      'запеченный лосось',
      'сырная корочка',
      'быстрый ужин',
      'рецепт с филе лосося',
      'изысканный ужин',
      'лимонный соус',
      'ужин для двоих',
      'пп рецепт',
      'лосось в духовке',
      'вкусно и полезно',
      'рецепт с пармезаном',
      'простое блюдо',
      'рыба на ужин',
      'элегантный ужин',
      'рецепт с зеленью',
      'быстрое приготовление',
    ],
    'og:title': 'Лосось под сырной корочкой — изысканный ужин за 25 минут',
    'og:description': 'Нежное филе лосося с хрустящей сырной корочкой и лимонным соусом.',
    'og:url': 'https://food-paradise.ru/recipe/losos-pod-syrnoy-korochkoy',
    'og:image': '/optimize/recipes/supper/losos-pod-syrnoy-korochkoy.webp',
    twitterTitle: 'Лосось под сырной корочкой — изысканный ужин за 25 минут',
    twitterDescription: 'Нежное филе лосося с хрустящей сырной корочкой и лимонным соусом.',
    twitterImage: '/optimize/recipes/supper/losos-pod-syrnoy-korochkoy.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/losos-pod-syrnoy-korochkoy',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/losos-pod-syrnoy-korochkoy',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'вкусная запеченная рыба рецепт',
    'домашний рецепт лосося',
    'запеченная рыба в духовке рецепт',
    'запечь рыбу в духовке рецепты простые',
    'запечь рыбу с овощами в духовке рецепт',
    'как готовить лосось',
    'киш с лососем рецепт',
    'красная рыба',
    'красная рыба с сыром',
    'лимон',
    'лосось',
    'лосось в домашних условиях рецепт',
    'лосось в духовке рецепт',
    'лосось классический рецепт',
    'лосось на сковороде рецепты',
    'лосось рецепты',
    'оливковое масло',
    'пармезан',
    'паста с лососем рецепт',
    'под сырной корочкой',
    'простые рецепты запеченной рыбы',
    'рецепт брокколи с лососем',
    'рецепт запеченной красной рыбы',
    'рецепт запеченной рыбы',
    'рецепт запеченной рыбы в духовке в фольге',
    'рецепт запеченной рыбы в фольге',
    'рецепт лосося в сливочном соусе',
    'рецепт лосося в соусе',
    'рецепт рыба запечен',
    'рецепт ухи из лосося',
    'рыба',
    'рыба с сыром',
    'сколько готовить лосось',
    'сколько готовить лосось в духовке',
    'сколько готовить стейки лосося',
    'сливочный лосось рецепт',
    'соус пармезан',
    'стейк лосося в духовке рецепт',
    'сыр пармезан',
    'сырная корочка',
    'творожный сыр с рыбой',
    'укроп',
    'уха из лосося рецепт',
    'филе лосося',
    'финский суп с лососем рецепт',
    'чеснок',
  ],
  categories: [{ name: 'supper' }, { name: 'fish' }, { name: 'quick' }],
  key: 'losos-pod-syrnoy-korochkoy',
  name: 'losos-pod-syrnoy-korochkoy',
  img: '/optimize/recipes/supper/losos-pod-syrnoy-korochkoy.webp',
  title: 'Лосось под сырной корочкой',
  description:
    'Филе лосося с хрустящей сырной корочкой из пармезана и лимонным соусом. Идеально для романтического ужина.',
  calories: 380,
  preparation: 10,
  time: 25,
  level: 2,
  rating: 4.8,
  portions: 2,
  used: [12, 14],
  ingredients: [
    {
      ingredientKey: 'salmonFillet',
      gauge: 'г',
      count: 400,
    },
    {
      ingredientKey: 'parmezan',
      gauge: 'г',
      count: 50,
    },
    {
      ingredientKey: 'lemon',
      gauge: 'шт.',
      count: 0.5,
    },
    {
      ingredientKey: 'garlic',
      gauge: 'зубчик',
      count: 2,
    },
    {
      ingredientKey: 'olivkovoeMaslo',
      gauge: 'ст.л',
      count: 1,
    },
    {
      ingredientKey: 'dill',
      gauge: 'г',
      count: 10,
    },
    {
      ingredientKey: 'solIPerets',
      gauge: 'по вкусу',
      count: 1,
    },
  ],
  equipments: [
    {
      equipmentKey: 'bakingTray',
    },
    {
      equipmentKey: 'melkayaTerka',
    },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Филе лосося сбрызните оливковым маслом, посолите, поперчите и посыпьте измельченным чесноком.',
      ingredients: [
        {
          ingredientKey: 'salmonFillet',
          gauge: 'г',
          count: 400,
        },
        {
          ingredientKey: 'garlic',
          gauge: 'зубчик',
          count: 2,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Посыпьте тертым пармезаном и запекайте 15 минут при 200°C до золотистой корочки.',
      ingredients: [
        {
          ingredientKey: 'parmezan',
          gauge: 'г',
          count: 50,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Перед подачей полейте лимонным соком и украсьте укропом.',
      ingredients: [
        {
          ingredientKey: 'lemon',
          gauge: 'шт.',
          count: 0.5,
        },
        {
          ingredientKey: 'dill',
          gauge: 'г',
          count: 10,
        },
      ],
    },
  ],
  tips: ['Для хрустящей корочки включите гриль на последние 2 минуты.', 'Подавайте с рисом или овощами на пару.'],
  variations: [
    {
      name: 'С травами',
      changes: 'Добавьте смесь прованских трав к сыру.',
    },
  ],
  historyDescription:
    'Лосось под сырной корочкой — блюдо из повседневной домашней кухни, где важны понятные продукты, насыщенный вкус и надежный результат. Такие рецепты обычно складываются из практики: хозяйки и повара подбирают удобную технологию, уточняют пропорции и оставляют только те приемы, которые действительно помогают сделать ужин вкуснее.',
}
