export const BEZE = {
  metaSeo: {
    title: 'Безе — воздушное французское пирожное за 2 часа',
    description:
      'Идеальное безе с хрустящей корочкой: пошаговый рецепт с фото. Секреты устойчивых пиков, правильная температура сушки и варианты вкусов. Готовится 2 часа в духовке.',
    keywords: ['безе', 'французское пирожное', 'воздушный десерт', 'десерт из белков'],
    'og:title': 'Безе — воздушное французское пирожное за 2 часа',
    'og:description': 'Идеальное безе с хрустящей корочкой: секреты устойчивых пиков и правильная температура сушки.',
    'og:url': 'https://food-paradise.ru/recipe/beze',
    'og:image': '/optimize/recipes/dessert/beze.webp',
    twitterTitle: 'Безе — воздушное французское пирожное за 2 часа',
    twitterDescription: 'Воздушные безе с хрустящей корочкой — просто и изысканно!',
    twitterImage: '/optimize/recipes/dessert/beze.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/beze',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/beze',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'безе',
    'безе в домашних условиях',
    'безе в духовке',
    'безе видео рецепт',
    'безе классический в духовке',
    'безе рецепт',
    'безе рецепт без',
    'безе рецепт в домашних классический духовке',
    'безе рецепт в духовке',
    'безе рецепт классический',
    'безе рецепт классический в домашних условиях',
    'безе рецепт классический в духовке',
    'безе рецепт классический в духовке с сахаром',
    'безе рецепт классический с сахаром',
    'безе с какао',
    'безе с кофе',
    'белок яичного белка',
    'ванильный экстракт',
    'десерт',
    'десерт без',
    'домашнее безе',
    'классическое безе',
    'классическое безе в домашних условиях',
    'классическое безе рецепт в домашних',
    'лимонный сок',
    'приготовление десертов',
    'рецепт безе в домашних условиях',
    'рецепт безе из белков',
    'рецепт безе с сахаром',
    'рецепт домашнего безе',
    'рецепт домашнего безе из белков',
    'рецепт пирога с безе',
    'рецепты безе в духовке домашних условиях',
    'рецепты десертов',
    'сахар',
    'сладкий десерт',
    'торт безе',
    'фото рецепта безе',
    'яичные белки',
    'яичный белок',
  ],
  categories: [{ name: 'dessert' }],
  key: 'beze',
  name: 'beze',
  img: '/optimize/recipes/dessert/beze.webp',
  title: 'Безе классическое',
  description:
    'Французская меренга с хрустящей корочкой и тающей серединой. Соотношение сахара и белков 2:1, сушка при 100°C.',
  calories: 120,
  preparation: 20,
  time: 140,
  level: 2,
  rating: 4.7,
  portions: 15,
  used: [2, 0, 28],
  ingredients: [
    {
      ingredientKey: 'yaichnyeBelki',
      gauge: 'шт.',
      count: 4,
    },
    {
      ingredientKey: 'sugar',
      gauge: 'г',
      count: 200,
    },
    {
      ingredientKey: 'lemonJuice',
      gauge: 'ч.л',
      count: 0.5,
    },
    {
      ingredientKey: 'vanilnyyEkstrakt',
      gauge: 'ч.л',
      count: 0.5,
      optional: true,
    },
    {
      ingredientKey: 'pischevoyKrasitel',
      gauge: 'г',
      count: 1,
      optional: true,
    },
  ],
  equipments: [
    {
      equipmentKey: 'mikser',
    },
    {
      equipmentKey: 'chistayaSuhayaMiska',
    },
    {
      equipmentKey: 'konditerskiyMeshok',
    },
    {
      equipmentKey: 'nasadkaZvezda',
    },
    {
      equipmentKey: 'bakingTray',
    },
    {
      equipmentKey: 'pergamentnayaBumaga',
    },
    {
      equipmentKey: 'kuhonnyyTermometr',
    },
  ],
  cookingRecipe: [
    {
      description: 'В чистой сухой миске взбейте белки с лимонным соком до мягких пиков.',
      ingredients: [
        {
          ingredientKey: 'yaichnyeBelki',
          gauge: 'шт.',
          count: 4,
        },
        {
          ingredientKey: 'lemonJuice',
          gauge: 'ч.л',
          count: 0.5,
        },
      ],
    },
    {
      description: 'Продолжая взбивать, добавляйте сахар по ложке. Добейтесь глянцевой плотной массы.',
      ingredients: [
        {
          ingredientKey: 'sugar',
          gauge: 'г',
          count: 200,
        },
        {
          ingredientKey: 'vanilnyyEkstrakt',
          gauge: 'ч.л',
          count: 0.5,
          optional: true,
        },
        {
          ingredientKey: 'pischevoyKrasitel',
          gauge: 'г',
          count: 1,
          optional: true,
        },
      ],
    },
    {
      description: 'Отсадите безе кондитерским мешком на пергамент. Сушите в духовке при 100°C 2 часа.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Безе держится всего на двух базовых вещах: хорошо взбитых белках и сахаре. При низкой температуре оно не столько печется, сколько сушится, поэтому получает хрустящую оболочку и легкую середину. Это один из самых показательных десертов для работы с меренгой.',
  tips: [
    'Добавляйте сахар постепенно, чтобы он успел раствориться и меренга стала глянцевой.',
    'Оставьте безе остывать в выключенной духовке с приоткрытой дверцей, чтобы оно меньше трескалось.',
  ],
  variations: [
    { name: 'С орехами', changes: 'Аккуратно вмешайте немного мелко рубленного фундука в готовую меренгу.' },
    { name: 'С какао', changes: 'Слегка присыпьте меренгу какао и сделайте мраморные разводы перед отсадкой.' },
  ],
}
