export const KLUBNICHNYY_PAI_S_PESOCHNOY_KROSCHKOY = {
  metaSeo: {
    title: 'Клубничный пай с песочной крошкой — американский десерт за 45 минут',
    description:
      'Классический американский клубничный пай с рассыпчатой крошкой: секреты сочной начинки и идеального теста.',
    keywords: ['клубничный пай', 'американский десерт', 'десерт с клубникой', 'фруктовый пирог'],
    'og:title': 'Клубничный пай с песочной крошкой — американский десерт за 45 минут',
    'og:description': 'Ароматный клубничный пай с хрустящей крошкой — вкус лета!',
    'og:url': 'https://food-paradise.ru/recipe/klubnichnyy-pai-s-pesochnoy-kroschkoy',
    'og:image': '/optimize/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.webp',
    twitterTitle: 'Клубничный пай с песочной крошкой — американский десерт за 45 минут',
    twitterDescription: 'Ароматный клубничный пай с хрустящей крошкой — вкус лета!',
    twitterImage: '/optimize/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/klubnichnyy-pai-s-pesochnoy-kroschkoy',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/klubnichnyy-pai-s-pesochnoy-kroschkoy',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'ванильный экстракт',
    'десерт из ягод',
    'десерт из ягод клубники',
    'десерт с желатином и ягодами',
    'десерт сливки ягоды',
    'десерты из ягод и фруктов',
    'картошка с крошки картошки',
    'клубника',
    'клубника описание',
    'клубника описание сорта',
    'клубника осенью',
    'клубнику можно',
    'клубничный пай',
    'крошка с',
    'крошка с вареньем',
    'крошка с творогом',
    'кукурузный крахмал',
    'лимонный сок',
    'лимонный сок на зиму',
    'миндальная мука',
    'миндальная мука рецепты',
    'мороженое с крошкой',
    'мороженое с шоколадной крошкой',
    'мука пшеничная',
    'мука пшеничная цельнозерновая',
    'песочный пирог с крошкой',
    'печенье из миндальной муки',
    'печенье с крошкой',
    'печенье с шоколадной крошкой',
    'пирог с крошкой',
    'пшеничная мука рецепт',
    'рецепт печенья с крошкой',
    'рецепт печенья с шоколадной крошкой',
    'рецепт пирога с крошкой',
    'рецепт сливочного масла',
    'рецепты десертов ягоды',
    'рецепты с крошкой',
    'рецепты с шоколадной крошкой',
    'с мраморной крошкой',
    'с шоколадной крошкой',
    'сахар',
    'сколько мука пшеничная',
    'сколько сливочного масла',
    'сливочное масло',
    'со сливочным маслом',
    'сорта клубники',
    'сорта пшеничной муки',
    'ягода малина',
    'ягоду малинку',
    'ягоды',
  ],
  categories: [{ name: 'dessert' }],
  key: 'klubnichnyy-pai-s-pesochnoy-kroschkoy',
  name: 'klubnichnyy-pai-s-pesochnoy-kroschkoy',
  img: '/optimize/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.webp',
  title: 'Клубничный пай с крошкой',
  description: 'Американский десерт с клубничной начинкой и песочной крошкой. Подается с ванильным мороженым.',
  calories: 320,
  preparation: 15,
  time: 45,
  level: 2,
  rating: 4.8,
  portions: 6,
  used: [4, 16, 42],
  ingredients: [
    {
      ingredientKey: 'klubnikaSvezhaya',
      gauge: 'г',
      count: 500,
    },
    {
      ingredientKey: 'pshenichnayaMuka',
      gauge: 'г',
      count: 200,
    },
    {
      ingredientKey: 'slivochnoeMaslo2',
      gauge: 'г',
      count: 120,
    },
    {
      ingredientKey: 'sugar',
      gauge: 'г',
      count: 150,
    },
    {
      ingredientKey: 'mindalnayaMuka',
      gauge: 'г',
      count: 50,
    },
    {
      ingredientKey: 'kukuruznyyKrahmal',
      gauge: 'ст.л',
      count: 2,
    },
    {
      ingredientKey: 'lemonJuice',
      gauge: 'ст.л',
      count: 1,
    },
    {
      ingredientKey: 'vanilnyyEkstrakt',
      gauge: 'ч.л',
      count: 1,
    },
  ],
  equipments: [
    {
      equipmentKey: 'formaDlyaVypechki',
    },
    {
      equipmentKey: 'blender',
    },
    {
      equipmentKey: 'miskaDlyaSmeshivaniya',
    },
    {
      equipmentKey: 'bakingTray',
    },
    {
      equipmentKey: 'kuhonnyeVesy',
    },
    {
      equipmentKey: 'pischevayaPlenka',
    },
  ],
  cookingRecipe: [
    {
      description:
        'Для крошки смешайте муку, холодное масло и сахар руками до состояния крупных крошек. Добавьте миндальную муку.',
      ingredients: [
        {
          ingredientKey: 'pshenichnayaMuka',
          gauge: 'г',
          count: 200,
        },
        {
          ingredientKey: 'slivochnoeMaslo2',
          gauge: 'г',
          count: 120,
        },
        {
          ingredientKey: 'sugar',
          gauge: 'г',
          count: 100,
        },
        {
          ingredientKey: 'mindalnayaMuka',
          gauge: 'г',
          count: 50,
        },
      ],
    },
    {
      description: 'Клубнику смешайте с сахаром и крахмалом, половину пюрируйте блендером.',
      ingredients: [
        {
          ingredientKey: 'klubnikaSvezhaya',
          gauge: 'г',
          count: 500,
        },
        {
          ingredientKey: 'sugar',
          gauge: 'г',
          count: 50,
        },
        {
          ingredientKey: 'kukuruznyyKrahmal',
          gauge: 'ст.л',
          count: 2,
        },
        {
          ingredientKey: 'lemonJuice',
          gauge: 'ст.л',
          count: 1,
        },
        {
          ingredientKey: 'vanilnyyEkstrakt',
          gauge: 'ч.л',
          count: 1,
        },
      ],
    },
    {
      description: 'Выложите начинку в форму, посыпьте крошкой. Выпекайте при 180°C 30 минут до золотистого цвета.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Клубничный пай с крошкой — пример десерта, который стал домашней классикой благодаря простому сочетанию понятных продуктов и выразительной текстуры. Такие сладости часто переходили из кондитерских витрин на семейные кухни: рецепт упрощали, подстраивали под доступные ингредиенты и сохраняли главное — аккуратную подачу и ощущение праздника.',
  tips: [
    'Точно взвешивайте ингредиенты: для десертов небольшое отклонение заметно влияет на текстуру.',
    'Перед подачей дайте десерту полностью остыть или стабилизироваться в холодильнике.',
  ],
  variations: [
    { name: 'С ягодами', changes: 'Добавьте свежие или замороженные ягоды для легкой кислинки и яркой подачи.' },
    { name: 'Шоколадный акцент', changes: 'Часть основы или крема дополните какао, шоколадом или шоколадной крошкой.' },
  ],
}
