export const KREM_BRYULE_S_VANILYU = {
  metaSeo: {
    title: 'Крем-брюле с ванилью — французский десерт с хрустящей корочкой',
    description: 'Аутентичный крем-брюле: нежный ванильный крем под карамельной корочкой. Секреты идеальной текстуры.',
    keywords: ['крем-брюле', 'французский десерт', 'десерт с карамелью', 'ванильный десерт'],
    'og:title': 'Крем-брюле с ванилью — французский десерт с хрустящей корочкой',
    'og:description': 'Французский крем-брюле с хрустящей карамелью — просто и изысканно!',
    'og:url': 'https://food-paradise.ru/recipe/krem-bryule-s-vanilyu',
    'og:image': '/optimize/recipes/dessert/krem-bryule-s-vanilyu.webp',
    twitterTitle: 'Крем-брюле с ванилью — французский десерт с хрустящей корочкой',
    twitterDescription: 'Французский крем-брюле с хрустящей карамелью — просто и изысканно!',
    twitterImage: '/optimize/recipes/dessert/krem-bryule-s-vanilyu.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/krem-bryule-s-vanilyu',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/krem-bryule-s-vanilyu',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'белки яичного желтка',
    'борная кислота яичный желток',
    'ваниль',
    'ванильное небо',
    'ванильный',
    'ванильный сахар',
    'ванильный сахар из стручка ванили',
    'ванильный стручок',
    'десерт',
    'десерт без',
    'десерт из клубники',
    'десерт из сливок',
    'десерт из яблок',
    'десерт из ягод',
    'десерт из ягод клубники',
    'десерт крем брюле',
    'десерт павлова',
    'десерт павловой',
    'десерты без выпечки',
    'десерты в домашних условиях',
    'домашнее крем брюле',
    'домашние десерты',
    'как из стручка ванили сделать ванильный',
    'как использовать ванильные стручки',
    'какой тростниковый сахар',
    'коровка крем брюле',
    'король десертов',
    'крем брюле',
    'крем брюле в домашних условиях',
    'крем брюле рецепт',
    'мороженое крем брюле',
    'на одну порцию десерта',
    'на одну порцию десерта из клубники',
    'пломбир крем брюле',
    'пп десерты',
    'приготовление десертов',
    'рецепты десертов',
    'сахар белый',
    'сладкий десерт',
    'сливка',
    'сливки',
    'творожный десерт',
    'торт крем брюле',
    'тростниковый сахар',
    'украшение десертов',
    'холодные десерты',
    'яичный желток',
  ],
  categories: [{ name: 'dessert' }],
  key: 'krem-bryule-s-vanilyu',
  name: 'krem-bryule-s-vanilyu',
  img: '/optimize/recipes/dessert/krem-bryule-s-vanilyu.webp',
  title: 'Крем-брюле ванильное',
  description:
    'Французский десерт с ванильным кремом и хрустящей карамельной корочкой. Требует точного температурного контроля.',
  calories: 380,
  preparation: 20,
  time: 290,
  level: 2,
  rating: 4.9,
  portions: 4,
  used: [6, 28, 32],
  ingredients: [
    {
      ingredientKey: 'cream33',
      gauge: 'мл',
      count: 500,
    },
    {
      ingredientKey: 'vanilnyyStruchok',
      gauge: 'шт.',
      count: 1,
    },
    {
      ingredientKey: 'yaichnyeZheltki',
      gauge: 'шт.',
      count: 6,
    },
    {
      ingredientKey: 'saharBelyy',
      gauge: 'г',
      count: 100,
    },
    {
      ingredientKey: 'saharTrostnikovyy',
      gauge: 'г',
      count: 50,
    },
  ],
  equipments: [
    {
      equipmentKey: 'ramekiny',
    },
    {
      equipmentKey: 'kastryulyaDlyaVodyanoyBani',
    },
    {
      equipmentKey: 'kuhonnyyTermometr',
    },
    {
      equipmentKey: 'mikser',
    },
    {
      equipmentKey: 'sieve',
    },
    {
      equipmentKey: 'gazovayaGorelkaDlyaKaramelizatsii',
    },
    {
      equipmentKey: 'protivenDlyaDuhovki',
    },
  ],
  cookingRecipe: [
    {
      description: 'Нагрейте сливки с ванилью до 80°C. Взбейте желтки с сахаром до светлой массы.',
      ingredients: [
        {
          ingredientKey: 'cream33',
          gauge: 'мл',
          count: 500,
        },
        {
          ingredientKey: 'vanilnyyStruchok',
          gauge: 'шт.',
          count: 1,
        },
        {
          ingredientKey: 'yaichnyeZheltki',
          gauge: 'шт.',
          count: 6,
        },
        {
          ingredientKey: 'saharBelyy',
          gauge: 'г',
          count: 100,
        },
      ],
    },
    {
      description: 'Медленно влейте сливки в желтки, помешивая. Процедите через сито.',
      ingredients: [],
    },
    {
      description: 'Разлейте по рамекинам, запекайте на водяной бане при 150°C 30 минут. Охладите 4 часа.',
      ingredients: [],
    },
    {
      description: 'Перед подачей посыпьте сахаром, карамелизуйте горелкой.',
      ingredients: [
        {
          ingredientKey: 'saharTrostnikovyy',
          gauge: 'г',
          count: 50,
        },
      ],
    },
  ],
}
