export const PANNA_COTTA = {
  metaSeo: {
    title: 'Панна котта с малиновым соусом — итальянский десерт за 15 минут',
    description:
      'Нежная панна котта с хрустящей карамельной корочкой и кисло-сладким малиновым соусом. Секреты идеальной текстуры без комочков.',
    keywords: ['панна котта', 'итальянский десерт', 'десерт без выпечки', 'холодный десерт'],
    'og:title': 'Панна котта с малиновым соусом — итальянский десерт за 15 минут',
    'og:description': 'Нежная панна котта с бархатистой текстурой — готовится за 15 минут!',
    'og:url': 'https://food-paradise.ru/recipe/panna-cotta',
    'og:image': '/optimize/recipes/dessert/panna-cotta.webp',
    twitterTitle: 'Панна котта с малиновым соусом — итальянский десерт за 15 минут',
    twitterDescription: 'Нежная панна котта с бархатистой текстурой — готовится за 15 минут!',
    twitterImage: '/optimize/recipes/dessert/panna-cotta.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/panna-cotta',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/panna-cotta',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'блэк десерт',
    'ванильный стручок',
    'варенье из малины рецепт',
    'вкусные десерты',
    'десерт',
    'десерт без',
    'десерт из клубники',
    'десерт из сливок',
    'десерт из ягод',
    'десерт павлова',
    'десерт павловой',
    'десерт панна котта',
    'домашние десерты',
    'домашние рецепты из малины',
    'домашняя панна котта',
    'желатин',
    'итальянские десерты',
    'кокосовая панна котта',
    'малина',
    'малина рецепт простой',
    'можно десерт',
    'панна котта',
    'панна котта в домашних условиях',
    'панна котта желатин',
    'панна котта из кресс салата',
    'панна котта классический',
    'панна котта классический рецепт в домашних',
    'панна котта кострома',
    'панна котта купить',
    'панна котта рецепт',
    'панна котта рецепт домашний',
    'панна котта рецепт классический',
    'панна котта с клубникой',
    'панна котта с малиной',
    'панна котта с малиной рецепт',
    'панна котта с манго',
    'панна котта свердловский',
    'панна котта фото',
    'пп десерты',
    'приготовление десертов',
    'рецепт панна котта в домашних условиях',
    'рецепты десертов',
    'рецепты с желатином',
    'рецепты с малиной',
    'сахар',
    'сахарная пудра',
    'сладкий десерт',
    'сладкое украшение десерта',
    'сливки',
    'шоколадная панна котта',
    'ягода малина',
    'ягодная панна котта',
    'ягоду малинку',
    'ягоды',
    'ягоды фото',
  ],
  categories: [{ name: 'dessert' }],
  key: 'panna-cotta',
  name: 'panna-cotta',
  img: '/optimize/recipes/dessert/panna-cotta.webp',
  title: 'Панна котта с малиной',
  description: 'Итальянский десерт с бархатистой текстурой и малиновым соусом. Готовится за 15 минут + охлаждение.',
  calories: 280,
  preparation: 15,
  time: 255,
  level: 1,
  rating: 4.8,
  portions: 4,
  used: [3, 22, 18],
  ingredients: [
    {
      ingredientKey: 'cream33',
      gauge: 'мл',
      count: 500,
    },
    {
      ingredientKey: 'vanilnyyStruchok',
      gauge: 'шт.',
      count: 1,
    },
    {
      ingredientKey: 'sugar',
      gauge: 'г',
      count: 80,
    },
    {
      ingredientKey: 'zhelatinListovoy',
      gauge: 'г',
      count: 8,
    },
    {
      ingredientKey: 'malinaSvezhaya',
      gauge: 'г',
      count: 200,
    },
    {
      ingredientKey: 'powderedSugar',
      gauge: 'г',
      count: 30,
    },
    {
      ingredientKey: 'lemonJuice',
      gauge: 'ч.л',
      count: 1,
      optional: true,
    },
  ],
  equipments: [
    {
      equipmentKey: 'soteynik',
    },
    {
      equipmentKey: 'formyDlyaPannaKotty',
    },
    {
      equipmentKey: 'sieve',
    },
    {
      equipmentKey: 'kuhonnyyTermometr',
    },
    {
      equipmentKey: 'miskaDlyaZamachivaniyaZhelatina',
    },
    {
      equipmentKey: 'whisk',
    },
  ],
  cookingRecipe: [
    {
      description:
        'В сотейнике смешайте сливки, ванильный стручок и сахар. Нагревайте на медленном огне до 80°C, не допуская кипения. Снимите с огня, удалите ваниль.',
      ingredients: [
        {
          ingredientKey: 'cream33',
          gauge: 'мл',
          count: 500,
        },
        {
          ingredientKey: 'vanilnyyStruchok',
          gauge: 'шт.',
          count: 1,
        },
        {
          ingredientKey: 'sugar',
          gauge: 'г',
          count: 80,
        },
      ],
    },
    {
      description:
        'Замочите желатин в холодной воде на 5 минут. Отожмите и растворите в горячих сливках, тщательно размешивая.',
      ingredients: [
        {
          ingredientKey: 'zhelatinListovoy',
          gauge: 'г',
          count: 8,
        },
      ],
    },
    {
      description: 'Разлейте смесь по формочкам, охладите до комнатной температуры. Уберите в холодильник на 4 часа.',
      ingredients: [],
    },
    {
      description:
        'Для соуса протрите малину через сито, смешайте с сахарной пудрой. Подавайте панна котту, поливая соусом.',
      ingredients: [
        {
          ingredientKey: 'malinaSvezhaya',
          gauge: 'г',
          count: 200,
        },
        {
          ingredientKey: 'powderedSugar',
          gauge: 'г',
          count: 30,
        },
        {
          ingredientKey: 'lemonJuice',
          gauge: 'ч.л',
          count: 1,
          optional: true,
        },
      ],
    },
  ],
  historyDescription:
    'Панна котта с малиной — пример десерта, который стал домашней классикой благодаря простому сочетанию понятных продуктов и выразительной текстуры. Такие сладости часто переходили из кондитерских витрин на семейные кухни: рецепт упрощали, подстраивали под доступные ингредиенты и сохраняли главное — аккуратную подачу и ощущение праздника.',
  tips: [
    'Точно взвешивайте ингредиенты: для десертов небольшое отклонение заметно влияет на текстуру.',
    'Перед подачей дайте десерту полностью остыть или стабилизироваться в холодильнике.',
  ],
  variations: [
    { name: 'С ягодами', changes: 'Добавьте свежие или замороженные ягоды для легкой кислинки и яркой подачи.' },
    { name: 'Шоколадный акцент', changes: 'Часть основы или крема дополните какао, шоколадом или шоколадной крошкой.' },
  ],
}
