export const PIROZHNOYE_KARTOSHKA = {
  metaSeo: {
    title: 'Пирожное Картошка — классический советский десерт за 20 минут',
    description:
      'Легендарное пирожное Картошка из детства: простой рецепт с печеньем и какао. Без выпечки, готовится за 20 минут.',
    keywords: ['пирожное картошка', 'советский десерт', 'десерт с печеньем', 'десерт без выпечки'],
    'og:title': 'Пирожное Картошка — классический советский десерт за 20 минут',
    'og:description': 'Ностальгическое пирожное Картошка — вкус детства!',
    'og:url': 'https://food-paradise.ru/recipe/pirozhnoye-kartoshka',
    'og:image': '/optimize/recipes/dessert/pirozhnoye-kartoshka.webp',
    twitterTitle: 'Пирожное Картошка — классический советский десерт за 20 минут',
    twitterDescription: 'Ностальгическое пирожное Картошка — вкус детства!',
    twitterImage: '/optimize/recipes/dessert/pirozhnoye-kartoshka.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/pirozhnoye-kartoshka',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/pirozhnoye-kartoshka',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
  },
  searchRequests: [
    'белый молочный шоколад',
    'белый шоколад',
    'вареное сгущенное молоко',
    'вареное сгущенное молоко отзывы',
    'горький шоколад',
    'горький шоколад можно',
    'грецкий орех',
    'домашние конфеты рецепты',
    'как сварить какао из порошка',
    'какао',
    'какао в домашних условиях из какао порошка',
    'какао из порошка на молоке',
    'какао можно',
    'какао порошок',
    'какао порошок как приготовить',
    'кедровые орехи',
    'конфеты',
    'конфеты коровка рецепт',
    'конфеты молоко рецепт',
    'конфеты рецепт',
    'коньяк',
    'корица',
    'корица молотая',
    'молоко сгущенное вареное алексеевское',
    'молоко сгущенное с сахаром вареное',
    'молочный шоколад',
    'орех фундук',
    'орехи',
    'печенье',
    'рецепт какао',
    'рецепт конфет в домашних условиях',
    'рецепт печенья',
    'рецепт сливок',
    'рецепты с корицей',
    'сварить какао на молоке из порошка',
    'сколько конфет',
    'сколько орехов',
    'сколько сливочного масла',
    'сливки',
    'сливочное масло',
    'со сгущенным молоком вареным',
    'со сливками',
    'трюфель',
    'трюфель конфеты',
    'трюфель конфеты рецепт',
    'трюфельные конфеты',
    'фундук',
    'шоколад',
    'шоколад из какао порошка',
    'шоколад с молочной начинкой',
    'шоколад с фундуком',
    'шоколадное какао',
    'шоколадные конфеты',
  ],
  categories: [{ name: 'dessert' }],
  key: 'pirozhnoye-kartoshka',
  name: 'pirozhnoye-kartoshka',
  img: '/optimize/recipes/dessert/pirozhnoye-kartoshka.webp',
  title: 'Пирожное Картошка',
  description:
    'Культовый советский десерт из печенья, сгущенки и какао. Формируется вручную и обваливается в какао-порошке.',
  calories: 320,
  preparation: 20,
  time: 140,
  level: 1,
  rating: 4.9,
  portions: 10,
  used: [4, 18, 35],
  ingredients: [
    {
      ingredientKey: 'pecheneYubileynoe',
      gauge: 'г',
      count: 300,
    },
    {
      ingredientKey: 'sguschennoeMolokoVarenoe',
      gauge: 'г',
      count: 200,
    },
    {
      ingredientKey: 'slivochnoeMaslo',
      gauge: 'г',
      count: 100,
    },
    {
      ingredientKey: 'kakaoPoroshok',
      gauge: 'г',
      count: 30,
    },
    {
      ingredientKey: 'konyak',
      gauge: 'ст.л',
      count: 1,
      optional: true,
    },
    {
      ingredientKey: 'vanillaSugar',
      gauge: 'ч.л',
      count: 1,
    },
  ],
  equipments: [
    {
      equipmentKey: 'blenderIliSkalka',
    },
    {
      equipmentKey: 'miskaDlyaSmeshivaniya',
    },
    {
      equipmentKey: 'spatula',
    },
    {
      equipmentKey: 'pischevayaPlenka',
    },
    {
      equipmentKey: 'mernyyStakan',
    },
  ],
  cookingRecipe: [
    {
      description: 'Измельчите печенье в крошку с помощью блендера или скалки. Добавьте какао и перемешайте.',
      ingredients: [
        {
          ingredientKey: 'pecheneYubileynoe',
          gauge: 'г',
          count: 300,
        },
        {
          ingredientKey: 'kakaoPoroshok',
          gauge: 'г',
          count: 15,
        },
      ],
    },
    {
      description: 'Смешайте сгущенку с размягченным маслом до однородности. Соедините с печеньем.',
      ingredients: [
        {
          ingredientKey: 'sguschennoeMolokoVarenoe',
          gauge: 'г',
          count: 200,
        },
        {
          ingredientKey: 'slivochnoeMaslo',
          gauge: 'г',
          count: 100,
        },
        {
          ingredientKey: 'konyak',
          gauge: 'ст.л',
          count: 1,
          optional: true,
        },
        {
          ingredientKey: 'vanillaSugar',
          gauge: 'ч.л',
          count: 1,
        },
      ],
    },
    {
      description: 'Сформируйте шарики или клубни, обваляйте в какао. Охладите 2 часа.',
      ingredients: [
        {
          ingredientKey: 'kakaoPoroshok',
          gauge: 'г',
          count: 15,
        },
      ],
    },
  ],
  historyDescription:
    'Пирожное Картошка — пример десерта, который стал домашней классикой благодаря простому сочетанию понятных продуктов и выразительной текстуры. Такие сладости часто переходили из кондитерских витрин на семейные кухни: рецепт упрощали, подстраивали под доступные ингредиенты и сохраняли главное — аккуратную подачу и ощущение праздника.',
  tips: [
    'Точно взвешивайте ингредиенты: для десертов небольшое отклонение заметно влияет на текстуру.',
    'Перед подачей дайте десерту полностью остыть или стабилизироваться в холодильнике.',
  ],
  variations: [
    { name: 'С ягодами', changes: 'Добавьте свежие или замороженные ягоды для легкой кислинки и яркой подачи.' },
    { name: 'Шоколадный акцент', changes: 'Часть основы или крема дополните какао, шоколадом или шоколадной крошкой.' },
  ],
}
