export const SHU_S_KREMOM = {
  metaSeo: {
    title: 'Шу с кремом — воздушные профитроли за 1 час',
    description:
      'Французские профитроли Шу с заварным кремом: пошаговый рецепт с фото. Секреты пустот внутри, идеальный заварной крем и варианты начинок. Выпекается 25 минут.',
    keywords: [
      'шу с кремом',
      'французские профитроли',
      'воздушные пирожные',
      'десерт с заварным кремом',
      'десерт за 1 час',
      'легкие пирожные',
      'десерт из заварного теста',
      'праздничный десерт',
      'десерт для гостей',
      'кофейный десерт',
      'шоколадный шу',
      'ванильные профитроли',
      'десерт к чаю',
      'ресторанный десерт',
      'пошаговый рецепт',
    ],
    'og:title': 'Шу с кремом — воздушные профитроли за 1 час',
    'og:description': 'Французские профитроли Шу с заварным кремом: секреты пустот внутри и идеальный крем.',
    'og:url': 'https://food-paradise.ru/recipe/shu-s-kremom',
    'og:image': '/optimize/recipes/dessert/shu-s-kremom.webp',
    twitterTitle: 'Шу с кремом — воздушные профитроли за 1 час',
    twitterDescription: 'Воздушные профитроли Шу с нежным кремом — французская классика!',
    twitterImage: '/optimize/recipes/dessert/shu-s-kremom.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/shu-s-kremom',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/shu-s-kremom',
    robots: 'index, follow',
    googlebot: 'index, follow',
    yandex: 'index, follow',
    selfwork: 'index, follow',
    'max-image-preview': 'large',
    viewport: 'width=device-width, initial-scale=1',
    author: 'food-paradise',
    'theme-color': '#ffffff',
  },
  searchRequests: [
    'без сливочного масла',
    'вода',
    'десерты рецепты в домашних',
    'десерты рецепты в домашних условиях',
    'домашние пирожные',
    'домашняя картошка пирожное',
    'заварные пирожные',
    'кукурузный крахмал',
    'молоко',
    'пирожное',
    'пирожное в домашних условиях',
    'пирожное из печенья',
    'пирожное картошка',
    'пирожное картошка в домашних условиях',
    'пирожное картошка из печенья',
    'пирожное картошка рецепт',
    'пирожное рецепт в домашних',
    'пирожное рецепт в домашних условиях',
    'пирожное с кремом',
    'пирожное шу с заварным кремом',
    'пирожное шу с кремом',
    'простые рецепты десертов',
    'рецепт пирожных',
    'рецепты десертов',
    'сколько пирожных',
    'сливочное ли масло',
    'со сливочным маслом',
    'соль',
    'фото рецепты десерт',
    'французские пирожные',
    'шу',
    'шу с ванильным кремом',
    'шу с заварным кремом',
    'шу с кремом',
    'шу с кремом рецепт',
  ],
  categories: [{ name: 'dessert' }],
  key: 'shu-s-kremom',
  name: 'shu-s-kremom',
  img: '/optimize/recipes/dessert/shu-s-kremom.webp',
  title: 'Шу с кремом',
  description:
    "Классика французской кондитерской школы — воздушные полые пирожные из заварного теста, наполненные ванильным заварным кремом. Особенность рецепта — точное соблюдение пропорций теста (вода, мука, масло, яйца) и техника 'открытой духовки' для идеального подъема. Подаются присыпанными сахарной пудрой.",
  calories: 280,
  preparation: 35,
  time: 60,
  level: 3,
  rating: 4.9,
  portions: 12,
  used: [6, 18, 25],
  ingredients: [
    {
      ingredientKey: 'water',
      gauge: 'мл',
      count: 250,
    },
    {
      ingredientKey: 'slivochnoeMaslo',
      gauge: 'г',
      count: 100,
    },
    {
      ingredientKey: 'pshenichnayaMuka',
      gauge: 'г',
      count: 150,
    },
    {
      ingredientKey: 'yaytsa',
      gauge: 'шт.',
      count: 4,
    },
    {
      ingredientKey: 'salt',
      gauge: 'щепотка',
      count: 1,
    },
    {
      ingredientKey: 'milk',
      gauge: 'мл',
      count: 500,
    },
    {
      ingredientKey: 'yaichnyeZheltki',
      gauge: 'шт.',
      count: 4,
    },
    {
      ingredientKey: 'sugar',
      gauge: 'г',
      count: 100,
    },
    {
      ingredientKey: 'kukuruznyyKrahmal',
      gauge: 'г',
      count: 40,
    },
    {
      ingredientKey: 'vanilnyyEkstrakt',
      gauge: 'ч.л',
      count: 1,
    },
    {
      ingredientKey: 'powderedSugar',
      gauge: 'г',
      count: 30,
    },
  ],
  equipments: [
    {
      equipmentKey: 'kastryulyaSrednegoRazmera',
    },
    {
      equipmentKey: 'derevyannayaLopatka',
    },
    {
      equipmentKey: 'konditerskiyMeshok',
    },
    {
      equipmentKey: 'nasadkaDlyaMeshka',
    },
    {
      equipmentKey: 'bakingTray',
    },
    {
      equipmentKey: 'pergamentnayaBumaga',
    },
    {
      equipmentKey: 'mikser',
    },
    {
      equipmentKey: 'kuhonnyeVesy',
    },
    {
      equipmentKey: 'termometrKuhonnyy',
    },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Для теста вскипятите воду с маслом и солью. Всыпьте муку, интенсивно размешивая.',
      ingredients: [
        {
          ingredientKey: 'water',
          gauge: 'мл',
          count: 250,
        },
        {
          ingredientKey: 'slivochnoeMaslo',
          gauge: 'г',
          count: 100,
        },
        {
          ingredientKey: 'pshenichnayaMuka',
          gauge: 'г',
          count: 150,
        },
        {
          ingredientKey: 'salt',
          gauge: 'щепотка',
          count: 1,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: "Охладите до 60°C, добавляйте яйца по одному. Тесто должно стекать 'лентой'.",
      ingredients: [
        {
          ingredientKey: 'yaytsa',
          gauge: 'шт.',
          count: 4,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Отсадите шарики на пергамент. Выпекайте при 200°C 10 минут, затем при 180°C 15 минут.',
      ingredients: [],
    },
    {
      img: null,
      video: null,
      description: 'Для крема смешайте молоко, желтки, сахар и крахмал. Варите до загустения, добавьте ваниль.',
      ingredients: [
        {
          ingredientKey: 'milk',
          gauge: 'мл',
          count: 500,
        },
        {
          ingredientKey: 'yaichnyeZheltki',
          gauge: 'шт.',
          count: 4,
        },
        {
          ingredientKey: 'sugar',
          gauge: 'г',
          count: 100,
        },
        {
          ingredientKey: 'kukuruznyyKrahmal',
          gauge: 'г',
          count: 40,
        },
        {
          ingredientKey: 'vanilnyyEkstrakt',
          gauge: 'ч.л',
          count: 1,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Наполните остывшие профитроли кремом через отверстие снизу. Посыпьте пудрой.',
      ingredients: [
        {
          ingredientKey: 'powderedSugar',
          gauge: 'г',
          count: 30,
        },
      ],
    },
  ],
  historyDescription:
    'Шу с кремом — пример десерта, который стал домашней классикой благодаря простому сочетанию понятных продуктов и выразительной текстуры. Такие сладости часто переходили из кондитерских витрин на семейные кухни: рецепт упрощали, подстраивали под доступные ингредиенты и сохраняли главное — аккуратную подачу и ощущение праздника.',
  tips: [
    'Точно взвешивайте ингредиенты: для десертов небольшое отклонение заметно влияет на текстуру.',
    'Перед подачей дайте десерту полностью остыть или стабилизироваться в холодильнике.',
  ],
  variations: [
    { name: 'С ягодами', changes: 'Добавьте свежие или замороженные ягоды для легкой кислинки и яркой подачи.' },
    { name: 'Шоколадный акцент', changes: 'Часть основы или крема дополните какао, шоколадом или шоколадной крошкой.' },
  ],
}
