export const LOSOS_NA_KEDROVOY_DOSKE_S_MEDOVO_GORCHICHNYM_SOUSOM = {
  metaSeo: {
    title: 'Лосось на кедровой доске — изысканный рыбный рецепт',
    description:
      'Нежный лосось, приготовленный на кедровой доске с медово-горчичной глазурью. Техника копчения на гриле.',
    keywords: [
      'лосось на гриле',
      'рыба на кедровой доске',
      'медово-горчичный соус',
      'рецепт лосося',
      'здоровое питание',
      'рыба на гриле',
      'лосось с медом',
      'дачный рецепт',
      'изысканный ужин',
      'скандинавская кухня',
      'гриль с дымком',
      'пп рецепты',
      'омега-3',
      'красная рыба',
      'быстрый ужин',
      'рецепт для гостей',
      'домашнее копчение',
      'лосось стейк',
      'низкоуглеводный рецепт',
      'рыбный пикник',
    ],
    'og:title': 'Лосось на кедровой доске — изысканный рыбный рецепт',
    'og:description': 'Нежный лосось, приготовленный на кедровой доске с медово-горчичной глазурью.',
    'og:url': 'https://food-paradise.ru/recipe/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
    'og:image': '/optimize/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.webp',
    twitterTitle: 'Лосось на кедровой доске — изысканный рыбный рецепт',
    twitterDescription: 'Нежный лосось, приготовленный на кедровой доске с медово-горчичной глазурью.',
    twitterImage: '/optimize/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
    robots: 'index, follow',
    viewport: 'width=device-width, initial-scale=1',
    googlebot: 'index, follow',
    yandex: 'index, follow',
    selfwork: 'index, follow',
    'max-image-preview': 'large',
    author: 'food-paradise',
    'theme-color': '#ffffff',
  },
  searchRequests: [
    'глазурь',
    'горчица дижонская зернистая',
    'дижонская горчица',
    'дижонская горчица от обычной',
    'дижонская горчица рецепт',
    'дижонская горчица фото',
    'дижонская горчица чем отличается',
    'дижонская и французская горчица',
    'домашний рецепт лосося',
    'домашняя дижонская горчица',
    'запеченный стейк лосося',
    'какое оливковое масло',
    'кедровая доска',
    'киш с лососем рецепт',
    'лимон',
    'лимонный сок',
    'лимонный сок рецепт',
    'лосось',
    'лосось в домашних условиях рецепт',
    'лосось в духовке рецепт',
    'лосось классический рецепт',
    'лосось на кедровой доске',
    'лосось на сковороде рецепты',
    'лосось рецепты',
    'лосось с брокколи рецепт',
    'мед',
    'можно оливковое масло',
    'огурцы с дижонской горчицей на зиму',
    'оливковое масло',
    'паста с лососем рецепт',
    'рецепт глазури',
    'рецепт лосось в соусе',
    'рецепт лосося в сливочном соусе',
    'рецепт ухи из лосося',
    'рецепты с лимоном',
    'сливочный лосось рецепт',
    'стейк из лосося',
    'стейк лосося в духовке',
    'стейк лосося в духовке рецепт',
    'стейк лосося в духовке сколько',
    'стейк лосося на сковороде',
    'суп с лососем и сливками рецепт',
    'укроп',
    'укроп чеснок',
    'уха из лосося рецепт',
    'финский суп с лососем рецепт',
    'чеснок',
    'чеснок на зиму',
  ],
  categories: [{ name: 'grill' }, { name: 'fish' }],
  key: 'losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
  name: 'losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom',
  img: '/optimize/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.webp',
  title: 'Лосось на кедровой доске',
  description:
    'Стейк лосося с медово-горчичной глазурью, приготовленный на кедровой доске для легкого дымного аромата. Подается с дольками лимона.',
  calories: 280,
  preparation: 15,
  time: 35,
  level: 2,
  rating: 4.9,
  portions: 2,
  used: [25, 18, 5],
  ingredients: [
    {
      ingredientKey: 'steykLososya',
      gauge: 'г',
      count: 400,
    },
    {
      ingredientKey: 'kedrovayaDoska',
      gauge: 'шт.',
      count: 1,
    },
    {
      ingredientKey: 'dizhonskayaGorchitsa',
      gauge: 'ст.л',
      count: 2,
    },
    {
      ingredientKey: 'honey',
      gauge: 'ст.л',
      count: 1,
    },
    {
      ingredientKey: 'lemonJuice',
      gauge: 'ст.л',
      count: 1,
    },
    {
      ingredientKey: 'garlic',
      gauge: 'зубчик',
      count: 1,
    },
    {
      ingredientKey: 'ukropSvezhiy',
      gauge: 'пучок',
      count: 1,
    },
    {
      ingredientKey: 'morskayaSol',
      gauge: 'ч.л',
      count: 0.5,
    },
    {
      ingredientKey: 'lemon',
      gauge: 'шт.',
      count: 0.5,
    },
    {
      ingredientKey: 'olivkovoeMaslo',
      gauge: 'ст.л',
      count: 1,
    },
  ],
  equipments: [
    {
      equipmentKey: 'grilIliMangal',
    },
    {
      equipmentKey: 'kulinarnyeSchiptsy',
    },
    {
      equipmentKey: 'kistochkaDlyaGlazuri',
    },
    {
      equipmentKey: 'miskaDlyaSmeshivaniya',
    },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Замочите кедровую доску в воде на 1-2 часа (можно с белым вином). Это предотвратит возгорание.',
      ingredients: [
        {
          ingredientKey: 'kedrovayaDoska',
          gauge: 'шт.',
          count: 1,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Смешайте горчицу, мед, лимонный сок, измельченный чеснок и рубленый укроп для глазури.',
      ingredients: [
        {
          ingredientKey: 'dizhonskayaGorchitsa',
          gauge: 'ст.л',
          count: 2,
        },
        {
          ingredientKey: 'honey',
          gauge: 'ст.л',
          count: 1,
        },
        {
          ingredientKey: 'lemonJuice',
          gauge: 'ст.л',
          count: 1,
        },
        {
          ingredientKey: 'garlic',
          gauge: 'зубчик',
          count: 1,
        },
        {
          ingredientKey: 'ukropSvezhiy',
          gauge: 'пучок',
          count: 1,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Лосося промокните салфеткой, сбрызните оливковым маслом, посолите. Намажьте 2/3 глазури.',
      ingredients: [
        {
          ingredientKey: 'steykLososya',
          gauge: 'г',
          count: 400,
        },
        {
          ingredientKey: 'olivkovoeMaslo',
          gauge: 'ст.л',
          count: 1,
        },
        {
          ingredientKey: 'morskayaSol',
          gauge: 'ч.л',
          count: 0.5,
        },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Разогрейте гриль до 180°C. Положите лосося кожей вниз на доску. Готовьте 12-15 минут под крышкой.',
      ingredients: [],
    },
    {
      img: null,
      video: null,
      description: 'За 2 минуты до готовности намажьте оставшейся глазурью. Подавайте на доске с дольками лимона.',
      ingredients: [
        {
          ingredientKey: 'lemon',
          gauge: 'шт.',
          count: 0.5,
        },
      ],
    },
  ],
}
