export const PHO_BO = {
  metaSeo: {
    title: 'Фо Бо — вьетнамский суп с говядиной | Аутентичный рецепт с фото',
    description:
      'Настоящий вьетнамский фо: прозрачный ароматный бульон, тончайшая говядина и правильная лапша. Секреты приготовления за 4 часа, набор специй и традиционная подача. Рецепт от шефа из Ханоя.',
    keywords: [
      'фо бо',
      'вьетнамский суп',
      'суп с говядиной',
      'азиатские супы',
      'рецепт фо',
      'суп с лапшой',
      'вьетнамская кухня',
      'прозрачный бульон',
      'суп за 4 часа',
      'имбирный суп',
      'аутентичный фо',
      'говяжий суп',
      'суп со звездчатым анисом',
      'подача фо бо',
      'рецепт от шефа',
    ],
    'og:title': 'Фо Бо — вьетнамский суп с говядиной | Аутентичный рецепт',
    'og:description':
      'Настоящий вьетнамский фо: прозрачный бульон, тонкая говядина и правильная лапша. Секреты приготовления за 4 часа.',
    'og:url': 'https://food-paradise.ru/recipe/pho-bo',
    'og:image': '/optimize/recipes/dinner/pho-bo.webp',
    twitterTitle: 'Фо Бо — вьетнамский суп с говядиной | Аутентичный рецепт',
    twitterDescription: 'Научитесь готовить настоящий фо как в уличных кафе Ханоя!',
    twitterImage: '/optimize/recipes/dinner/pho-bo.webp',
    twitterUrl: 'https://food-paradise.ru/recipe/pho-bo',
    'twitter:card': 'summary_large_image',
    canonicalUrl: 'https://food-paradise.ru/recipe/pho-bo',
    robots: 'index, follow',
    googlebot: 'index, follow',
    yandex: 'index, follow',
    selfwork: 'index, follow',
    'max-image-preview': 'large',
    viewport: 'width=device-width, initial-scale=1',
    author: 'food-paradise',
    'theme-color': '#ffffff',
  },

  searchRequests: [
    'вкусный суп с говядиной',
    'вьетнамские супы фо',
    'вьетнамский суп',
    'вьетнамский фо бо',
    'гороховый суп с говядиной',
    'гороховый суп с говядиной рецепт',
    'кинза',
    'классические супы',
    'классический фо бо',
    'кости с костным мозгом',
    'кости с мозгами',
    'кость с мозгом',
    'куриный суп',
    'лайм',
    'лапша фо бо',
    'приготовление супа с говядины',
    'простой суп с говядиной',
    'простые рецепты супов с говядиной',
    'рецепт супа из говядины с рисом',
    'рецепты супов домашних с говядиной',
    'суп',
    'суп домашний с говядиной',
    'суп из говядины с картошкой',
    'суп из говядины с пошаговый рецепт',
    'суп картофель с говядиной',
    'суп классический рецепт',
    'суп пюре',
    'суп с говядиной',
    'суп с говядиной и картошкой рецепт',
    'суп с говядиной и рисом',
    'суп с говядиной классический',
    'суп с говядиной пошаговый',
    'суп с говядиной рецепт классический',
    'суп с говядиной рецепт приготовления',
    'суп с говядиной рецепты',
    'суп с говядиной рецепты с фото',
    'суп с говядины вкусный рецепт',
    'суп с говядины с фото',
    'суп с мясом говядины',
    'суп с мясом говядины рецепт',
    'суп с рисом из говядины классический',
    'суп фо бо',
    'суп фо бо рецепт',
    'суп фо бо с говядиной',
    'суп фо с говядиной',
    'суп харчо домашний рецепт с говядиной',
    'суп харчо из говядины с рисом',
    'суп харчо классический из говядины с рисом',
    'суп харчо классический с говядиной',
    'суп харчо рецепт классический с говядиной',
    'суп харчо с говядиной',
    'суп харчо с говядиной пошаговый рецепт',
    'суп харчо с говядиной рецепт',
    'суп харчо с говядиной рецепт приготовления',
    'супы рецепты',
    'фо бо',
    'фо бо в домашних условиях',
    'фо бо домашний',
    'фо бо домашний рецепт',
    'фо бо доставка',
    'фо бо калорийность',
    'фо бо меню',
    'фо бо ресторан',
    'фо бо рецепт',
    'фо бо рецепт в домашних условиях',
    'фо бо рецепт классический',
    'фо бо с говядиной',
    'фо бо с говядиной рецепт',
    'чили',
  ],
  categories: [{ name: 'dinner' }, { name: 'soups' }, { name: 'asian' }],
  key: 'pho-bo',
  name: 'pho-bo',
  img: '/optimize/recipes/dinner/pho-bo.webp',
  title: 'Фо Бо (вьетнамский суп с говядиной)',

  description:
    "Коронное блюдо вьетнамской кухни — фо бо требует особого подхода к приготовлению бульона. Наш рецепт повторяет технологию уличных поваров Ханоя: 4-часовое томление костей с обугленным имбирем и луком, набор специй (звездчатый анис, корица, гвоздика, кориандр) и рисовую лапшу 'бань фо'. Особенность — добавление сырой говядины тончайшей нарезки прямо в тарелку: она готовится от горячего бульона.",

  calories: 380,
  preparation: 60,
  time: 240,
  level: 3,
  rating: 4.9,
  portions: 4,
  used: [55.3, 70.2, 30.1],

  historyDescription:
    'Фо бо — символ Вьетнама. Он появился в начале XX века, когда местные повара адаптировали французские мясные бульоны, добавив восточные специи, рисовую лапшу и свежие травы. Сегодня фо готовят повсюду — от уличных лавок до ресторанов.',

  ingredients: [
    { ingredientKey: 'beefBones', count: 1.5, gauge: 'кг.' },
    { ingredientKey: 'beefBrisket', count: 0.4, gauge: 'кг.' },
    { ingredientKey: 'water', count: 6, gauge: 'л.' },
    { ingredientKey: 'onion', count: 2, gauge: 'шт.' },
    { ingredientKey: 'ginger', count: 60, gauge: 'г.' },
    { ingredientKey: 'starAnise', count: 2, gauge: 'шт.' },
    { ingredientKey: 'cinnamonStick', count: 1, gauge: 'шт.' },
    { ingredientKey: 'cloves', count: 4, gauge: 'шт.' },
    { ingredientKey: 'corianderSeeds', count: 1, gauge: 'ч.л.' },
    { ingredientKey: 'fishSauce', count: 3, gauge: 'ст.л.' },
    { ingredientKey: 'sugar', count: 1, gauge: 'ст.л.' },
    { ingredientKey: 'salt', count: 1, gauge: 'ч.л.' },
    { ingredientKey: 'riceNoodles', count: 300, gauge: 'г.' },
    { ingredientKey: 'beefTenderloin', count: 0.3, gauge: 'кг.' },
    { ingredientKey: 'lime', count: 1, gauge: 'шт.' },
    { ingredientKey: 'chiliPepper', count: 1, gauge: 'шт.' },
    { ingredientKey: 'beanSprouts', count: 1, gauge: 'горсть' },
    { ingredientKey: 'cilantro', count: 1, gauge: 'горсть' },
    { ingredientKey: 'greenOnion', count: 1, gauge: 'пуч.' },
  ],
  equipments: [
    { equipmentKey: 'pot' },
    { equipmentKey: 'sieve' },
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'pan' },
    { equipmentKey: 'tongs' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'spoon' },
  ],
  cookingRecipe: [
    {
      description:
        'Подготовьте кости: залейте холодной водой, доведите до кипения, варите 5 минут. Слейте, промойте кости и кастрюлю — это уберёт запах и лишнюю пену.',
      ingredients: [
        { ingredientKey: 'beefBones', count: 1.5, gauge: 'кг.' },
        { ingredientKey: 'water', count: 2, gauge: 'л.' },
      ],
    },
    {
      description:
        'Залейте кости заново 4 л воды, добавьте грудинку. Доведите до кипения, снимите пену и варите на минимальном огне 3 часа.',
      ingredients: [
        { ingredientKey: 'beefBones', count: 1.5, gauge: 'кг.' },
        { ingredientKey: 'beefBrisket', count: 0.4, gauge: 'кг.' },
        { ingredientKey: 'water', count: 4, gauge: 'л.' },
      ],
    },
    {
      description:
        'На сухой сковороде обуглите лук и имбирь до чёрных подпалин (около 10 минут). Очистите и добавьте в бульон вместе со специями: звёздчатым анисом, корицей, гвоздикой и кориандром. Варите ещё 1 час.',
      ingredients: [
        { ingredientKey: 'onion', count: 2, gauge: 'шт.' },
        { ingredientKey: 'ginger', count: 60, gauge: 'г.' },
        { ingredientKey: 'starAnise', count: 2, gauge: 'шт.' },
        { ingredientKey: 'cinnamonStick', count: 1, gauge: 'шт.' },
        { ingredientKey: 'cloves', count: 4, gauge: 'шт.' },
        { ingredientKey: 'corianderSeeds', count: 1, gauge: 'ч.л.' },
      ],
    },
    {
      description:
        'Процедите бульон через сито, верните на слабый огонь. Добавьте рыбный соус, сахар и щепоть соли. Попробуйте — вкус должен быть солоновато-сладким с ярким умами.',
      ingredients: [
        { ingredientKey: 'fishSauce', count: 3, gauge: 'ст.л.' },
        { ingredientKey: 'sugar', count: 1, gauge: 'cт.л.' },
        { ingredientKey: 'salt', count: 1, gauge: 'ч.л.' },
      ],
    },
    {
      description:
        'Достаньте грудинку, остудите и нарежьте ломтиками. Замочите рисовую лапшу в горячей воде на 1 минуту, откиньте на дуршлаг и разложите по глубоким мискам.',
      ingredients: [
        { ingredientKey: 'beefBrisket', count: 0.4, gauge: 'кг.' },
        { ingredientKey: 'riceNoodles', count: 300, gauge: 'г.' },
      ],
    },
    {
      description:
        'Сырую вырезку нарежьте тончайшими ломтиками (удобнее, если мясо слегка подморожено). Выложите поверх лапши и ломтиков грудинки.',
      ingredients: [{ ingredientKey: 'beefTenderloin', count: 0.3, gauge: 'кг.' }],
    },
    {
      description:
        'Залейте всё кипящим бульоном. Украсьте ростками бобов, зелёным луком, кинзой, дольками лайма и перцем чили. Подавайте сразу — мясо должно оставаться розовым.',
      ingredients: [
        { ingredientKey: 'beanSprouts', count: 1, gauge: 'горсть' },
        { ingredientKey: 'greenOnion', count: 1, gauge: 'пуч.' },
        { ingredientKey: 'cilantro', count: 1, gauge: 'горсть' },
        { ingredientKey: 'lime', count: 1, gauge: 'шт.' },
        { ingredientKey: 'chiliPepper', count: 1, gauge: 'шт.' },
      ],
    },
  ],
  tips: [
    'Используйте кости с костным мозгом — бульон получится насыщенным.',
    'С солью будьте осторожны: основную солёность даёт рыбный соус, поэтому досаливайте только после него.',
    'Подморозьте говядину перед нарезкой, чтобы получить тонкие ломтики.',
    'Подавайте сразу — мясо готовится от горячего бульона и должно быть розовым.',
  ],
  variations: [
    {
      name: 'Фо Га',
      changes: 'Замените говядину на курицу и используйте куриный бульон.',
    },
    {
      name: 'Вегетарианский фо',
      changes: 'Используйте овощной бульон, тофу и грибы шиитаке вместо мяса.',
    },
  ],
}
