// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  btn: {
    default: {
      label: 'Кнопка default'
    }
    primary: {
      label: 'Кнопка primary'
    }
  }
  localeSelect: {
    label: 'Выберите язык'
    locale: {
      ru: 'Рус'
      en: 'Англ'
    }
  }
  manifest: {
    name: 'next-intl example'
  }
  localeLayout: {
    title: 'next-intl example'
  }
  notFoundPage: {
    description: 'Пожалуйста, еще раз проверьте адресную строку браузера или воспользуйтесь навигацией, чтобы перейти на известную страницу.'
    title: 'Страница не найдена'
  }
}
export default messages
