const createMetaSeo = (key: string, title: string, description: string, keywords: string[]) => ({
  title,
  description,
  keywords,
  'og:title': title,
  'og:description': description,
  'og:url': `https://food-paradise.ru/recipe/${key}`,
  twitterTitle: title,
  twitterDescription: description,
  twitterUrl: `https://food-paradise.ru/recipe/${key}`,
  'twitter:card': 'summary_large_image',
  canonicalUrl: `https://food-paradise.ru/recipe/${key}`,
  robots: 'index, follow',
  viewport: 'width=device-width, initial-scale=1',
  googlebot: 'index, follow',
  yandex: 'index, follow',
  selfwork: 'index, follow',
  'max-image-preview': 'large',
  author: 'food-paradise',
  'theme-color': '#ffffff',
})

export const BRUSKETTA_S_TOMATAMI_I_BAZILIKOM = {
  metaSeo: createMetaSeo(
    'brusketta-s-tomatami-i-bazilikom',
    'Брускетта с томатами и базиликом',
    'Хрустящая брускетта с сочными томатами, чесноком, базиликом и оливковым маслом.',
    ['брускетта', 'закуска с помидорами', 'итальянская закуска', 'быстрая закуска'],
  ),
  searchRequests: ['брускетта с помидорами', 'итальянская закуска', 'закуска на багете'],
  categories: [{ name: 'snacks' }],
  key: 'brusketta-s-tomatami-i-bazilikom',
  name: 'brusketta-s-tomatami-i-bazilikom',
  img: null,
  title: 'Брускетта с томатами и базиликом',
  description: 'Быстрая хрустящая закуска с томатами, базиликом и чесночным ароматом.',
  calories: 185,
  preparation: 10,
  time: 8,
  level: 1,
  rating: 4.8,
  portions: 4,
  used: [5, 7, 24],
  ingredients: [
    { ingredientKey: 'ciabatta', count: 1, gauge: 'шт.' },
    { ingredientKey: 'tomato', count: 3, gauge: 'шт.' },
    { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
    { ingredientKey: 'basil', count: 10, gauge: 'г' },
    { ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' },
    { ingredientKey: 'salt', gauge: 'по вкусу' },
    { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
  ],
  equipments: [
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'pan' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Нарежьте чиабатту ломтиками и подсушите на сухой сковороде до легкой корочки.',
      ingredients: [{ ingredientKey: 'ciabatta', count: 1, gauge: 'шт.' }],
    },
    {
      img: null,
      video: null,
      description:
        'Томаты нарежьте мелкими кубиками, смешайте с базиликом, оливковым маслом, солью и перцем. Подсушенный хлеб натрите разрезанным зубчиком чеснока.',
      ingredients: [
        { ingredientKey: 'tomato', count: 3, gauge: 'шт.' },
        { ingredientKey: 'basil', count: 10, gauge: 'г' },
        { ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' },
        { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
        { ingredientKey: 'salt', gauge: 'по вкусу' },
        { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Выложите томатную смесь на теплые ломтики хлеба и подавайте сразу, пока основа хрустит.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Брускетта родилась как простой итальянский способ использовать хороший хлеб и сезонные овощи. В домашней кухне она ценится за честный вкус: хрустящая основа, спелые томаты, аромат чеснока и свежий базилик.',
  tips: [
    'Берите плотные спелые томаты, чтобы начинка не стала водянистой.',
    'Собирайте брускетту прямо перед подачей.',
  ],
  variations: [
    { name: 'С сыром', changes: 'Добавьте немного феты или твердого сыра.' },
    { name: 'С оливками', changes: 'Вмешайте рубленые оливки в томатную начинку.' },
  ],
}

export const RULETIKI_IZ_LAVASHA_S_LOSOSEM = {
  metaSeo: createMetaSeo(
    'ruletiki-iz-lavasha-s-lososem',
    'Рулетики из лаваша с лососем',
    'Нежные рулетики из лаваша со слабосоленым лососем, сливочным сыром и зеленью.',
    ['рулетики из лаваша', 'закуска с лососем', 'лаваш с красной рыбой', 'быстрая закуска'],
  ),
  searchRequests: ['рулетики из лаваша с лососем', 'лаваш с красной рыбой', 'закуска на праздничный стол'],
  categories: [{ name: 'snacks' }],
  key: 'ruletiki-iz-lavasha-s-lososem',
  name: 'ruletiki-iz-lavasha-s-lososem',
  img: null,
  title: 'Рулетики из лаваша с лососем',
  description: 'Праздничная закуска из тонкого лаваша, сливочного сыра, слабосоленого лосося и зелени.',
  calories: 245,
  preparation: 15,
  time: 20,
  level: 1,
  rating: 4.9,
  portions: 6,
  used: [12, 16, 21],
  ingredients: [
    { ingredientKey: 'lavash', count: 2, gauge: 'листа' },
    { ingredientKey: 'salmonSalted', count: 180, gauge: 'г' },
    { ingredientKey: 'creamCheese', count: 180, gauge: 'г' },
    { ingredientKey: 'cucumber', count: 1, gauge: 'шт.' },
    { ingredientKey: 'dill', count: 15, gauge: 'г' },
    { ingredientKey: 'lemonJuice', count: 1, gauge: 'ч.л.' },
  ],
  equipments: [
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'spoon' },
    { equipmentKey: 'fridge' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Смешайте сливочный сыр с рубленым укропом и лимонным соком.',
      ingredients: [
        { ingredientKey: 'creamCheese', count: 180, gauge: 'г' },
        { ingredientKey: 'dill', count: 15, gauge: 'г' },
        { ingredientKey: 'lemonJuice', count: 1, gauge: 'ч.л.' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Смажьте лаваш сырной массой, разложите ломтики лосося и тонкие полоски огурца.',
      ingredients: [
        { ingredientKey: 'lavash', count: 2, gauge: 'листа' },
        { ingredientKey: 'salmonSalted', count: 180, gauge: 'г' },
        { ingredientKey: 'cucumber', count: 1, gauge: 'шт.' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Плотно сверните рулеты, охладите 20 минут и нарежьте порционными кусочками.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Рулеты из лаваша стали популярной домашней закуской благодаря простоте и аккуратной подаче. Начинка с лососем и сливочным сыром напоминает классические канапе, но готовится быстрее и легко нарезается на порции.',
  tips: [
    'Не кладите слишком много начинки, иначе рулет будет плохо держать форму.',
    'Нарезайте хорошо охлажденный рулет острым ножом.',
  ],
  variations: [
    { name: 'С авокадо', changes: 'Добавьте тонкие ломтики авокадо вместо огурца.' },
    { name: 'С пикантностью', changes: 'Вмешайте в сыр щепотку перца или немного горчицы.' },
  ],
}

export const FARSHIROVANNYE_YAJTSA_S_GORCHICEJ = {
  metaSeo: createMetaSeo(
    'farshirovannye-yajtsa-s-gorchicej',
    'Фаршированные яйца с горчицей',
    'Классическая холодная закуска из яиц с нежной горчичной начинкой и зеленью.',
    ['фаршированные яйца', 'закуска из яиц', 'яйца с горчицей', 'холодная закуска'],
  ),
  searchRequests: ['фаршированные яйца', 'закуска из яиц', 'яйца с майонезом и горчицей'],
  categories: [{ name: 'snacks' }],
  key: 'farshirovannye-yajtsa-s-gorchicej',
  name: 'farshirovannye-yajtsa-s-gorchicej',
  img: null,
  title: 'Фаршированные яйца с горчицей',
  description: 'Проверенная холодная закуска с кремовой желтковой начинкой, горчицей и зеленью.',
  calories: 168,
  preparation: 10,
  time: 15,
  level: 1,
  rating: 4.7,
  portions: 6,
  used: [13, 11, 3],
  ingredients: [
    { ingredientKey: 'eggs', count: 6, gauge: 'шт.' },
    { ingredientKey: 'mayonnaise', count: 2, gauge: 'ст.л.' },
    { ingredientKey: 'mustard', count: 1, gauge: 'ч.л.' },
    { ingredientKey: 'dill', count: 10, gauge: 'г' },
    { ingredientKey: 'salt', gauge: 'по вкусу' },
    { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
  ],
  equipments: [{ equipmentKey: 'pot' }, { equipmentKey: 'knife' }, { equipmentKey: 'bowl' }, { equipmentKey: 'fork' }],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Яйца отварите вкрутую, охладите, очистите и разрежьте вдоль пополам.',
      ingredients: [{ ingredientKey: 'eggs', count: 6, gauge: 'шт.' }],
    },
    {
      img: null,
      video: null,
      description: 'Желтки разомните вилкой с майонезом, горчицей, солью, перцем и частью укропа.',
      ingredients: [
        { ingredientKey: 'mayonnaise', count: 2, gauge: 'ст.л.' },
        { ingredientKey: 'mustard', count: 1, gauge: 'ч.л.' },
        { ingredientKey: 'dill', count: 10, gauge: 'г' },
        { ingredientKey: 'salt', gauge: 'по вкусу' },
        { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Наполните половинки белков начинкой, украсьте оставшимся укропом и охладите до подачи.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Фаршированные яйца — одна из самых устойчивых праздничных закусок домашней кухни. Простая основа позволяет менять вкус начинки, а горчица добавляет желткам легкую остроту и делает блюдо выразительнее.',
  tips: [
    'Не переваривайте яйца, чтобы желток не получил серый ободок.',
    'Начинку можно переложить в кондитерский мешок для аккуратной подачи.',
  ],
  variations: [
    { name: 'С рыбой', changes: 'Добавьте немного мелко нарезанного лосося или сельди.' },
    { name: 'С паприкой', changes: 'Посыпьте готовые яйца копченой паприкой.' },
  ],
}

export const KANAPE_IZ_OGURTSA_S_LOSOSEM = {
  metaSeo: createMetaSeo(
    'kanape-iz-ogurtsa-s-lososem',
    'Канапе из огурца с лососем',
    'Свежие канапе на кружочках огурца со сливочным сыром, лососем и укропом.',
    ['канапе с лососем', 'закуска с огурцом', 'закуска без хлеба', 'быстрые канапе'],
  ),
  searchRequests: ['канапе с лососем', 'огурец сливочный сыр лосось', 'закуска без хлеба'],
  categories: [{ name: 'snacks' }],
  key: 'kanape-iz-ogurtsa-s-lososem',
  name: 'kanape-iz-ogurtsa-s-lososem',
  img: null,
  title: 'Канапе из огурца с лососем',
  description: 'Легкая закуска без хлеба: хрустящий огурец, сливочный сыр, лосось и укроп.',
  calories: 132,
  preparation: 15,
  time: 0,
  level: 1,
  rating: 4.8,
  portions: 4,
  used: [11, 9, 4],
  ingredients: [
    { ingredientKey: 'cucumber', count: 2, gauge: 'шт.' },
    { ingredientKey: 'salmonSalted', count: 120, gauge: 'г' },
    { ingredientKey: 'creamCheese', count: 120, gauge: 'г' },
    { ingredientKey: 'dill', count: 10, gauge: 'г' },
    { ingredientKey: 'lemonJuice', count: 1, gauge: 'ч.л.' },
    { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
  ],
  equipments: [
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'paperTowel' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'spoon' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Огурцы нарежьте толстыми кружочками и промокните бумажным полотенцем, если они слишком влажные.',
      ingredients: [{ ingredientKey: 'cucumber', count: 2, gauge: 'шт.' }],
    },
    {
      img: null,
      video: null,
      description: 'Смешайте сливочный сыр с укропом, лимонным соком и перцем.',
      ingredients: [
        { ingredientKey: 'creamCheese', count: 120, gauge: 'г' },
        { ingredientKey: 'dill', count: 10, gauge: 'г' },
        { ingredientKey: 'lemonJuice', count: 1, gauge: 'ч.л.' },
        { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Выложите сыр на огурцы, сверху добавьте ломтики лосося и подавайте охлажденными.',
      ingredients: [{ ingredientKey: 'salmonSalted', count: 120, gauge: 'г' }],
    },
  ],
  historyDescription:
    'Канапе на овощной основе появились как легкая альтернатива бутербродам. Огурец дает свежесть и хруст, а лосось со сливочным сыром делает закуску праздничной без сложной подготовки.',
  tips: [
    'Выбирайте плотные огурцы с мелкими семенами.',
    'Собирайте канапе незадолго до подачи, чтобы огурец не пустил сок.',
  ],
  variations: [
    { name: 'С авокадо', changes: 'Замените часть сыра размятым авокадо.' },
    { name: 'С редисом', changes: 'Добавьте тонкий ломтик редиса для хруста.' },
  ],
}

export const TARTALETKI_S_KRABOVYMI_PALOCHKAMI = {
  metaSeo: createMetaSeo(
    'tartaletki-s-krabovymi-palochkami',
    'Тарталетки с крабовыми палочками',
    'Быстрые тарталетки с крабовыми палочками, кукурузой, огурцом и легкой заправкой.',
    ['тарталетки', 'закуска с крабовыми палочками', 'праздничная закуска', 'тарталетки с кукурузой'],
  ),
  searchRequests: ['тарталетки с крабовыми палочками', 'закуска в тарталетках', 'тарталетки с кукурузой'],
  categories: [{ name: 'snacks' }],
  key: 'tartaletki-s-krabovymi-palochkami',
  name: 'tartaletki-s-krabovymi-palochkami',
  img: null,
  title: 'Тарталетки с крабовыми палочками',
  description: 'Нарядная холодная закуска с крабовыми палочками, кукурузой и свежим огурцом.',
  calories: 214,
  preparation: 15,
  time: 0,
  level: 1,
  rating: 4.7,
  portions: 6,
  used: [9, 15, 18],
  ingredients: [
    { ingredientKey: 'tartlets', count: 12, gauge: 'шт.' },
    { ingredientKey: 'crabSticks', count: 200, gauge: 'г' },
    { ingredientKey: 'cannedCorn', count: 120, gauge: 'г' },
    { ingredientKey: 'cucumber', count: 1, gauge: 'шт.' },
    { ingredientKey: 'mayonnaise', count: 2, gauge: 'ст.л.' },
    { ingredientKey: 'dill', count: 10, gauge: 'г' },
  ],
  equipments: [
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'spoon' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Крабовые палочки и огурец нарежьте мелкими кубиками, укроп порубите.',
      ingredients: [
        { ingredientKey: 'crabSticks', count: 200, gauge: 'г' },
        { ingredientKey: 'cucumber', count: 1, gauge: 'шт.' },
        { ingredientKey: 'dill', count: 10, gauge: 'г' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Смешайте крабовые палочки, кукурузу, огурец, укроп и майонез.',
      ingredients: [
        { ingredientKey: 'cannedCorn', count: 120, gauge: 'г' },
        { ingredientKey: 'mayonnaise', count: 2, gauge: 'ст.л.' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Разложите начинку по тарталеткам прямо перед подачей, чтобы корзинки остались хрустящими.',
      ingredients: [{ ingredientKey: 'tartlets', count: 12, gauge: 'шт.' }],
    },
  ],
  historyDescription:
    'Тарталетки закрепились в домашнем праздничном меню как удобная порционная подача салатов и закусок. Крабовая начинка напоминает классический салат, но выглядит аккуратнее и быстрее расходится со стола.',
  tips: [
    'Не наполняйте тарталетки заранее: от влажной начинки они размокают.',
    'Огурец можно слегка отжать, если он очень сочный.',
  ],
  variations: [
    { name: 'С яйцом', changes: 'Добавьте мелко нарезанное вареное яйцо.' },
    { name: 'С сыром', changes: 'Вмешайте немного тертого твердого сыра.' },
  ],
}

export const SHAMPINONY_S_SYROM_V_DUHOVKE = {
  metaSeo: createMetaSeo(
    'shampinony-s-syrom-v-duhovke',
    'Шампиньоны с сыром в духовке',
    'Запеченные шампиньоны с сырной начинкой, чесноком и зеленью.',
    ['шампиньоны с сыром', 'закуска из грибов', 'грибы в духовке', 'горячая закуска'],
  ),
  searchRequests: ['шампиньоны с сыром в духовке', 'фаршированные шампиньоны', 'горячая закуска из грибов'],
  categories: [{ name: 'snacks' }],
  key: 'shampinony-s-syrom-v-duhovke',
  name: 'shampinony-s-syrom-v-duhovke',
  img: null,
  title: 'Шампиньоны с сыром в духовке',
  description: 'Горячая закуска из шляпок шампиньонов с сыром, чесноком и зеленью.',
  calories: 176,
  preparation: 15,
  time: 20,
  level: 1,
  rating: 4.8,
  portions: 4,
  used: [12, 14, 7],
  ingredients: [
    { ingredientKey: 'champignons', count: 500, gauge: 'г' },
    { ingredientKey: 'hardCheese', count: 120, gauge: 'г' },
    { ingredientKey: 'creamCheese', count: 80, gauge: 'г' },
    { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
    { ingredientKey: 'parsley', count: 10, gauge: 'г' },
    { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
  ],
  equipments: [
    { equipmentKey: 'oven' },
    { equipmentKey: 'bakingTray' },
    { equipmentKey: 'parchment' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'grater' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description:
        'Разогрейте духовку до 190°C. У шампиньонов удалите ножки, шляпки выложите на противень с пергаментом.',
      ingredients: [{ ingredientKey: 'champignons', count: 500, gauge: 'г' }],
    },
    {
      img: null,
      video: null,
      description: 'Смешайте тертый твердый сыр, сливочный сыр, чеснок, петрушку и перец.',
      ingredients: [
        { ingredientKey: 'hardCheese', count: 120, gauge: 'г' },
        { ingredientKey: 'creamCheese', count: 80, gauge: 'г' },
        { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
        { ingredientKey: 'parsley', count: 10, gauge: 'г' },
        { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Наполните шляпки сырной смесью и запекайте 18–20 минут до румяной верхушки.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Фаршированные шампиньоны — удобная горячая закуска, которая пришла из ресторанной подачи в домашние духовки. Грибная шляпка работает как маленькая форма, а сырная начинка делает блюдо сытным и ароматным.',
  tips: [
    'Выбирайте крупные шампиньоны одинакового размера.',
    'Не мойте грибы долго в воде: лучше быстро протереть или сполоснуть и обсушить.',
  ],
  variations: [
    { name: 'С беконом', changes: 'Добавьте в начинку обжаренный мелко нарезанный бекон.' },
    { name: 'С зеленью', changes: 'Замените петрушку укропом или зеленым луком.' },
  ],
}

export const RULETIKI_IZ_BAKLAZHANOV_S_FETOY = {
  metaSeo: createMetaSeo(
    'ruletiki-iz-baklazhanov-s-fetoy',
    'Рулетики из баклажанов с фетой',
    'Обжаренные ломтики баклажанов с начинкой из феты, зелени и чеснока.',
    ['рулетики из баклажанов', 'закуска с фетой', 'баклажаны с сыром', 'овощная закуска'],
  ),
  searchRequests: ['рулетики из баклажанов с фетой', 'баклажаны с сыром и чесноком', 'овощная закуска'],
  categories: [{ name: 'snacks' }],
  key: 'ruletiki-iz-baklazhanov-s-fetoy',
  name: 'ruletiki-iz-baklazhanov-s-fetoy',
  img: null,
  title: 'Рулетики из баклажанов с фетой',
  description: 'Ароматная овощная закуска из баклажанов с солоноватой фетой, зеленью и чесноком.',
  calories: 198,
  preparation: 20,
  time: 15,
  level: 2,
  rating: 4.8,
  portions: 4,
  used: [9, 12, 18],
  ingredients: [
    { ingredientKey: 'eggplant', count: 2, gauge: 'шт.' },
    { ingredientKey: 'fetaCheese', count: 150, gauge: 'г' },
    { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
    { ingredientKey: 'parsley', count: 15, gauge: 'г' },
    { ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' },
    { ingredientKey: 'salt', gauge: 'по вкусу' },
  ],
  equipments: [
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'pan' },
    { equipmentKey: 'bowl' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Баклажаны нарежьте длинными тонкими пластинами, посолите и оставьте на 10 минут, затем обсушите.',
      ingredients: [
        { ingredientKey: 'eggplant', count: 2, gauge: 'шт.' },
        { ingredientKey: 'salt', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Обжарьте баклажаны на оливковом масле до мягкости и легкой румяности.',
      ingredients: [{ ingredientKey: 'oliveOil', count: 2, gauge: 'ст.л.' }],
    },
    {
      img: null,
      video: null,
      description: 'Разомните фету с чесноком и петрушкой, выложите начинку на баклажаны и сверните рулетики.',
      ingredients: [
        { ingredientKey: 'fetaCheese', count: 150, gauge: 'г' },
        { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
        { ingredientKey: 'parsley', count: 15, gauge: 'г' },
      ],
    },
  ],
  historyDescription:
    'Рулетики из баклажанов часто встречаются в кавказской и средиземноморской домашней кухне. Обжаренный баклажан становится мягкой основой, а солоноватая сырная начинка дает блюду яркий вкус.',
  tips: [
    'Не нарезайте баклажаны слишком толсто, иначе рулетики будут плохо сворачиваться.',
    'Готовые пластины промокните от лишнего масла.',
  ],
  variations: [
    { name: 'С орехами', changes: 'Добавьте в начинку рубленые грецкие орехи.' },
    { name: 'С томатами', changes: 'Положите внутрь тонкую полоску свежего томата.' },
  ],
}

export const SYRNYE_SHARIKI_S_KUNZHUTOM = {
  metaSeo: createMetaSeo(
    'syrnye-shariki-s-kunzhutom',
    'Сырные шарики с кунжутом',
    'Холодная закуска из сливочного и твердого сыра в кунжутной обсыпке.',
    ['сырные шарики', 'закуска из сыра', 'сырная закуска', 'закуска с кунжутом'],
  ),
  searchRequests: ['сырные шарики', 'сырная закуска', 'закуска с кунжутом'],
  categories: [{ name: 'snacks' }],
  key: 'syrnye-shariki-s-kunzhutom',
  name: 'syrnye-shariki-s-kunzhutom',
  img: null,
  title: 'Сырные шарики с кунжутом',
  description: 'Порционная сырная закуска с чесноком, зеленью и кунжутной обсыпкой.',
  calories: 285,
  preparation: 15,
  time: 20,
  level: 1,
  rating: 4.7,
  portions: 6,
  used: [15, 22, 6],
  ingredients: [
    { ingredientKey: 'creamCheese', count: 180, gauge: 'г' },
    { ingredientKey: 'hardCheese', count: 120, gauge: 'г' },
    { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
    { ingredientKey: 'dill', count: 10, gauge: 'г' },
    { ingredientKey: 'sesameSeeds', count: 40, gauge: 'г' },
    { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
  ],
  equipments: [
    { equipmentKey: 'grater' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'spoon' },
    { equipmentKey: 'fridge' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Твердый сыр натрите, смешайте со сливочным сыром, чесноком, укропом и перцем.',
      ingredients: [
        { ingredientKey: 'hardCheese', count: 120, gauge: 'г' },
        { ingredientKey: 'creamCheese', count: 180, gauge: 'г' },
        { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
        { ingredientKey: 'dill', count: 10, gauge: 'г' },
        { ingredientKey: 'groundBlackPepper', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Сформируйте небольшие шарики и обваляйте их в кунжуте.',
      ingredients: [{ ingredientKey: 'sesameSeeds', count: 40, gauge: 'г' }],
    },
    {
      img: null,
      video: null,
      description: 'Охладите шарики 20 минут, чтобы они стали плотнее и лучше держали форму.',
      ingredients: [],
    },
  ],
  historyDescription:
    'Сырные шарики — домашний вариант порционных фуршетных закусок. Их удобно готовить заранее, менять обсыпку и подавать маленькими порциями без нарезки и сложной сервировки.',
  tips: [
    'Если масса липнет к рукам, охладите ее 10 минут перед формовкой.',
    'Кунжут можно слегка подсушить на сухой сковороде.',
  ],
  variations: [
    { name: 'С паприкой', changes: 'Часть шариков обваляйте в копченой паприке.' },
    { name: 'С орехами', changes: 'Замените кунжут мелко рублеными орехами.' },
  ],
}

export const KANAPE_S_SELDYU_I_SVEKLOY = {
  metaSeo: createMetaSeo(
    'kanape-s-seldyu-i-svekloy',
    'Канапе с сельдью и свеклой',
    'Мини-закуска на хлебе со свеклой, сельдью, луком и зеленью.',
    ['канапе с сельдью', 'закуска со свеклой', 'селедка на хлебе', 'праздничные канапе'],
  ),
  searchRequests: ['канапе с сельдью', 'селедка со свеклой', 'закуска на хлебе'],
  categories: [{ name: 'snacks' }],
  key: 'kanape-s-seldyu-i-svekloy',
  name: 'kanape-s-seldyu-i-svekloy',
  img: null,
  title: 'Канапе с сельдью и свеклой',
  description: 'Небольшие канапе с привычным сочетанием сельди, свеклы, лука и хлеба.',
  calories: 172,
  preparation: 20,
  time: 0,
  level: 1,
  rating: 4.8,
  portions: 6,
  used: [8, 10, 24],
  ingredients: [
    { ingredientKey: 'whiteBread', count: 6, gauge: 'ломтиков' },
    { ingredientKey: 'herringFillet', count: 180, gauge: 'г' },
    { ingredientKey: 'beet', count: 1, gauge: 'шт.' },
    { ingredientKey: 'redOnion', count: 1, gauge: 'шт.' },
    { ingredientKey: 'mayonnaise', count: 1, gauge: 'ст.л.' },
    { ingredientKey: 'dill', count: 10, gauge: 'г' },
  ],
  equipments: [
    { equipmentKey: 'knife' },
    { equipmentKey: 'cutBoard' },
    { equipmentKey: 'grater' },
    { equipmentKey: 'bowl' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Свеклу натрите и смешайте с майонезом. Лук нарежьте тонкими полукольцами.',
      ingredients: [
        { ingredientKey: 'beet', count: 1, gauge: 'шт.' },
        { ingredientKey: 'mayonnaise', count: 1, gauge: 'ст.л.' },
        { ingredientKey: 'redOnion', count: 1, gauge: 'шт.' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Хлеб нарежьте небольшими квадратами, сельдь — аккуратными кусочками.',
      ingredients: [
        { ingredientKey: 'whiteBread', count: 6, gauge: 'ломтиков' },
        { ingredientKey: 'herringFillet', count: 180, gauge: 'г' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'На хлеб выложите свеклу, сельдь, лук и укроп. Подавайте сразу или охладите 10 минут.',
      ingredients: [{ ingredientKey: 'dill', count: 10, gauge: 'г' }],
    },
  ],
  historyDescription:
    'Сельдь со свеклой — знакомое сочетание русской праздничной кухни. В формате канапе оно становится легче и аккуратнее: вкус напоминает классические салаты, но подается маленькими порциями.',
  tips: [
    'Свеклу лучше заранее отварить или запечь и полностью остудить.',
    'Хлеб можно слегка подсушить, чтобы канапе дольше держали форму.',
  ],
  variations: [
    { name: 'С соленым огурцом', changes: 'Добавьте тонкий ломтик маринованного огурца.' },
    { name: 'С горчицей', changes: 'Смажьте хлеб тонким слоем горчицы перед свеклой.' },
  ],
}

export const KABACHKOVYE_OLADI_S_SYROM = {
  metaSeo: createMetaSeo(
    'kabachkovye-oladi-s-syrom',
    'Кабачковые оладьи с сыром',
    'Нежные кабачковые оладьи с сыром, зеленью и чесноком на сковороде.',
    ['кабачковые оладьи', 'закуска из кабачков', 'оладьи с сыром', 'овощная закуска'],
  ),
  searchRequests: ['кабачковые оладьи с сыром', 'закуска из кабачков', 'оладьи из кабачков на сковороде'],
  categories: [{ name: 'snacks' }],
  key: 'kabachkovye-oladi-s-syrom',
  name: 'kabachkovye-oladi-s-syrom',
  img: null,
  title: 'Кабачковые оладьи с сыром',
  description: 'Сочные овощные оладьи из кабачка с сыром и зеленью — хороши горячими и холодными.',
  calories: 206,
  preparation: 15,
  time: 15,
  level: 1,
  rating: 4.8,
  portions: 4,
  used: [10, 13, 22],
  ingredients: [
    { ingredientKey: 'zucchini', count: 2, gauge: 'шт.' },
    { ingredientKey: 'hardCheese', count: 100, gauge: 'г' },
    { ingredientKey: 'eggs', count: 1, gauge: 'шт.' },
    { ingredientKey: 'flour', count: 3, gauge: 'ст.л.' },
    { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
    { ingredientKey: 'dill', count: 10, gauge: 'г' },
    { ingredientKey: 'vegetableOil', count: 2, gauge: 'ст.л.' },
    { ingredientKey: 'salt', gauge: 'по вкусу' },
  ],
  equipments: [
    { equipmentKey: 'grater' },
    { equipmentKey: 'bowl' },
    { equipmentKey: 'pan' },
    { equipmentKey: 'spatula' },
  ],
  cookingRecipe: [
    {
      img: null,
      video: null,
      description: 'Кабачки натрите, посолите и оставьте на 5 минут, затем хорошо отожмите лишний сок.',
      ingredients: [
        { ingredientKey: 'zucchini', count: 2, gauge: 'шт.' },
        { ingredientKey: 'salt', gauge: 'по вкусу' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Смешайте кабачки с тертым сыром, яйцом, мукой, чесноком и укропом.',
      ingredients: [
        { ingredientKey: 'hardCheese', count: 100, gauge: 'г' },
        { ingredientKey: 'eggs', count: 1, gauge: 'шт.' },
        { ingredientKey: 'flour', count: 3, gauge: 'ст.л.' },
        { ingredientKey: 'garlic', count: 1, gauge: 'зубчик' },
        { ingredientKey: 'dill', count: 10, gauge: 'г' },
      ],
    },
    {
      img: null,
      video: null,
      description: 'Жарьте небольшие оладьи на разогретом масле по 2–3 минуты с каждой стороны до румяности.',
      ingredients: [{ ingredientKey: 'vegetableOil', count: 2, gauge: 'ст.л.' }],
    },
  ],
  historyDescription:
    'Кабачковые оладьи — практичный сезонный рецепт, который часто появляется летом, когда кабачки особенно доступные. Сыр делает вкус насыщеннее, а зелень и чеснок превращают простые овощные оладьи в полноценную закуску.',
  tips: [
    'Обязательно отжимайте кабачок, иначе тесто получится жидким.',
    'Жарьте небольшими порциями: так оладьи легче переворачивать.',
  ],
  variations: [
    { name: 'С йогуртовым соусом', changes: 'Подайте с натуральным йогуртом, чесноком и зеленью.' },
    { name: 'С морковью', changes: 'Добавьте немного тертой моркови для сладости и цвета.' },
  ],
}
